Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2020-07, with the labels that each got.

#1500 storage: disable bucket lifecycle management
  storage/buckets/buckets_test.go
  storage/buckets/disable_bucket_lifecycle_management.go
Labels: cla: yes

#1550 translate: skip flaky glossary test
  translate/v3/batch_translate_text_with_glossary_test.go
Labels: cla: yes

#1547 storage: reuse testutil.CleanBucket
  storage/objects/objects_test.go
Labels: cla: yes

#1558 healthcare: add comment clarifying payload body when patching FHIR resource
  healthcare/fhir_resource_patch.go
Labels: cla: yes

#1552 testing: skip modules with a newer version than toolchain
  internal/gomodversiontest/go.mod
  internal/gomodversiontest/main.go
  testing/kokoro/system_tests.sh
Labels: cla: yes

#1524 feat: add run_events_pubsub
  run/events_pubsub/Dockerfile
  run/events_pubsub/go.mod
  run/events_pubsub/go.sum
  run/events_pubsub/main.go
  run/events_pubsub/main_test.go
Labels: api: run, cla: yes, priority: p1, type: feature request

#1546 testing, .github: remove autoformat, move go vet and tidy to Actions
  .github/workflows/autoformat.yaml
  .github/workflows/go.yaml
  testing/kokoro/system_tests.sh
Labels: cla: yes

#1562 all: update deps
  appengine/go11x/warmup/go.mod
  appengine/go11x/warmup/go.sum
  functions/bigtable/go.mod
  functions/bigtable/go.sum
  functions/console_snippets/firebase_auth/go.sum
  functions/console_snippets/firebase_rtdb/go.sum
  functions/console_snippets/firestore/go.sum
  functions/console_snippets/google_analytics/go.sum
  functions/firebase/hello/go.sum
  functions/helloworld/storage_generic/go.sum
  functions/imagemagick/go.mod
  functions/imagemagick/go.sum
  functions/log/go.mod
  functions/log/go.sum
  functions/ocr/app/go.mod
  functions/ocr/app/go.sum
  functions/slack/go.mod
  functions/slack/go.sum
  functions/spanner/go.mod
  functions/spanner/go.sum
  functions/tips/contexttip/go.mod
  functions/tips/contexttip/go.sum
  functions/tips/go.mod
  functions/tips/go.sum
  functions/tips/infinite_retries/go.sum
  getting-started/authenticating-users/go.sum
  getting-started/background/go.mod
  getting-started/background/go.sum
  getting-started/bookshelf/go.mod
  getting-started/bookshelf/go.sum
  go.mod
  go.sum
  internal/cloudrunci/testingapp/go.mod
  internal/cloudrunci/testingapp/go.sum
  profiler/shakesapp/go.mod
  profiler/shakesapp/go.sum
  run/events_pubsub/go.mod
  run/events_pubsub/go.sum
  run/grpc-ping/go.mod
  run/grpc-ping/go.sum
  run/hello-broken/go.mod
  run/hello-broken/go.sum
  run/image-processing/go.mod
  run/image-processing/go.sum
  run/logging-manual/go.sum
  run/markdown-preview/editor/go.mod
  run/markdown-preview/editor/go.sum
  run/markdown-preview/renderer/go.mod
  run/markdown-preview/renderer/go.sum
  run/system_package/go.mod
  run/system_package/go.sum
Labels: cla: yes

#1553 datastore: admin export/import samples
  datastore/admin/datastore_admin_entities_export.go
  datastore/admin/datastore_admin_test.go
Labels: cla: yes

#1368 run/markdown-preview: use %w error handling
  run/markdown-preview/editor/render.go
  run/markdown-preview/editor/service.go
Labels: api: run, automerge, cla: yes, type: cleanup

#1563 cloudsql: add Postgres sample
  cloudsql/postgres/database-sql/Dockerfile
  cloudsql/postgres/database-sql/README.md
  cloudsql/postgres/database-sql/app.flexible.yaml
  cloudsql/postgres/database-sql/app.standard.yaml
  cloudsql/postgres/database-sql/cloudsql.go
  cloudsql/postgres/database-sql/go.mod
  cloudsql/postgres/database-sql/go.sum
  cloudsql/postgres/database-sql/templates/index.html
Labels: automerge, cla: yes

#1509 spanner: use timestamp+uuid for db names
  spanner/spanner_snippets/spanner/integration_test.go
Labels: api: spanner, automerge, cla: yes

#1575 storage: unflake TestKMSObjects
  storage/objects/objects_test.go
Labels: automerge, cla: yes

#1577 testing: attempt to make mtls_smoketest more green
  testing/kokoro/mtls_smoketest.bash
  testing/kokoro/system_tests.sh
Labels: automerge, cla: yes

#1578 testing/kokoro: chmod +x mtls_smoketest.bash
  testing/kokoro/mtls_smoketest.bash
Labels: cla: yes

#1579 internal/e2e: skip Go11xStatic
  internal/e2e/standard_test.go
Labels: cla: yes

#1567 gaming/servers: add samples cloud gaming
  gaming/servers/create_cluster.go
  gaming/servers/create_config.go
  gaming/servers/create_deployment.go
  gaming/servers/create_realm.go
  gaming/servers/delete_cluster.go
  gaming/servers/delete_config.go
  gaming/servers/delete_deployment.go
  gaming/servers/delete_realm.go
  gaming/servers/deployment_test.go
  gaming/servers/doc.go
  gaming/servers/get_cluster.go
  gaming/servers/get_config.go
  gaming/servers/get_deployment.go
  gaming/servers/get_realm.go
  gaming/servers/get_rollout.go
  gaming/servers/list_clusters.go
  gaming/servers/list_configs.go
  gaming/servers/list_deployments.go
  gaming/servers/list_realms.go
  gaming/servers/realm_test.go
  gaming/servers/update_rollout_default.go
  gaming/servers/update_rollout_override.go
  gaming/servers/update_rollout_remove_default.go
  gaming/servers/update_rollout_remove_override.go
  go.mod
  go.sum
Labels: cla: yes

#1564 cloudsql: update MySQL sample
  cloudsql/mysql/database-sql/README.md
  cloudsql/mysql/database-sql/app.flexible.yaml
  cloudsql/mysql/database-sql/app.standard.yaml
  cloudsql/mysql/database-sql/cloudsql.go
  cloudsql/mysql/database-sql/go.mod
Labels: automerge, cla: yes

#1538 memorystore: add Dockerfile for Cloud Run deployment
  badfiles_test.go
  memorystore/redis/.gcloudignore
  memorystore/redis/cloud_run_deployment/Dockerfile
  memorystore/redis/go.mod
  memorystore/redis/go.sum
Labels: automerge, cla: yes

#1581 .github: assign 'api: run' issues to grayside
  .github/blunderbuss.yml
Labels: cla: yes

#1543 profiler: add WithTelemetryDisabled for OpenCensus users
  profiler/snippets/snippets.go
Labels: automerge, cla: yes, kokoro:run

#1583 gaming: fix game server delete cluster tag
  gaming/servers/delete_cluster.go
Labels: cla: yes

#1586 gaming: remove empty DefaultGameServerConfig initialization
  gaming/servers/update_rollout_remove_override.go
Labels: cla: yes

#1588 gaming: skip tests for mtls (known bad)
  gaming/servers/deployment_test.go
Labels: automerge, cla: yes

#1589 all: mtls_smoketest - move skip to bash script, add more
  bigquery/bigquery_storage_quickstart/main_test.go
  gaming/servers/deployment_test.go
  internal/mtls_smoketest/smoketest_test.go
  internal/testutil/testutil.go
  testing/kokoro/system_tests.sh
  vision/detect/detect_test.go
  vision/detect/set_endpoint_test.go
  vision/label/label_test.go
  vision/product_search/mtls_smoketest_test.go
Labels: cla: yes

#1590 testing: skip bad mtls by removing go files
  internal/mtls_smoketest/smoketest_test.go
  testing/kokoro/mtls_smoketest.bash
  testing/kokoro/system_tests.sh
Labels: cla: yes

#1593 testing: skip functions/ocr/app in mtls_smoketest
  internal/mtls_smoketest/smoketest_test.go
  testing/kokoro/mtls_smoketest.bash
Labels: cla: yes

#1594 spanner: add a sample to set custom timeout and retry
  go.mod
  go.sum
  spanner/spanner_snippets/spanner/integration_test.go
  spanner/spanner_snippets/spanner/spanner_set_custom_timeout_and_retry.go
Labels: api: spanner, automerge, cla: yes

#1512 securitycenter: update golang sample with new mutable field
  go.sum
  securitycenter/notifications/update_notification_config.go
Labels: cla: yes

#1601 functions: delete unused functions sample
  functions/helloworld/hello_pubsub.go
Labels: cla: yes

#1605 .github: assign dataproc issues to bradmiro
  .github/blunderbuss.yml
Labels: cla: yes

#1597 run/events_pubsub: re-enable test
  run/events_pubsub/go.mod
  run/events_pubsub/main_test.go
Labels: automerge, cla: yes

#1608 dataproc: add retries to flaky cluster_create test
  dataproc/create_cluster_test.go
Labels: automerge, cla: yes

#1599 firestore: add LimitToLast samples
  firestore/firestore_snippets/query.go
  go.mod
  go.sum
Labels: automerge, cla: yes

#1604 pubsub: add subscription detach samples
  pubsub/subscriptions/detach_subscription.go
  pubsub/subscriptions/subscription_test.go
Labels: cla: yes

#1607 opencensus: add a sample for trace exemplar
  opencensus/trace_exemplar.go
  opencensus/trace_exemplar_test.go
Labels: automerge, cla: yes

#1612 testing: only include a specific set of services for mtls tests
  testing/kokoro/mtls_smoketest.bash
Labels: cla: yes

#1561 asset: add samples for ListAssets v1p5beta1
  asset/quickstart/list-assets/main.go
  asset/quickstart/list-assets/main_test.go
Labels: cla: yes

#1617 feat(run/markdown-preview): use client library to mint identity tokens
  run/markdown-preview/editor/go.mod
  run/markdown-preview/editor/go.sum
  run/markdown-preview/editor/render.go
Labels: api: run, cla: yes, type: feature request
