Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2020-10, with the labels that each got.

#1743 testing(eventarc): move eventarc e2e tests from run
  eventarc/testing/audit_storage.e2e_test.go
  eventarc/testing/go.mod
  eventarc/testing/go.sum
  eventarc/testing/pubsub.e2e_test.go
Labels: cla: yes

#1746 test(spanner): skip ListBackupOperations
  spanner/spanner_snippets/spanner/integration_test.go
Labels: api: spanner, cla: yes, samples

#1739 fix(iam): remove old quickstart
  iam/quickstart/quickstart.go
  iam/quickstart/quickstart_test.go
  iam/quickstartv2/quickstart.go
  iam/quickstartv2/quickstart_test.go
Labels: api: iam, automerge, cla: yes, samples

#1545 spanner: only keep necessary CLIs in snippet.go
  spanner/spanner_snippets/snippet.go
Labels: api: spanner, automerge, cla: yes, samples

#1751 refactor(functions/tips/contexttip): contexttip sample for pubsub publish
  functions/tips/contexttip/context_tip.go
  functions/tips/contexttip/context_tip_test.go
Labels: cla: yes

#1733 chore: Updated appengine samples to 1.14
  appengine/go11x/cloudsql/app.yaml
  appengine/go11x/helloworld/app.yaml
  appengine/go11x/helloworld/go.mod
  appengine/go11x/pubsub/authenicated_push/app.yaml
  appengine/go11x/tasks/handle_task/Dockerfile
  appengine/go11x/tasks/handle_task/app.yaml
  appengine/go11x/warmup/app.yaml
Labels: api: appengine, cla: yes, samples

#1755 fix(storage): rename print_bucket_aCL.go to print_bucket_acl.go
  storage/acl/print_bucket_acl.go
Labels: cla: yes

#1756 fix(storage): rename print_file_aCL->print_file_acl
  storage/acl/print_file_acl.go
Labels: cla: yes

#1758 fix(spanner): fix flaky leaderboard test
  spanner/spanner_leaderboard/leaderboard_test.go
Labels: api: spanner, cla: yes, samples

#1744 feat(pubsub): add attributes sample and cleanup region tags
  pubsub/subscriptions/async_pull_custom_attributes.go
  pubsub/subscriptions/subscription_test.go
  pubsub/topics/publish.go
  pubsub/topics/publish_scale.go
Labels: api: pubsub, automerge, cla: yes, samples

#1757 chore(functions/pubsub): fix region tags + rename env var
  functions/tips/contexttip/context_tip.go
Labels: api: cloudfunctions, cla: yes, samples

#1764 fix(bigquery): minor refactor to avoid pushback failures
  bigquery/snippets/table/integration_test.go
Labels: api: bigquery, cla: yes, samples

#1766 refactor(logging): debrand stackdriver logging in favor of cloud logging
  functions/log/process_log_entry.go
  getting-started/bookshelf/bookshelf.go
  logging/logging_quickstart/main.go
  logging/stdlogging/main.go
  run/hello-broken/main.go
  run/logging-manual/main.go
Labels: automerge, cla: yes

#1767 feat: add eventarc generic snippet
  eventarc/generic/Dockerfile
  eventarc/generic/go.mod
  eventarc/generic/main.go
  eventarc/generic/main_test.go
Labels: automerge, cla: yes

#1768 fix(datastore): close clients
  datastore/snippets/snippet_test.go
Labels: cla: yes

#1770 fix(dialogflow): remove the cmd options
  dialogflow/detect_intent/detect_intent.go
  dialogflow/detect_intent/detect_intent_test.go
  dialogflow/intent_management/intent_management.go
  dialogflow/intent_management/intent_management_test.go
Labels: automerge, cla: yes

#1771 test(spanner): increase timeout and cleanup test
  spanner/spanner_leaderboard/leaderboard.go
  spanner/spanner_leaderboard/leaderboard_test.go
Labels: cla: yes

#1780 chore(.github): disable major updates, update prefix
  .github/renovate.json
Labels: cla: yes

#1773 chore(.github): add logging code owner: observability dpe
  .github/CODEOWNERS
  .github/blunderbuss.yml
Labels: automerge, cla: yes, samples

#1781 fix: fix eventarc audit output
  eventarc/audit_storage/main.go
  eventarc/audit_storage/main_test.go
Labels: automerge, cla: yes

#1790 chore: updates region tags
  videointelligence/annotate/object_tracking.go
  videointelligence/annotate/object_tracking_gcs.go
  videointelligence/annotate/text_detection.go
  videointelligence/annotate/text_detection_gcs.go
  videointelligence/video_analyze/video_analyze.go
  videointelligence/video_analyze/video_analyze_gcs.go
Labels: cla: yes, samples

#1792 test(storage): add retry to s3sdk test
  storage/s3_sdk/s3_gcs_test.go
Labels: api: storage, automerge, cla: yes

#1789 fix(pubsub): correct comment in resume publish
  pubsub/topics/publish_resume_ordering.go
Labels: api: pubsub, cla: yes, samples

#1793 fix(storage): fix TestListenChanges flakey test
  firestore/firestore_snippets/listen_test.go
Labels: api: storage, cla: yes, samples

#1785 feature(datacatalog): add datacatalog policy tag manager snippets
  datacatalog/snippets/policytagmanager/create_policytag.go
  datacatalog/snippets/policytagmanager/create_taxonomy.go
  datacatalog/snippets/policytagmanager/delete_policytag.go
  datacatalog/snippets/policytagmanager/delete_taxonomy.go
  datacatalog/snippets/policytagmanager/get_iam_policy.go
  datacatalog/snippets/policytagmanager/get_policytag.go
  datacatalog/snippets/policytagmanager/get_taxonomy.go
  datacatalog/snippets/policytagmanager/integration_test.go
  datacatalog/snippets/policytagmanager/list_policytags.go
  datacatalog/snippets/policytagmanager/list_taxonomies.go
  datacatalog/snippets/policytagmanager/set_iam_policy.go
  datacatalog/snippets/policytagmanager/test_iam_permissions.go
Labels: api: datacatalog, cla: yes, do not merge, samples

#1798 fix: #1795 endpoints sample mustEmbedUnimplemented
  endpoints/getting-started-grpc/server/main.go
Labels: automerge: exact, cla: yes, samples

#1802 chore: add team to codeowners for error reporting
  .github/CODEOWNERS
  .github/blunderbuss.yml
Labels: api: clouderrorreporting, automerge, cla: yes, lang: go, priority: p2, samples, type: process

#1801 test(logging): remove TestSimpleLog flakiness and reduce test run time
  logging/simplelog/simplelog.go
  logging/simplelog/simplelog_test.go
Labels: api: logging, automerge, cla: yes, samples

#1803 docs: update running system tests instructions
  CONTRIBUTING.md
Labels: automerge, cla: yes, type: docs

#1722 feat(storage): sample gap (1/2 object part)
  storage/objects/copy_file_archived_generation.go
  storage/objects/delete_file_archived_generation.go
  storage/objects/disable_versioning.go
  storage/objects/enable_versioning.go
  storage/objects/generate_encryption_key.go
  storage/objects/objects_test.go
  storage/service_account/service_account.go
  storage/service_account/service_account_test.go
Labels: api: storage, cla: yes, samples

#1806 fix(storage): add retry to TestBucketWebsiteInfo
  storage/buckets/buckets_test.go
Labels: automerge, cla: yes

#1807 docs(CONTRIBUTING): remove extra fmt.Sprintf
  CONTRIBUTING.md
Labels: automerge, cla: yes

#1788 refactor: improve eventarc go samples
  eventarc/audit_storage/go.mod
  eventarc/audit_storage/main.go
  eventarc/generic/go.mod
  eventarc/generic/main.go
  eventarc/generic/main_test.go
  eventarc/pubsub/go.mod
  eventarc/pubsub/main.go
Labels: api: eventarc, cla: yes, samples

#1805 feat(logging): advanced log write sample
  logging/advancedlog/main.go
  logging/advancedlog/main_test.go
Labels: api: logging, cla: yes, priority: p2, samples, type: docs
