Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2020-05, with the labels that each got.

#1393 dlp: enable inspect tests and only test jobs were created
  dlp/snippets/inspect/inspect_bigquery.go
  dlp/snippets/inspect/inspect_datastore.go
  dlp/snippets/inspect/inspect_gcs.go
  dlp/snippets/inspect/inspect_test.go
Labels: cla: yes

#1394 appengine: add a go.mod to every app
  appengine/go11x/cloudsql/go.mod
  appengine/go11x/cloudsql/go.sum
  appengine/go11x/helloworld/go.mod
  appengine/go11x/tasks/handle_task/go.mod
  appengine/go11x/warmup/go.mod
  appengine/go11x/warmup/go.sum
Labels: cla: yes

#1378 iap: add samples using new idtoken package
  .gitignore
  badfiles_test.go
  go.mod
  go.sum
  iap/request.go
  iap/validate.go
Labels: automerge, cla: yes

#1397 .github: create CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes

#1398 badfiles_test: add CODEOWNERS file
  badfiles_test.go
Labels: cla: yes

#1400 spanner: fix DBs conflict in different tests.
  spanner/spanner_leaderboard/leaderboard_test.go
Labels: api: spanner, cla: yes, type: bug

#1380 functions: add sample calling a function with an ID token
  functions/security/README.md
  functions/security/idtoken.go
  functions/security/security_system_test.go
  go.mod
  go.sum
Labels: cla: yes

#985 testing: include region tags in XML test output
  badfiles_test.go
  go.mod
  go.sum
  regiontag_test.go
  testing/kokoro/system_tests.sh
  testing/sampletests/fakesamples/differentmodule/go.mod
  testing/sampletests/fakesamples/differentmodule/should_not_be_checked.go
  testing/sampletests/fakesamples/hello.go
  testing/sampletests/fakesamples/hello_test.go
  testing/sampletests/fakesamples/samemodule/has_region_tags.go
  testing/sampletests/main.go
  testing/sampletests/main_test.go
  testing/sampletests/testdata/raw_log.xml
Labels: cla: yes

#1403 functions: update ocr sample to use environment variables
  functions/ocr/app/config.json
  functions/ocr/app/detect.go
  functions/ocr/app/ocr_test.go
  functions/ocr/app/save.go
  functions/ocr/app/setup.go
  functions/ocr/app/translate.go
Labels: automerge, cla: yes

#1406 testing/sampletests: work with function references
  testing/sampletests/fakesamples/hello.go
  testing/sampletests/fakesamples/hello_test.go
  testing/sampletests/main.go
  testing/sampletests/main_test.go
Labels: cla: yes

#1407 firestore: add imports to quickstart
  firestore/firestore_quickstart/main.go
Labels: cla: yes

#1392 storage: add PostPolicyV4 sample
  go.mod
  go.sum
  storage/objects/generate_signed_post_policy_v4.go
  storage/objects/objects_test.go
Labels: cla: yes

#1411 run: update main.go with missing region tag
  run/grpc-ping/main.go
Labels: cla: yes

#1414 GCF cloudbuild.yaml: clarify "runtime" + "dir" args
  functions/ci_cd/cloudbuild.yaml
Labels: cla: yes

#1416 healthcare: more retries
  healthcare/hl7v2_test.go
Labels: cla: yes

#1425 pubsub: refactor pull samples
  pubsub/subscriptions/async_pull.go
  pubsub/subscriptions/subscription_test.go
  pubsub/subscriptions/sync_pull.go
Labels: cla: yes

#1417 trace/trace_quickstart: use Google Cloud propagation in server
  trace/trace_quickstart/main.go
Labels: automerge, cla: yes

#1389 Adding golang samples for ServiceDirectory
  servicedirectory/create_endpoint.go
  servicedirectory/create_namespace.go
  servicedirectory/create_service.go
  servicedirectory/delete_endpoint.go
  servicedirectory/delete_namespace.go
  servicedirectory/delete_service.go
  servicedirectory/quickstart/quickstart.go
  servicedirectory/resolve_service.go
  servicedirectory/service_directory_test.go
Labels: cla: yes
