Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2020-08, with the labels that each got.

#1603 fix: make sure go.mod matches actual language level
  cloudsql/sqlserver/database-sql/go.mod
  go.sum
  opencensus/metrics_quickstart/go.mod
  opencensus/metrics_quickstart/go.sum
Labels: cla: yes

#1164 feat(run): grpc-server-streaming sample
  license_test.go
  run/grpc-server-streaming/Dockerfile
  run/grpc-server-streaming/README.md
  run/grpc-server-streaming/api/v1/timeservice.proto
  run/grpc-server-streaming/client/client.go
  run/grpc-server-streaming/e2e_test.go
  run/grpc-server-streaming/go.mod
  run/grpc-server-streaming/go.sum
  run/grpc-server-streaming/pkg/api/v1/timeservice.pb.go
  run/grpc-server-streaming/server/main.go
Labels: automerge, cla: yes

#1616 docs(all): update contributing guide
  CONTRIBUTING.md
Labels: cla: yes

#1585 storage: listing noncurrent object versions
  internal/testutil/storage_cleaner.go
  storage/objects/list_files_all_version.go
  storage/objects/objects_test.go
Labels: cla: yes

#1582 fix(functions): remove redundant GCS sample
  functions/helloworld/go.mod
  functions/helloworld/go.sum
  functions/helloworld/hello_cloud_storage.go
  functions/helloworld/hello_cloud_storage_test.go
  functions/helloworld/storage_generic/go.mod
  functions/helloworld/storage_generic/go.sum
  functions/helloworld/storage_generic/hello_storage_generic.go
  functions/helloworld/storage_generic/hello_storage_generic_test.go
  go.mod
  go.sum
Labels: automerge, cla: yes

#1614 refactor(run/grpc-ping): use client library to mint identity token
  run/grpc-ping/go.mod
  run/grpc-ping/go.sum
  run/grpc-ping/request_auth.go
Labels: api: run, cla: yes, type: cleanup

#1630 fix(bigtable): add retry for writing data test
  bigtable/writes/writes_test.go
Labels: cla: yes

#1624 refactor(run/markdown-preview): remove unauthenticated mode
  run/markdown-preview/editor/render.go
  run/markdown-preview/editor/service.go
Labels: cla: yes

#1629 fix(functions/codelabs): fix file reading on go113
  functions/codelabs/gopher/gopher.go
Labels: automerge, cla: yes

#1633 test(run): skip broken test
  run/grpc-server-streaming/e2e_test.go
Labels: cla: yes

#1636 chore(gaming): update gaming/servers to use v1 API from betav1
  gaming/servers/create_cluster.go
  gaming/servers/create_config.go
  gaming/servers/create_deployment.go
  gaming/servers/create_realm.go
  gaming/servers/delete_cluster.go
  gaming/servers/delete_config.go
  gaming/servers/delete_deployment.go
  gaming/servers/delete_realm.go
  gaming/servers/get_cluster.go
  gaming/servers/get_config.go
  gaming/servers/get_deployment.go
  gaming/servers/get_realm.go
  gaming/servers/get_rollout.go
  gaming/servers/list_clusters.go
  gaming/servers/list_configs.go
  gaming/servers/list_deployments.go
  gaming/servers/list_realms.go
  gaming/servers/update_rollout_default.go
  gaming/servers/update_rollout_override.go
  gaming/servers/update_rollout_remove_default.go
  gaming/servers/update_rollout_remove_override.go
  go.mod
  go.sum
Labels: cla: yes

#1637 feat(run): reuse function idtoken sample
  functions/security/idtoken.go
  functions/security/security_system_test.go
Labels: automerge, cla: yes

#1643 refactor(functions): yaml indentation
  functions/ci_cd/cloudbuild.yaml
Labels: cla: yes

#1644 test(asset): add retries and use UUIDs
  asset/quickstart/create-feed/main_test.go
  asset/quickstart/delete-feed/main_test.go
Labels: automerge, cla: yes

#1625 feat(pubsub): add ordering key samples
  go.mod
  go.sum
  pubsub/subscriptions/create_ordering.go
  pubsub/subscriptions/subscription_test.go
  pubsub/topics/publish_ordering.go
  pubsub/topics/publish_resume_ordering.go
  pubsub/topics/topics_test.go
Labels: automerge, cla: yes

#1641 fix(cloudsql): remove SQL Server Unix socket code
  cloudsql/sqlserver/database-sql/README.md
  cloudsql/sqlserver/database-sql/cloudsql.go
Labels: automerge, cla: yes

#1649 fix(profiler): close connections/clients in shakesapp to fix memory leak
  profiler/shakesapp/shakesapp/client.go
  profiler/shakesapp/shakesapp/server.go
Labels: cla: yes

#1652 chore: upgrade to doublestar v2
  badfiles_test.go
  go.mod
  go.sum
Labels: automerge, cla: yes

#1651 chore(functions/firebase): upgrade firebase.google.com/go to v4
  functions/firebase/upper/go.mod
  functions/firebase/upper/go.sum
  functions/firebase/upper/upper.go
Labels: automerge, cla: yes

#1654 fix: use valid run service name for e2e test
  run/events_pubsub/e2e_test.go
  run/events_storage/e2e_test.go
Labels: automerge, cla: yes

#1656 chore(getting-started/background): add test retries
  getting-started/background/go.mod
  getting-started/background/go.sum
  getting-started/background/translate_test.go
Labels: cla: yes

#1660 feat(profiler): add flags for enabling collection of different profile types
  profiler/shakesapp/main.go
Labels: cla: yes

#1662 feat(testing/docker): add Go 1.15, use single Dockerfile, add cloudbuild.yaml
  testing/docker/Dockerfile
  testing/docker/Dockerfile.go111
  testing/docker/Dockerfile.go112
  testing/docker/Dockerfile.go113
  testing/docker/Dockerfile.go114
  testing/docker/README.md
  testing/docker/cloudbuild.yaml
Labels: cla: yes

#1661 fix(internal/aeintegrate): correct minor typo
  internal/aeintegrate/aeintegrate.go
Labels: automerge: exact, cla: yes, kokoro:run

#1634 chore(functions): remove redundant logging sample
  functions/log/go.mod
  functions/log/go.sum
  functions/log/list.go
  functions/log/list_test.go
Labels: cla: yes, do not merge

#1670 test(securitycenter/notifications): add retry
  securitycenter/notifications/notifications_test.go
Labels: cla: yes

#1671 test: add go115, remove go112-go114
  CONTRIBUTING.md
  testing/kokoro/go112.cfg
  testing/kokoro/go113.cfg
  testing/kokoro/go115.cfg
Labels: cla: yes

#1668 feat(iam): update quickstart samples
  iam/quickstartv2/quickstart.go
  iam/quickstartv2/quickstart_test.go
Labels: api: iam, automerge, cla: yes, samples

#1676 fix(run/events-storage): e2e test checking for invalid criteria
  run/events_storage/e2e_test.go
Labels: api: run, automerge, cla: yes

#1683 fix(.github): only create single failure-indicator file
  .github/workflows/go.yaml
Labels: cla: yes

#1677 test(securitycenter): add retries to all tests
  securitycenter/assets/assets_test.go
  securitycenter/findings/findings_test.go
  securitycenter/settings/settings_test.go
Labels: api: securitycenter, automerge, cla: yes, samples

#1680 refactor(run): upgrade all Dockerfiles to Go 1.15
  run/events_pubsub/Dockerfile
  run/events_storage/Dockerfile
  run/grpc-server-streaming/Dockerfile
  run/hello-broken/Dockerfile
  run/image-processing/Dockerfile
  run/logging-manual/Dockerfile
  run/markdown-preview/editor/Dockerfile
  run/markdown-preview/renderer/Dockerfile
  run/system_package/Dockerfile
Labels: api: run, automerge, cla: yes, samples

#1684 fix(opentelemetry): building requires 1.13
  opentelemetry/go.mod
Labels: automerge, cla: yes

#1685 chore(opentelemetry): upgrade otel and opentelemetry-operations-go
  opentelemetry/go.mod
  opentelemetry/go.sum
  opentelemetry/trace/main.go
Labels: automerge, cla: yes

#1686 test(dataproc): make quickstart test delete before retry and E2E
  dataproc/quickstart/quickstart_test.go
Labels: automerge, cla: yes
