Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2020-04, with the labels that each got.

#1295 dialogflow: remove unused code samples
  dialogflow/context_management/context_management.go
  dialogflow/context_management/context_management_test.go
  dialogflow/entity_management/entity_management.go
  dialogflow/entity_management/entity_management_test.go
  dialogflow/entity_type_management/entity_type_management.go
  dialogflow/entity_type_management/entity_type_management_test.go
  dialogflow/session_entity_type_management/session_entity_type_management.go
  dialogflow/session_entity_type_management/session_entity_type_management_test.go
Labels: cla: yes

#1308 pubsub: update publish with batch settings sample to queue 10 messages
  pubsub/topics/publish_settings.go
  pubsub/topics/topics_test.go
Labels: cla: yes

#1328 dataproc: clean proto formatting a bit
  dataproc/instantiate_inline_workflow_template.go
Labels: cla: yes

#1329 datastore: fix namespace sample
  datastore/snippets/snippet_test.go
Labels: cla: yes

#1334 functions/ci_cd: make region tags consistent across languages
  functions/ci_cd/cloudbuild.yaml
Labels: cla: yes

#1343 functions/slack: fix typo
  functions/slack/search.go
Labels: cla: yes

#1340 all: create testutil.CleanBucket, add storage retries
  asset/quickstart/export-assets/main_test.go
  dataproc/quickstart/quickstart_test.go
  healthcare/fhir_test.go
  internal/testutil/storage_cleaner.go
  storage/acl/acl_test.go
  storage/buckets/buckets_test.go
  storage/buckets/set_bucket_default_kms_key.go
  storage/gcsupload/gcsupload_test.go
  storage/service_account/hmac/hmac_test.go
  vision/detect/detect_test.go
Labels: cla: yes

#1345 dlp: only wait for 1 minute for risk jobs
  dlp/snippets/risk/categorical.go
  dlp/snippets/risk/k_anonymity.go
  dlp/snippets/risk/k_map.go
  dlp/snippets/risk/l_diversity.go
  dlp/snippets/risk/numerical.go
  dlp/snippets/risk/risk_test.go
Labels: cla: yes

#1348 storage: extend timeouts for SA HMAC samples
  storage/service_account/hmac/activate.go
  storage/service_account/hmac/create.go
  storage/service_account/hmac/deactivate.go
  storage/service_account/hmac/delete.go
  storage/service_account/hmac/get.go
  storage/service_account/hmac/list.go
Labels: cla: yes

#1361 securitycenter/notifications: skip broken tests
  securitycenter/notifications/create_notification_config.go
  securitycenter/notifications/delete_notification_config.go
  securitycenter/notifications/doc.go
  securitycenter/notifications/get_notification_config.go
  securitycenter/notifications/list_notification_configs.go
  securitycenter/notifications/notifications_test.go
  securitycenter/notifications/receive_notifications.go
  securitycenter/notifications/update_notification_config.go
Labels: cla: yes

#1344 healthcare API: update all samples from v1beta1 to v1
  go.mod
  go.sum
  healthcare/dataset_create.go
  healthcare/dataset_deidentify.go
  healthcare/dataset_delete.go
  healthcare/dataset_get.go
  healthcare/dataset_iam_get.go
  healthcare/dataset_iam_set.go
  healthcare/dataset_list.go
  healthcare/dataset_patch.go
  healthcare/dicom_export.go
  healthcare/dicom_iam_get.go
  healthcare/dicom_iam_set.go
  healthcare/dicom_import.go
  healthcare/dicom_store_create.go
  healthcare/dicom_store_delete.go
  healthcare/dicom_store_get.go
  healthcare/dicom_store_list.go
  healthcare/dicom_store_patch.go
  healthcare/dicomweb_instance_retrieve.go
  healthcare/dicomweb_instance_store.go
  healthcare/dicomweb_rendered_retrieve.go
  healthcare/dicomweb_study_delete.go
  healthcare/dicomweb_study_retrieve.go
  healthcare/dicomweb_study_search.go
  healthcare/fhir_execute_bundle.go
  healthcare/fhir_iam_get.go
  healthcare/fhir_iam_set.go
  healthcare/fhir_metadata_get.go
  healthcare/fhir_resource_create.go
  healthcare/fhir_resource_delete.go
  healthcare/fhir_resource_export.go
  healthcare/fhir_resource_get.go
  healthcare/fhir_resource_get_everything.go
  healthcare/fhir_resource_history_get.go
  healthcare/fhir_resource_history_list.go
  healthcare/fhir_resource_import.go
  healthcare/fhir_resource_patch.go
  healthcare/fhir_resource_purge.go
  healthcare/fhir_resource_search.go
  healthcare/fhir_resource_update.go
  healthcare/fhir_store_create.go
  healthcare/fhir_store_delete.go
  healthcare/fhir_store_get.go
  healthcare/fhir_store_list.go
  healthcare/fhir_store_patch.go
  healthcare/hl7v2_iam_get.go
  healthcare/hl7v2_iam_set.go
  healthcare/hl7v2_message_create.go
  healthcare/hl7v2_message_delete.go
  healthcare/hl7v2_message_get.go
  healthcare/hl7v2_message_ingest.go
  healthcare/hl7v2_message_list.go
  healthcare/hl7v2_message_patch.go
  healthcare/hl7v2_store_create.go
  healthcare/hl7v2_store_delete.go
  healthcare/hl7v2_store_get.go
  healthcare/hl7v2_store_list.go
  healthcare/hl7v2_store_patch.go
  healthcare/internal/dicomweb-instance-search/dicomweb_instance_search.go
Labels: cla: yes

#1341 kms: add new samples and adopt new format
  go.mod
  go.sum
  kms/add_member_cryptokey.go
  kms/add_member_keyring.go
  kms/asymmetric_test.go
  kms/create_key_asymmetric_decrypt.go
  kms/create_key_asymmetric_sign.go
  kms/create_key_hsm.go
  kms/create_key_labels.go
  kms/create_key_ring.go
  kms/create_key_rotation_schedule.go
  kms/create_key_symmetric_encrypt_decrypt.go
  kms/create_key_version.go
  kms/decrypt_asymmetric.go
  kms/decrypt_symmetric.go
  kms/destroy_key_version.go
  kms/disable_key_version.go
  kms/enable_key_version.go
  kms/encrypt_asymmetric.go
  kms/encrypt_rsa.go
  kms/encrypt_symmetric.go
  kms/get_cryptokey_policy.go
  kms/get_key.go
  kms/get_key_labels.go
  kms/get_keyring_policy.go
  kms/get_public_key.go
  kms/iam_add_member.go
  kms/iam_get_policy.go
  kms/iam_remove_member.go
  kms/kms_helpers_test.go
  kms/kms_test.go
  kms/remove_member_cryptokey.go
  kms/remove_member_keyring.go
  kms/restore_key_version.go
  kms/sign.go
  kms/sign_asymmetric.go
  kms/snippets_test.go
  kms/update_key_add_rotation.go
  kms/update_key_remove_labels.go
  kms/update_key_remove_rotation.go
  kms/update_key_set_primary.go
  kms/update_key_update_labels.go
  kms/verify_asymmetric_ec.go
  kms/verify_asymmetric_rsa.go
  kms/verify_ec.go
  kms/verify_rsa.go
Labels: cla: yes

#1358 bigquery: address streaming error logic in storage sample
  bigquery/bigquery_storage_quickstart/main.go
Labels: cla: yes

#1357 functions: delete unused SQL samples
  functions/sql/mysql/go.mod
  functions/sql/mysql/go.sum
  functions/sql/mysql/mysql.go
  functions/sql/mysql/mysql_test.go
  functions/sql/postgres/go.mod
  functions/sql/postgres/go.sum
  functions/sql/postgres/postgres.go
  functions/sql/postgres/postgres_test.go
Labels: cla: yes

#1366 kms: add sample for getting key attestation
  kms/get_key_version_attestation.go
  kms/kms_helpers_test.go
  kms/kms_test.go
Labels: cla: yes

#1359 functions: add "gcf filesystem is not persistent" note
  functions/http/form.go
Labels: automerge, cla: yes

#1367 all: upgrade spanner and proto
  go.mod
  go.sum
Labels: cla: yes

#1286 cdn: add SignCookie example w/ tests
  cdn/signedcookies/sign_cookie.go
  cdn/signedcookies/sign_cookie_test.go
  cdn/signedurls/signurl.go
  cdn/signedurls/signurl_test.go
Labels: cla: yes

#1298 cloudsql: use '--update-env-vars' in Cloud Run deploy
  cloudsql/mysql/database-sql/README.md
Labels: automerge, cla: yes

#1140 asset: add export to BigQuery
  asset/quickstart/export-assets-bigquery/main.go
  asset/quickstart/export-assets-bigquery/main_test.go
Labels: cla: yes

#1371 kms: skip, don't fail, when GOLANG_SAMPLES_PROJECT_ID is unset
  kms/kms_test.go
Labels: cla: yes

#1374 vision: use t.SystemTest for endpoint test
  vision/detect/set_endpoint_test.go
Labels: cla: yes

#1377 securitycenter/asset: skip broken test, small style fixes
  securitycenter/assets/assets_test.go
Labels: cla: yes

#1379 securitycenter: fix broken ListAssets test, stop skipping tests
  securitycenter/assets/assets_test.go
  securitycenter/notifications/notifications_test.go
Labels: cla: yes

#1382 fix: use DELETE FROM for consistency
  spanner/spanner_snippets/snippet.go
Labels: api: spanner, cla: yes

#1384 datastore: make dst slice for GetMulti
  datastore/snippets/snippet_test.go
Labels: cla: yes

#1383 functions: cloud bigtable reading function example
  functions/bigtable/bigtable.go
  functions/bigtable/bigtable_test.go
  functions/bigtable/go.mod
  functions/bigtable/go.sum
Labels: cla: yes

#1385 functions: update slack sample to use environment variables
  functions/slack/config.json
  functions/slack/search.go
  functions/slack/setup.go
  functions/slack/slack_test.go
Labels: automerge, cla: yes

#1386 spanner: remove double hyphens to be consistent with other tests.
  spanner/spanner_leaderboard/leaderboard_test.go
Labels: automerge, cla: yes
