Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2020-06, with the labels that each got.

#1428 translate: correct wrong glossary method
  translate/v3/translate_text_with_glossary.go
  translate/v3/translate_text_with_glossary_and_model.go
Labels: cla: yes

#1434 CONTRIBUTING.md: add a few more points
  CONTRIBUTING.md
Labels: cla: yes

#1433 testing/kokoro: add Firestore project
  testing/kokoro/system_tests.sh
Labels: automerge, cla: yes

#1437 logging: fix region tag
  logging/simplelog/simplelog.go
Labels: automerge, cla: yes

#1436 healthcare: fix retries
  healthcare/dicom_test.go
Labels: cla: yes

#1432 appengine/go11x/tasks: use r.Header.Get
  appengine/go11x/tasks/handle_task/handle_task.go
Labels: automerge, cla: yes

#1440 monitorying/uptime: add retries to TestCreate
  monitoring/uptime/uptime_test.go
Labels: cla: yes

#1441 logging/simplelog: enable test, increase retry pauses
  logging/simplelog/simplelog_test.go
Labels: cla: yes

#1438 all: enable and fix issues from shellcheck
  .github/workflows/go.yaml
  getting-started/devflowapp/deployment/sed_wrapper.sh
  getting-started/gce/startup-script.sh
  getting-started/gopher-run/cmd/training.sh
  memorystore/redis/gce_deployment/deploy.sh
  memorystore/redis/gce_deployment/startup-script.sh
  testing/docker/bootstrap.sh
  testing/kokoro/system_tests.sh
  testing/kokoro/trampoline.sh
Labels: cla: yes

#1439 bigquery: add reservation quickstart
  bigquery/bigquery_reservation_quickstart/main.go
  bigquery/bigquery_reservation_quickstart/main_test.go
Labels: automerge, cla: yes

#1429 testing/kokoro: add mtls_smoketest config
  testing/kokoro/mtls_smoketest.cfg
Labels: cla: yes

#1442 all: remove legacy health check handlers
  appengine_flexible/helloworld/helloworld.go
  appengine_flexible/websockets/main.go
  appengine_flexible/websockets/main_test.go
  getting-started/bookshelf/main.go
  getting-started/devflowapp/devflowapp.go
  getting-started/helloworld/helloworld.go
Labels: automerge, cla: yes

#1448 healthcare API: add comment to clarify that deleted FHIR resources wi…
  healthcare/fhir_resource_delete.go
Labels: cla: yes

#1449 .github: switch to Dependabot
  .github/dependabot.yml
  .github/renovate.json
Labels: cla: yes

#1456 badfiles_test: add dependabot config
  badfiles_test.go
Labels: cla: yes

#1458 all: upgrade root dependencies
  go.mod
  go.sum
Labels: cla: yes

#1457 .config, testing: add Blunderbuss config
  .config/blunderbuss.yml
  badfiles_test.go
  testing/kokoro/system_tests.sh
  testing/kokoro/trampoline.sh
Labels: cla: yes

#1445 functions/helloworld: expand logging sample, update README
  functions/helloworld/README.md
  functions/helloworld/hello_logging.go
Labels: api: cloudfunctions, cla: yes

#1443 functions: document source code location
  functions/tips/file_system.go
  functions/tips/serverless_function_source_code/README.md
Labels: cla: yes

#1463 datastore: put key creation in examples
  datastore/snippets/snippet_test.go
Labels: cla: yes

#1475 .github: add autoformat Action
  .github/workflows/autoformat.yml
  .github/workflows/go.yaml
Labels: cla: yes

#1479 .github: rename to autoformat.yaml
  .github/workflows/autoformat.yaml
Labels: cla: yes

#1478 .github/workflows: clarify autoformat message
  .github/workflows/go.yaml
Labels: automerge, cla: yes

#1481 .github: add Action to run root tests
  .github/workflows/go.yaml
Labels: cla: yes

#1480 testing/kokoro: GOLANG_SAMPLES_E2E_TEST=1 for mtls_smoketest
  testing/kokoro/mtls_smoketest.cfg
Labels: automerge, cla: yes

#1487 spanner: add create_clients sample
  spanner/spanner_snippets/spanner/integration_test.go
  spanner/spanner_snippets/spanner/spanner_create_clients.go
  spanner/spanner_snippets/spanner/spanner_read_stale_data.go
Labels: api: spanner, cla: yes

#1489 spanner: update spanner_delete_data sample
  spanner/spanner_snippets/spanner/spanner_delete_data.go
Labels: automerge, cla: yes

#1493 firestore: make tests EndToEnd
  firestore/firestore_snippets/collection_group_test.go
  firestore/firestore_snippets/increment_test.go
  firestore/firestore_snippets/save_test.go
  firestore/firestore_snippets/solution_counters_test.go
Labels: cla: yes

#1491 .github: expand Blunderbuss config
  .github/blunderbuss.yml
Labels: cla: yes

#1495 dataproc/quickstart: add test retries
  dataproc/quickstart/quickstart_test.go
Labels: cla: yes

#1424 storage: enable bucket object lifecycle management
  storage/buckets/buckets_test.go
  storage/buckets/enable_bucket_lifecycle_management.go
Labels: cla: yes

#1501 dlp: update samples to include locations/global in parent field
  dlp/quickstart/quickstart.go
  dlp/snippets/deid/date_shift.go
  dlp/snippets/deid/deid_fpe.go
  dlp/snippets/deid/mask.go
  dlp/snippets/deid/reid_fpe.go
  dlp/snippets/inspect/inspect_bigquery.go
  dlp/snippets/inspect/inspect_datastore.go
  dlp/snippets/inspect/inspect_gcs.go
  dlp/snippets/inspect/inspect_string.go
  dlp/snippets/inspect/inspect_text_file.go
  dlp/snippets/jobs/jobs_test.go
  dlp/snippets/jobs/list.go
  dlp/snippets/redact/redact.go
  dlp/snippets/risk/categorical.go
  dlp/snippets/risk/k_anonymity.go
  dlp/snippets/risk/k_map.go
  dlp/snippets/risk/l_diversity.go
  dlp/snippets/risk/numerical.go
  dlp/snippets/template/create.go
  dlp/snippets/template/list.go
  dlp/snippets/template/template_test.go
  dlp/snippets/trigger/create.go
  dlp/snippets/trigger/list.go
  dlp/snippets/trigger/trigger_test.go
Labels: cla: yes

#1490 spanner: add spanner_create_instance sample.
  spanner/spanner_snippets/spanner/integration_test.go
  spanner/spanner_snippets/spanner/spanner_create_instance.go
Labels: api: spanner, cla: yes

#1506 Clarify infinite retries example
  functions/tips/infinite_retries/infinite_retries.go
Labels: automerge, cla: yes

#1518 firestore: use project-specific collection/doc names
  firestore/firestore_snippets/collection_group_setup.go
  firestore/firestore_snippets/collection_group_test.go
  firestore/firestore_snippets/increment.go
  firestore/firestore_snippets/increment_test.go
Labels: cla: yes

#1514 pubsub: unflake sync pull test
  pubsub/subscriptions/sync_pull.go
Labels: api: pubsub, automerge, cla: yes

#1499 monitoring: demonstrate creation of a POST uptime check to go along with the GET uptime check
  monitoring/uptime/uptime.go
  monitoring/uptime/uptime_test.go
Labels: cla: yes

#1519 .github: switch back to Renovate
  .github/dependabot.yml
  .github/renovate.json
  badfiles_test.go
Labels: cla: yes

#1520 healthcare API: fix some instances where hl7V2Stores was incorrectly capitalized in URL path
  healthcare/hl7v2_iam_get.go
  healthcare/hl7v2_iam_set.go
  healthcare/hl7v2_store_get.go
  healthcare/hl7v2_store_patch.go
Labels: cla: yes

#1523 pubsub: unflake dead letter delivery attempt test
  pubsub/subscriptions/subscription_test.go
Labels: api: pubsub, cla: yes

#1521 healthcare: add "rendered" suffix to dicomWebPath comment
  healthcare/dicomweb_rendered_retrieve.go
Labels: cla: yes

#1522 healthcare: updates to DICOMweb instance search
  healthcare/dicom_test.go
  healthcare/dicomweb_instance_search.go
Labels: cla: yes

#1496 bigtable: update region tags for reads and filters
  bigtable/filters/filters.go
  bigtable/reads/reads.go
Labels: cla: yes

#1530 vision/product_set: add retries to remove test
  vision/product_search/remove_product_from_product_set_test.go
Labels: cla: yes

#1505 asset: add samples for SearchAllResources and SearchAllIamPolicies
  asset/quickstart/search-all-iam-policies/main.go
  asset/quickstart/search-all-iam-policies/main_test.go
  asset/quickstart/search-all-resources/main.go
  asset/quickstart/search-all-resources/main_test.go
Labels: cla: yes

#1409 datastore: samples for Datastore Admin API
  datastore/admin/datastore_admin_client_create.go
  datastore/admin/datastore_admin_entities_export.go
  datastore/admin/datastore_admin_entities_import.go
  datastore/admin/datastore_admin_index_get.go
  datastore/admin/datastore_admin_index_list.go
  datastore/admin/datastore_admin_test.go
Labels: automerge, cla: yes

#1534 all: bump cloud.google.com/go/storage to v1.10.0
  go.mod
  go.sum
Labels: cla: yes

#1412 functions/helloworld: clarify that pubsub message data is already decoded
  functions/helloworld/hello_pubsub.go
Labels: cla: yes

#1537 healthcare: add clarifying comment for FHIR update resource
  healthcare/fhir_resource_update.go
Labels: cla: yes

#1544 monitoring/irm: delete unused samples
  monitoring/irm/annotate_incident.go
  monitoring/irm/change_severity.go
  monitoring/irm/change_stage.go
  monitoring/irm/create_incident.go
  monitoring/irm/create_signal.go
  monitoring/irm/doc.go
  monitoring/irm/irm_test.go
Labels: cla: yes

#1390 cloudsql: SQL Server sample
  cloudsql/sqlserver/database-sql/Dockerfile
  cloudsql/sqlserver/database-sql/README.md
  cloudsql/sqlserver/database-sql/app.yaml
  cloudsql/sqlserver/database-sql/cloudsql.go
  cloudsql/sqlserver/database-sql/go.mod
  cloudsql/sqlserver/database-sql/go.sum
  cloudsql/sqlserver/database-sql/templates/index.html
Labels: cla: yes

#1548 dlp: increase timeout, use unique topic/sub names for tests
  dlp/snippets/inspect/inspect_bigquery.go
  dlp/snippets/inspect/inspect_datastore.go
  dlp/snippets/inspect/inspect_gcs.go
  dlp/snippets/inspect/inspect_test.go
  dlp/snippets/risk/categorical.go
  dlp/snippets/risk/k_anonymity.go
  dlp/snippets/risk/k_map.go
  dlp/snippets/risk/l_diversity.go
  dlp/snippets/risk/numerical.go
  dlp/snippets/risk/risk_test.go
Labels: cla: yes
