Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2020-09, with the labels that each got.

#1673 feat(run/helloworld): New helloworld sample for Cloud Run
  run/helloworld/.dockerignore
  run/helloworld/.gcloudignore
  run/helloworld/Dockerfile
  run/helloworld/e2e_test.go
  run/helloworld/go.mod
  run/helloworld/go.sum
  run/helloworld/main.go
  run/helloworld/main_test.go
Labels: api: run, cla: yes, samples

#1410 chore(run): add region tag
  run/grpc-ping/api/v1/message.proto
Labels: api: run, automerge, cla: yes, samples

#1693 docs(cloudsql): add Postgres GAE Flex sample comment
  cloudsql/postgres/database-sql/cloudsql.go
  cloudsql/postgres/database-sql/go.mod
  cloudsql/postgres/database-sql/go.sum
Labels: automerge, cla: yes, samples

#1692 feat(storage): add CustomTime to metadata sample
  go.mod
  go.sum
  run/testing/go.sum
  storage/objects/get_metadata.go
Labels: api: storage, cla: yes, samples

#1618 feat(firestore): query watch samples
  firestore/firestore_snippets/listen_changes.go
  firestore/firestore_snippets/listen_document.go
  firestore/firestore_snippets/listen_errors.go
  firestore/firestore_snippets/listen_multiple.go
  firestore/firestore_snippets/listen_test.go
Labels: api: firestore, cla: yes, samples

#1698 fix(appengine)!: remove unused static sample
  appengine/go11x/static/app.yaml
  appengine/go11x/static/go.mod
  appengine/go11x/static/main.go
  appengine/go11x/static/public/gcp-gopher.svg
  appengine/go11x/static/public/style.css
  appengine/go11x/static/templates/index.html
  internal/e2e/standard_test.go
Labels: cla: yes, samples

#1700 tests(translate): skip flaky TestBatchTranslateText
  translate/v3/batch_translate_text_test.go
Labels: automerge, cla: yes

#1699 chore(storage): remove unused sample
  storage/gcsupload/README.md
  storage/gcsupload/gcsupload.go
  storage/gcsupload/gcsupload_test.go
Labels: automerge, cla: yes

#1705 chore: added examples of environment variable values to Cloud SQL samples
  cloudsql/mysql/database-sql/cloudsql.go
  cloudsql/postgres/database-sql/cloudsql.go
  cloudsql/sqlserver/database-sql/cloudsql.go
Labels: cla: yes

#1708 feat(spanner): add numeric samples
  go.mod
  go.sum
  run/testing/go.sum
  spanner/spanner_snippets/spanner/integration_test.go
  spanner/spanner_snippets/spanner/spanner_add_numeric_column.go
  spanner/spanner_snippets/spanner/spanner_query_with_numeric_parameter.go
  spanner/spanner_snippets/spanner/spanner_update_data_with_numeric_column.go
Labels: api: spanner, cla: yes, samples

#1711 chore(testing/sampletests): make its own module
  go.mod
  testing/kokoro/system_tests.sh
  testing/sampletests/go.mod
  testing/sampletests/go.sum
Labels: automerge, cla: yes

#1710 fix(run/system_package): correct minor typos of comment in code
  run/system_package/graphviz.go
Labels: api: run, automerge, cla: yes, samples

#1717 test(storage): add retry to hmac TestGetKey
  storage/service_account/hmac/hmac_test.go
Labels: api: storage, automerge, cla: yes, samples

#1724 docs(appengine): remove master_slave region tags
  docs/appengine/datastore/consistency/consistency.go
Labels: cla: yes

#1714 fix(storage): add viewing the CORS configuration
  storage/buckets/get_bucket_metadata.go
Labels: api: storage, automerge, cla: yes, samples

#1723 fix(functions/console_snippets/http): error handling and unit tests
  functions/console_snippets/http/http.go
  functions/console_snippets/http/http_test.go
Labels: api: cloudfunctions, automerge, cla: yes, samples

#1731 feat: move run/events to eventarc/
  eventarc/audit_storage/Dockerfile
  eventarc/audit_storage/go.mod
  eventarc/audit_storage/go.sum
  eventarc/audit_storage/main.go
  eventarc/audit_storage/main_test.go
  eventarc/pubsub/Dockerfile
  eventarc/pubsub/go.mod
  eventarc/pubsub/go.sum
  eventarc/pubsub/main.go
  eventarc/pubsub/main_test.go
Labels: automerge, cla: yes, samples

#1732 feat(healthcare): add test for listHL7V2Messages
  healthcare/hl7v2_test.go
Labels: automerge, cla: yes

#1738 fix(functions/console_snippets): http snippet should not have comma i…
  functions/console_snippets/http/http.go
  functions/console_snippets/http/http_test.go
Labels: automerge, cla: yes
