Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2021-05, with the labels that each got.

#2076 chore: disable Renovate for pubsublite
  .github/renovate.json
Labels: cla: yes, samples

#2077 fix(endpoints): rename the flag for better readability
  endpoints/getting-started/client/main.go
Labels: automerge, cla: yes, samples

#2085 test(storage): HMAC test fixes
  storage/service_account/hmac/hmac_test.go
Labels: api: storage, cla: yes, samples

#2086 fix(run): Update product name in comment
  run/logging-manual/main.go
Labels: cla: yes, samples

#2059 docs(appengine): add comment about authenticated push JWT token validation
  appengine/go11x/pubsub/authenicated_push/main.go
  appengine/go11x/pubsub/authenicated_push/main_test.go
Labels: api: appengine, automerge: exact, cla: yes, samples

#2084 refactor(pubsub): make test resources unique and improve cleanup
  pubsub/subscriptions/subscription_test.go
  pubsub/topics/topics_test.go
Labels: api: pubsub, cla: yes, samples

#2089 feat(secretmanager): add example code for receiving a Pub/Sub notification from Secret Manager
  secretmanager/consume_event_notification.go
  secretmanager/secretmanager_test.go
Labels: cla: yes, samples
