Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2021-01, with the labels that each got.

#1875 chore: update GAE samples to Go 1.15
  appengine/go11x/cloudsql/app.yaml
  appengine/go11x/helloworld/app.yaml
  appengine/go11x/pubsub/authenicated_push/app.yaml
  appengine/go11x/tasks/handle_task/app.yaml
  appengine/go11x/warmup/app.yaml
Labels: api: appengine, automerge, cla: yes, samples

#1878 chore(speech): quickstart now uses a gcs file
  speech/speech_quickstart/main.go
Labels: api: speech, automerge, cla: yes, samples

#1885 chore(videointelligence): increase logo detection timeout to other lang standards
  videointelligence/annotate/logo_detection.go
  videointelligence/annotate/logo_detection_gcs.go
Labels: automerge, cla: yes, samples

#1892 feat: update service directory samples to v1
  servicedirectory/create_endpoint.go
  servicedirectory/create_namespace.go
  servicedirectory/create_service.go
  servicedirectory/delete_endpoint.go
  servicedirectory/delete_namespace.go
  servicedirectory/delete_service.go
  servicedirectory/quickstart/quickstart.go
  servicedirectory/resolve_service.go
Labels: automerge, cla: yes, kokoro:run, samples

#1894 chore(servicedirectory): fix error text
  servicedirectory/resolve_service.go
Labels: api: servicedirectory, automerge, cla: yes, samples

#1896 fix: Update opentelemetry version to v0.15.0
  opentelemetry/go.mod
  opentelemetry/go.sum
  opentelemetry/trace/main.go
Labels: cla: yes, samples

#1899 ci(all): allow nightly tests on specific submodules
  testing/kokoro/system_tests.sh
Labels: automerge, cla: yes, priority: p2, samples, type: process

#1887 feat: add h2c sample for Cloud Run
  badfiles_test.go
  internal/cloudrunci/cloudrunci.go
  run/h2c/README.md
  run/h2c/app.json
  run/h2c/go.mod
  run/h2c/go.sum
  run/h2c/main.go
  run/testing/go.mod
  run/testing/h2c.e2e_test.go
Labels: cla: yes, samples

#1913 fix(run/h2c): instructions
  run/h2c/README.md
Labels: api: run, automerge, cla: yes, samples

#1907 chore(appengine_flexible): rm unused memcache sample
  appengine_flexible/memcache/app.yaml
  appengine_flexible/memcache/memcache.go
  eventarc/testing/go.sum
  go.mod
  go.sum
  run/testing/go.sum
Labels: cla: yes, samples

#1918 fix(run/h2c): move http2 to options
  run/h2c/app.json
Labels: automerge, cla: yes, samples

#1906 chore(appengine_flexible): rm unused sql samples
  appengine_flexible/cloudsql/README.md
  appengine_flexible/cloudsql/app.yaml
  appengine_flexible/cloudsql/cloudsql.go
  appengine_flexible/cloudsql_postgres/README.md
  appengine_flexible/cloudsql_postgres/app.yaml
  appengine_flexible/cloudsql_postgres/cloudsql.go
  eventarc/testing/go.sum
  go.mod
  go.sum
  run/testing/go.sum
Labels: automerge, cla: yes, samples

#1917 chore: update to pull in latest flakybot
  testing/kokoro/system_tests.sh
Labels: cla: yes, samples

#1916 fix(storage): clarify makePublic sample
  storage/objects/make_public.go
  storage/objects/objects_test.go
Labels: api: storage, automerge, cla: yes, samples

#1922 test(media): increase number of retries
  media/transcoder/transcoder_test.go
Labels: cla: yes, samples

#1893 fix(endpoints): update gke deployment apiVersion to apps/v1
  endpoints/getting-started-grpc/deployment.yaml
Labels: cla: yes, samples
