Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2021-08, with the labels that each got.

#2172 feat: add snippet for bigquery_revoke_dataset_access
  bigquery/snippets/dataset/bigquery_revoke_dataset_access.go
  bigquery/snippets/dataset/integration_test.go
Labels: cla: yes, samples

#2173 docs(firestore): incorporate a var to sample, improve docstrings
  datastore/snippets/snippet_test.go
Labels: api: firestore, cla: yes, samples

#2174 fix(compute): iterator to match new return values
  compute/list_instances.go
  eventarc/testing/go.sum
  go.mod
  go.sum
  monitoring/go.mod
  monitoring/go.sum
  run/testing/go.sum
Labels: api: compute, cla: yes, samples

#2168 test(storage): Improve logging for objects test
  storage/objects/objects_test.go
Labels: cla: yes, api: storage, samples

#2183 fix(asset): fix tests
  asset/quickstart/analyze-iam-policy-longrunning-bigquery/main_test.go
  asset/quickstart/analyze-iam-policy-longrunning-gcs/main_test.go
Labels: cla: yes, api: cloudasset, samples

#2185 chore(dlp): skip failing test
  dlp/snippets/inspect/inspect_test.go
Labels: cla: yes, api: dlp, samples

#2180 feat(pubsublite): add seek subscription sample
  eventarc/testing/go.sum
  go.mod
  go.sum
  monitoring/go.mod
  monitoring/go.sum
  pubsublite/admin/pubsublite_admin_test.go
  pubsublite/admin/seek_subscription.go
  run/testing/go.sum
Labels: automerge, cla: yes, samples, api: pubsublite

#2184 feat: update Transcoder API samples to v1
  media/transcoder/create_job_from_ad_hoc.go
  media/transcoder/create_job_from_preset.go
  media/transcoder/create_job_from_template.go
  media/transcoder/create_job_template.go
  media/transcoder/create_job_with_animated_overlay.go
  media/transcoder/create_job_with_periodic_images_spritesheet.go
  media/transcoder/create_job_with_set_number_images_spritesheet.go
  media/transcoder/create_job_with_static_overlay.go
  media/transcoder/delete_job.go
  media/transcoder/delete_job_template.go
  media/transcoder/get_job.go
  media/transcoder/get_job_state.go
  media/transcoder/get_job_template.go
  media/transcoder/list_job_templates.go
  media/transcoder/list_jobs.go
Labels: cla: yes, samples

#2178 feat(spanner): add samples for setting default leader
  spanner/spanner_snippets/spanner/integration_test.go
  spanner/spanner_snippets/spanner/spanner_create_database_with_default_leader.go
  spanner/spanner_snippets/spanner/spanner_get_database_ddl.go
  spanner/spanner_snippets/spanner/spanner_get_instance_config.go
  spanner/spanner_snippets/spanner/spanner_list_databases.go
  spanner/spanner_snippets/spanner/spanner_list_instance_configs.go
  spanner/spanner_snippets/spanner/spanner_query_information_schema_database_options.go
  spanner/spanner_snippets/spanner/spanner_update_database_with_default_leader.go
Labels: cla: yes, api: spanner, samples

#2177 feat: Functions v2 sample
  functions/functionsv2/helloworld/go.mod
  functions/functionsv2/helloworld/go.sum
  functions/functionsv2/helloworld/hello_pubsub.go
  functions/functionsv2/helloworld/hello_pubsub_test.go
Labels: cla: yes, api: cloudfunctions, samples

#2197 fix(kms): asymmetric public key ec error message
  kms/verify_asymmetric_ec.go
Labels: cla: yes, api: cloudkms, automerge: exact, samples

#2193 feat(spanner): add samples for request priorities
  spanner/spanner_snippets/spanner/integration_test.go
  spanner/spanner_snippets/spanner/spanner_batch_client_request_priority.go
  spanner/spanner_snippets/spanner/spanner_dml_batch_update_request_priority.go
  spanner/spanner_snippets/spanner/spanner_dml_partitioned_update_request_priority.go
  spanner/spanner_snippets/spanner/spanner_dml_standard_insert_request_priority.go
  spanner/spanner_snippets/spanner/spanner_query_request_priority.go
  spanner/spanner_snippets/spanner/spanner_read_request_priority.go
Labels: cla: yes, api: spanner, samples

#2201 fix(datacatalog): add small delay in quickstart test to avoid test flakes.
  datacatalog/datacatalog_quickstart/main_test.go
Labels: cla: yes, api: datacatalog, samples

#2181 downscope(examples): show credential downscoping with CAB
  auth/downscoping/credential_initialization.go
  auth/downscoping/downscoped_test.go
  auth/downscoping/initialize_CAB.go
  auth/downscoping/token_broker.go
  auth/downscoping/token_consumer.go
Labels: automerge, cla: yes, samples

#2209 chore: disable dep dashboard
  .github/renovate.json
Labels: automerge, cla: yes, samples

#2210 chore: skip some vision tests
  vision/product_search/get_similar_products_uri_test.go
  vision/product_search/get_similar_products_uri_with_filter_test.go
  vision/product_search/get_similar_products_with_filter_test.go
Labels: automerge, cla: yes, samples

#2212 fix(compute): fix compute samples after taking breaking change
  compute/create_instance.go
  compute/delete_instance.go
  compute/disable_usage_export.go
  compute/set_usage_export_bucket.go
  compute/wait_for_operation.go
  eventarc/testing/go.sum
  go.mod
  go.sum
  monitoring/go.mod
  monitoring/go.sum
  run/testing/go.sum
Labels: cla: yes, api: compute, samples
