Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2021-12, with the labels that each got.

#2304 feat(functionsv2): Add sample for Audit Logs
  functions/functionsv2/helloauditlog/go.mod
  functions/functionsv2/helloauditlog/go.sum
  functions/functionsv2/helloauditlog/hello_auditlog.go
  functions/functionsv2/helloauditlog/hello_auditlog_test.go
Labels: cla: yes, samples

#2309 chore: update CO to make samples-reviewers group the fallback
  .github/CODEOWNERS
Labels: cla: yes, samples

#2301 feat(gaming): add update samples
  gaming/servers/deployment_test.go
  gaming/servers/realm_test.go
  gaming/servers/update_cluster.go
  gaming/servers/update_deployment.go
  gaming/servers/update_realm.go
Labels: cla: yes, samples

#2313 fix(compute): fix compute API usage after some breaking changes
  compute/create_instance.go
  compute/create_instance_from_template_test.go
  compute/create_instance_from_template_with_overrides.go
  compute/firewall/create_firewall_rule.go
  compute/start_stop_instances_test.go
  eventarc/testing/go.sum
  go.mod
  go.sum
  monitoring/go.mod
  monitoring/go.sum
  opencensus/go.mod
  opencensus/go.sum
  run/testing/go.sum
  spanner/go.mod
  spanner/go.sum
Labels: cla: yes, api: compute, samples

#2318 feat(storage): update SignedURL samples to handle auth for user
  storage/objects/generate_v4_get_object_signed_url.go
  storage/objects/generate_v4_put_object_signed_url.go
  storage/objects/objects_test.go
Labels: api: storage, samples

#2329 test(spanner): unskip flaky tests and add method to read instance config name from environment
  spanner/spanner_snippets/spanner/integration_test.go
  testing/cloudbuild/run.bash
  testing/kokoro/system_tests.sh
Labels: api: spanner, samples

#2320 feat(functions): New v2 sample for GCE labeling on new instance creation
  functions/functionsv2/label_gce_instance/go.mod
  functions/functionsv2/label_gce_instance/go.sum
  functions/functionsv2/label_gce_instance/label_gce_instance.go
  functions/functionsv2/label_gce_instance/label_gce_instance_test.go
Labels: api: cloudfunctions, samples

#2337 test(spanner): fix backup tests
  spanner/spanner_snippets/spanner/integration_test.go
  spanner/spanner_snippets/spanner/spanner_list_backup_operations.go
Labels: api: spanner, samples

#2330 samples(compute): add line breaks
  compute/set_usage_export_bucket.go
Labels: api: compute, samples

#2339 samples(storage): delete unspecified sample
  storage/buckets/buckets_test.go
  storage/buckets/set_public_access_prevention_unspecified.go
Labels: api: storage, samples

#2348 testing(spanner): skip broken spanner backup test
  spanner/spanner_snippets/spanner/integration_test.go
Labels: samples

#2336 chore: auto-assign issues to new Spanner owner
  .github/blunderbuss.yml
Labels: api: spanner, samples

#2350 testing: skip impacted GCS tests
  speech/caption/caption_test.go
  speech/captionasync/captionasync_test.go
  speech/wordoffset/wordoffset_test.go
  videointelligence/annotate/text_detection_gcs_test.go
  videointelligence/video_analyze/video_analyze_test.go
  vision/detect/detect_test.go
Labels: samples

#2331 docs(bigquery): add samples for materialized views
  bigquery/snippets/table/bigquery_create_materialized_view.go
  bigquery/snippets/table/bigquery_delete_materialized_view.go
  bigquery/snippets/table/bigquery_update_materialized_view.go
  bigquery/snippets/table/integration_test.go
  eventarc/testing/go.sum
  go.mod
  go.sum
  monitoring/go.sum
  opencensus/go.sum
  run/testing/go.sum
  spanner/go.sum
Labels: api: bigquery, samples

#2354 docs(bigquery): add routines samples
  bigquery/snippets/routine/bigquery_create_routine.go
  bigquery/snippets/routine/bigquery_create_routine_ddl.go
  bigquery/snippets/routine/bigquery_delete_routine.go
  bigquery/snippets/routine/bigquery_get_routine..go
  bigquery/snippets/routine/bigquery_list_routines.go
  bigquery/snippets/routine/bigquery_update_routine.go
  bigquery/snippets/routine/integration_test.go
Labels: api: bigquery, samples

#2235 feat: Adding cloud run jobs sample
  run/jobs/go.mod
  run/jobs/go.sum
  run/jobs/main.go
  run/jobs/main_test.go
Labels: cla: yes, samples

#2340 chore(functions/helloworld): update go.mod to 1.16
  functions/helloworld/go.mod
  functions/helloworld/go.sum
Labels: api: cloudfunctions, samples
