Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2021-06, with the labels that each got.

#2093 opentelemetry: export traces in batch rather than synchronously
  opentelemetry/trace/main.go
Labels: cla: yes, samples

#2095 fix(opentelemetry): use the right flush method
  opentelemetry/trace/main.go
Labels: cla: yes, samples

#2094 feat(spanner): update samples for optimizer statistics package
  eventarc/testing/go.sum
  go.mod
  go.sum
  monitoring/go.mod
  monitoring/go.sum
  run/testing/go.mod
  run/testing/go.sum
  spanner/spanner_snippets/spanner/spanner_create_client_with_query_options.go
  spanner/spanner_snippets/spanner/spanner_query_with_query_options.go
Labels: api: spanner, cla: yes, samples

#2090 docs: remove dual-homed region tags
  firestore/firestore_quickstart/main.go
  firestore/firestore_snippets/collection_group_query.go
  firestore/firestore_snippets/collection_group_setup.go
  firestore/firestore_snippets/increment.go
  firestore/firestore_snippets/main.go
  firestore/firestore_snippets/query.go
  firestore/firestore_snippets/retrieve.go
  firestore/firestore_snippets/save.go
  firestore/firestore_snippets/solution_counters.go
Labels: automerge, cla: yes, samples

#2091 chore: Update CODEOWNERS and Blunderbuss for SoDa
  .github/CODEOWNERS
  .github/blunderbuss.yml
Labels: cla: yes, samples

#2097 chore: update asset lib to v1 for ListAssets sample code
  asset/quickstart/list-assets/main.go
Labels: api: cloudasset, cla: yes, samples

#2098 fix(functions): use golang image for CI/CD example
  functions/ci_cd/cloudbuild.yaml
Labels: api: cloudfunctions, cla: yes, samples

#2100 chore(.github): ignore x/net updates
  .github/renovate.json
Labels: cla: yes, samples

#2104 fix(deps): revert version contrib.go.opencensus.io/exporter/stackdriver
  .github/renovate.json
  eventarc/testing/go.sum
  go.mod
  go.sum
  monitoring/go.mod
  monitoring/go.sum
  opencensus/metrics_quickstart/go.mod
  opencensus/metrics_quickstart/go.sum
  run/testing/go.sum
Labels: automerge, cla: yes, samples

#2102 chore(.github): split build and lint into multiple jobs
  .github/workflows/go.yaml
Labels: cla: yes, samples

#2116 docs: fix connection pool size for samples
  bigtable/connectionpool/configure_connection_pool.go
  bigtable/connectionpool/configure_connection_pool_test.go
Labels: automerge, cla: yes, samples

#2126 chore: update how to install goimports
  .github/workflows/go.yaml
Labels: cla: yes, samples

#2124 chore: update storage dependency
  eventarc/testing/go.sum
  go.mod
  go.sum
  monitoring/go.mod
  monitoring/go.sum
  run/testing/go.sum
Labels: automerge, cla: yes, samples

#2120 chore: update blunderbuss.yml
  .github/blunderbuss.yml
Labels: automerge, cla: yes, samples

#2121 chore: update blunderbuss.yml
  .github/CODEOWNERS
Labels: automerge, cla: yes, samples

#1919 feat(storage): add PublicAccessPrevention samples
  storage/buckets/buckets_test.go
  storage/buckets/get_public_access_prevention.go
  storage/buckets/set_public_access_prevention_enforced.go
  storage/buckets/set_public_access_prevention_unspecified.go
Labels: api: storage, automerge, cla: yes, samples
