Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2022-02, with the labels that each got.

#2400 feat(cloudsql): update sqlserver sample app with Kubernetes Engine yaml files
  cloudsql/sqlserver/database-sql/deployment.yaml
  cloudsql/sqlserver/database-sql/service-account.yaml
  cloudsql/sqlserver/database-sql/service.yaml
Labels: api: cloudsql, samples

#2407 fix(logging): count real streamed entries instead of iterations
  logging/taillogs/taillogs.go
Labels: samples

#2402 fix(opencensus): trace exemplar example to show how to use attachments
  opencensus/go.mod
  opencensus/trace_exemplar.go
  opencensus/trace_exemplar_test.go
Labels: samples

#2421 feature(functions): add HTTP sample for functionsv2
  functions/functionsv2/helloworld/go.mod
  functions/functionsv2/helloworld/go.sum
  functions/functionsv2/helloworld/hello_world.go
  functions/functionsv2/helloworld/hello_world_test.go
Labels: api: cloudfunctions, samples

#2422 fix(functions): revert to non-declarative HTTP signatures
  functions/helloworld/go.mod
  functions/helloworld/go.sum
  functions/helloworld/hello_http.go
  functions/helloworld/hello_http_test.go
Labels: automerge, api: cloudfunctions, samples

#2297 feat(pubsublite): add regional topic samples
  pubsublite/admin/create_topic.go
  pubsublite/admin/delete_topic.go
  pubsublite/admin/get_topic.go
  pubsublite/admin/list_subscriptions_in_project.go
  pubsublite/admin/pubsublite_admin_test.go
  pubsublite/admin/update_topic.go
  pubsublite/go.mod
  pubsublite/go.sum
  pubsublite/internal/psltest/util.go
  pubsublite/publish/publish_test.go
  pubsublite/quickstart_publisher/main_test.go
  pubsublite/quickstart_subscriber/main_test.go
Labels: cla: yes, samples, api: pubsublite

#2426 chore: move infra to min of 1.15
  testing/kokoro/go115.cfg
Labels: samples

#2388 feat: add code samples and tests for jobs with captions
  media/transcoder/README.md
  media/transcoder/create_job_with_embedded_captions.go
  media/transcoder/create_job_with_standalone_captions.go
  media/transcoder/transcoder_test.go
Labels: samples

#2428 style(transcoder): omit extraneous types in sample
  media/transcoder/create_job_with_concatenated_inputs.go
Labels: samples, api: transcoder

#2429 fix(healthcare api): add if/else clause for DICOMweb search studies
  healthcare/dicomweb_study_search.go
Labels: samples

#2431 chore: update protobuf dependency for kms
  kms/create_key_rotation_schedule.go
  kms/go.mod
  kms/update_key_add_rotation.go
Labels: api: cloudkms, samples

#2401 docs(iam-samples): extract PrivateKeyData from ServiceAccountkey
  iam/snippets/service_account_keys_create.go
Labels: samples

#2439 feat(pubsub): add create subscription with filtering sample
  pubsub/subscriptions/create_filter.go
  pubsub/subscriptions/subscription_test.go
Labels: api: pubsub, samples

#2396 feat(samples): add compute custom hostname samples
  compute/custom-hostname-instance/create_instance_with_custom_hostname.go
  compute/custom-hostname-instance/get_instance_hostname.go
  compute/custom-hostname-instance/instance_hostname_test.go
Labels: samples

#2448 samples(compute): update LRO support
  compute/compute_test.go
  compute/custom-hostname-instance/create_instance_with_custom_hostname.go
  compute/custom-hostname-instance/instance_hostname_test.go
  compute/wait_for_operation.go
Labels: api: compute, samples

#2450 chore(cloudsql/sqlserver): update sqlserver sample package versions.
  cloudsql/sqlserver/database-sql/go.mod
  cloudsql/sqlserver/database-sql/go.sum
Labels: api: cloudsql, samples

#2451 feat(pubsublite): add reservations samples
  pubsublite/admin/create_reservation.go
  pubsublite/admin/delete_reservation.go
  pubsublite/admin/get_reservation.go
  pubsublite/admin/list_reservations.go
  pubsublite/admin/pubsublite_admin_test.go
  pubsublite/admin/update_reservation.go
  pubsublite/internal/psltest/util.go
Labels: samples, api: pubsublite
