Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2022-06, with the labels that each got.

#2574 feat(compute): add samples for suspend/resume
  compute/instances/suspend-resume/resume.go
  compute/instances/suspend-resume/suspend.go
  compute/instances/suspend-resume/suspend_resume_test.go
Labels: api: compute, samples

#2596 chore: upgrade talent
  jobs/go.mod
  jobs/go.sum
Labels: samples

#2600 chore: try to get renovate working
  .github/renovate.json
Labels: samples

#2598 fix(gcfv2/imagemagick): Catch storage Close() errors, and include zombie image.
  badfiles_test.go
  functions/functionsv2/imagemagick/imagemagick.go
  functions/functionsv2/imagemagick/zombie.jpg
Labels: samples

#2602 chore(cloudsql): remove SSL details from default TCP tag
  cloudsql/mysql/database-sql/connect_tcp.go
Labels: api: cloudsql, samples

#2590 docs: align channel config with best practices
  media/livestream/create_channel.go
  media/livestream/create_channel_with_backup_input.go
Labels: samples

#2592 chore: add ability to source general secrets from secret manager
  testing/kokoro/common.cfg
  testing/kokoro/populate-secrets.sh
  testing/kokoro/trampoline.sh
Labels: samples

#2601 feat(gcfv2): Use declarative syntax for label_gce_instance sample
  functions/functionsv2/label_gce_instance/go.mod
  functions/functionsv2/label_gce_instance/go.sum
  functions/functionsv2/label_gce_instance/label_gce_instance.go
  functions/functionsv2/label_gce_instance/label_gce_instance_test.go
Labels: samples

#2604 docs: add Google Cloud Samples browser link to readme template
  README.md
Labels: samples

#2595 fix(firestore): Fix documented error code returned by `DocumentSnapshotIterator.Next()`
  firestore/listen_errors.go
Labels: api: firestore, samples

#2614 test(monitoring): add retries
  monitoring/snippets/channel_enable_test.go
Labels: api: monitoring, samples

#2617 storage: increase bucket create timeout
  storage/buckets/create_bucket.go
  storage/buckets/create_bucket_class_location.go
  storage/buckets/create_bucket_dual_region.go
  storage/buckets/create_bucket_turbo_replication.go
Labels: api: storage, samples

#2619 fix(run/sigterm): use query string for terminate
  run/testing/sigterm_handler.e2e_test.go
Labels: api: run, samples
