Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2023-01, with the labels that each got.

#2797 chore(functions/http): Update 'request body' sample to use gen2 sig
  functions/http/http_content_type.go
Labels: automerge, api: cloudfunctions, samples

#2802 feat(storagetransfer): add azure sample
  storagetransfer/go.mod
  storagetransfer/go.sum
  storagetransfer/storagetransfer_test.go
  storagetransfer/transfer_from_azure.go
  testing/kokoro/system_tests.sh
Labels: api: storagetransfer, samples

#2779 feat(kms): Add docs samples for KMS key import.
  kms/check_state_import_job.go
  kms/check_state_imported_key.go
  kms/create_import_job.go
  kms/create_key_for_import.go
  kms/go.mod
  kms/go.sum
  kms/import_manually_wrapped_key.go
  kms/kms_test.go
Labels: automerge, api: cloudkms, samples

#2579 feat(spanner): add samples for database roles
  spanner/go.mod
  spanner/go.sum
  spanner/spanner_snippets/snippet.go
  spanner/spanner_snippets/spanner/integration_test.go
  spanner/spanner_snippets/spanner/spanner_add_and_drop_database_role.go
  spanner/spanner_snippets/spanner/spanner_enable_fine_grained_access.go
  spanner/spanner_snippets/spanner/spanner_list_database_roles.go
  spanner/spanner_snippets/spanner/spanner_read_data_with_database_role.go
Labels: api: spanner, samples

#2793 chore(functions/file_system): Update file_system sample to use gen2 signature
  functions/tips/file_system.go
  functions/tips/go.mod
  functions/tips/go.sum
Labels: api: cloudfunctions, samples

#2807 fix(testing): Work around kokoro image changes
  testing/kokoro/trampoline.sh
Labels: samples

#2813 docs(storage): fix precondition comments
  storage/objects/change_file_storage_class.go
  storage/objects/change_object_csek_to_cmek.go
  storage/objects/copy_file.go
  storage/objects/copy_file_archived_generation.go
  storage/objects/delete_file.go
  storage/objects/move_file.go
  storage/objects/release_event_based_hold.go
  storage/objects/release_temporary_hold.go
  storage/objects/rotate_encryption_key.go
  storage/objects/set_event_based_hold.go
  storage/objects/set_metadata.go
  storage/objects/set_temporary_hold.go
Labels: api: storage, samples

#2794 chore(functions/v2): migrate CORS sample to gen2
  functions/http/cors.go
Labels: api: cloudfunctions, samples

#2814 fix(testing): fix test xml output, disable currently-failing tests for investigation
  asset/quickstart/create-saved-query/main_test.go
  asset/quickstart/delete-saved-query/main_test.go
  asset/quickstart/export-assets/main_test.go
  asset/quickstart/get-saved-query/main_test.go
  asset/quickstart/list-saved-queries/main_test.go
  asset/quickstart/update-saved-query/main_test.go
  batch/create_with_gcs_bucket_test.go
  batch/create_with_template_test.go
  batch/job_basics_test.go
  bigquery/snippets/datatransfer/integration_test.go
  iam/deny/deny_policy_test.go
  storagetransfer/storagetransfer_test.go
  testing/kokoro/system_tests.sh
  translate/v3/translate_text_test.go
Labels: samples

#2816 chore(functions/http): Update xml sample to use gen2 signature
  functions/http/xml.go
Labels: api: cloudfunctions, samples

#2801 feat(compute): Regional disk samples
  compute/disks/attach_regional_disk.go
  compute/disks/attach_regional_disk_readonly.go
  compute/disks/disks_test.go
  compute/disks/resize_regional_disk.go
Labels: api: compute, samples

#2819 chore(functions/security): use go 1.18, not 1.13
  functions/security/go.mod
  functions/security/security_system_test.go
Labels: api: cloudfunctions, samples

#2805 chore(storage): clarify endpoint sample
  storage/service_account/client_endpoint/client_endpoint_test.go
  storage/service_account/client_endpoint/set_client_endpoint.go
Labels: automerge, api: storage, samples

#2821 chore(functions/http/request): Update sample to use declarative signature
  functions/http/request.go
Labels: api: cloudfunctions, samples

#2831 chore(functions/tips/lazy): Update sample to use declarative signature
  functions/tips/lazy.go
Labels: automerge, api: cloudfunctions, samples

#2820 chore(functions/contexttip): Make functions_tips_gcp_apis sample use declarative functions signature
  functions/tips/contexttip/context_tip.go
  functions/tips/contexttip/go.mod
  functions/tips/contexttip/go.sum
Labels: api: cloudfunctions, samples

#2824 chore(functions/tips/scope): Update sample to use declarative signature
  functions/tips/scope.go
Labels: api: cloudfunctions, samples

#2823 chore(functions/tips/timeout): Update sample to use declarative signature
  functions/tips/timeout.go
Labels: api: cloudfunctions, samples

#2822 chore(functions/tips/error): Update http error sample to use declarative signature
  functions/tips/error.go
Labels: api: cloudfunctions, samples
