Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2023-12, with the labels that each got.

#3590 feat(otel): use Cloud Logging structured log conventions
  opentelemetry/instrumentation/app/logger.go
  opentelemetry/instrumentation/app/main_test.go
  opentelemetry/instrumentation/app/setup.go
  opentelemetry/instrumentation/docker-compose.yaml
  opentelemetry/instrumentation/otel-collector-config.yaml
Labels: samples

#3585 chore: Update App Engine samples to the go121 runtime
  appengine/go.mod
  appengine/go.sum
  appengine/go11x/cloudsql/app.yaml
  appengine/go11x/cloudsql/go.mod
  appengine/go11x/helloworld/app.yaml
  appengine/go11x/helloworld/go.mod
  appengine/go11x/pubsub/authenicated_push/app.yaml
  appengine/go11x/tasks/handle_task/app.yaml
  appengine/go11x/tasks/handle_task/go.mod
  appengine/go11x/warmup/app.yaml
  appengine/go11x/warmup/go.mod
  appengine/go11x/warmup/go.sum
Labels: samples

#3611 feat(vertexai): add a Getting Started and Chat sample for gemini
  vertexai/chat/chat.go
  vertexai/chat/chat_test.go
  vertexai/chat/go.mod
  vertexai/chat/go.sum
  vertexai/snippets/go.mod
  vertexai/snippets/go.sum
  vertexai/snippets/try_gemini.go
  vertexai/snippets/try_gemini_test.go
Labels: samples

#3610 feat(vertexai): top level folder with initial Gemini samples
  vertexai/multimodal-multiple/go.mod
  vertexai/multimodal-multiple/go.sum
  vertexai/multimodal-multiple/multiple-multimodal.go
  vertexai/multimodal-multiple/multiple-multimodal_test.go
  vertexai/multimodal/go.mod
  vertexai/multimodal/go.sum
  vertexai/multimodal/multimodal.go
  vertexai/multimodal/multimodal_test.go
  vertexai/safety-settings-multimodal/go.mod
  vertexai/safety-settings-multimodal/go.sum
  vertexai/safety-settings-multimodal/safety-settings-multimodal.go
  vertexai/safety-settings-multimodal/safety-settings-multimodal_test.go
  vertexai/safety-settings/go.mod
  vertexai/safety-settings/go.sum
  vertexai/safety-settings/safety-settings.go
  vertexai/safety-settings/safety-settings_test.go
Labels: samples

#3615 fix(vertexai): use gs:// in safety-settings-multimodal
  vertexai/safety-settings-multimodal/safety-settings-multimodal.go
  vertexai/safety-settings-multimodal/safety-settings-multimodal_test.go
Labels: samples

#3595 testing(bigquery): deeper error introspection
  bigquery/bigquery_migration_quickstart/main_test.go
Labels: automerge, api: bigquery, samples

#3617 feat(profiler): add ListProfiles API sample
  profiler/export_profiles/main.go
  profiler/go.mod
  profiler/go.sum
Labels: api: cloudprofiler, samples

#3711 refactor(profiler): update package name and profile format
  profiler/export/main.go
Labels: api: cloudprofiler, samples

#3708 chore(opentelemetry): fix typo of "hander" -> "handler"
  opentelemetry/instrumentation/app/logger.go
  opentelemetry/instrumentation/app/setup.go
Labels: samples
