Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2023-11, with the labels that each got.

#3452 feat(trace): small updates to OTel sample so it works in Cloud Shell
  opentelemetry/instrumentation/docker-compose.adc.yaml
  opentelemetry/instrumentation/docker-compose.yaml
  opentelemetry/instrumentation/otel-collector-config.yaml
Labels: api: cloudtrace, samples

#3307 feat(cloudrunci): Service.Do() method, to support automatic retries in more tests
  internal/cloudrunci/cloudrunci.go
  run/testing/logging_manual.e2e_test.go
  run/testing/markdown_preview_editor.e2e_test.go
  run/testing/markdown_preview_renderer.e2e_test.go
  run/testing/sigterm_handler.e2e_test.go
Labels: type: cleanup, samples

#3546 Revert "fix(functions): new region tag for 1st gen functions sample "
  functions/helloworld/hello_world.go
Labels: api: cloudfunctions, samples

#3344 fix(dlp): Separated a tests files of samples for `inspect` package (PR-2 for inspect)
  dlp/snippets/inspect/inspect_hotword_rule_test.go
  dlp/snippets/inspect/inspect_image_all_infotypes_test.go
  dlp/snippets/inspect/inspect_image_file_test.go
  dlp/snippets/inspect/inspect_image_listed_infotypes_test.go
  dlp/snippets/inspect/inspect_phone_number_test.go
  dlp/snippets/inspect/inspect_send_data_to_hybrid_job_trigger_test.go
  dlp/snippets/inspect/inspect_string_custom_hotword_test.go
  dlp/snippets/inspect/inspect_string_custom_omit_overlap_test.go
  dlp/snippets/inspect/inspect_string_excluding_substring_test.go
  dlp/snippets/inspect/inspect_string_multiple_rules_test.go
  dlp/snippets/inspect/inspect_test.go
Labels: api: dlp, samples

#3552 chore(storage): bump storage dependency
  storage/go.mod
  storage/go.sum
Labels: api: storage, samples

#3446 feat(storage): support autoclass v2.1 samples
  storage/buckets/buckets_test.go
  storage/buckets/get_autoclass.go
  storage/buckets/set_autoclass.go
Labels: api: storage, samples

#3454 feat: add route tags in opentelemetry client sample
  opentelemetry/instrumentation/app/client.go
Labels: automerge, samples

#3555 feat(renovate): Enable dependency dashboard for golang-samples
  .github/renovate.json
Labels: samples

#3563 feat: Update supported go versions to match cloud SDK
  discoveryengine/search_test.go
  testing/kokoro/earliest-version.cfg
  testing/kokoro/latest-version.cfg
  testing/kokoro/system_tests.sh
Labels: samples

#3559 testing(run): migrate ioutil to io functions
  run/testing/h2c.e2e_test.go
  run/testing/helloworld.e2e_test.go
  run/testing/markdown_preview_editor.e2e_test.go
  run/testing/markdown_preview_renderer.e2e_test.go
Labels: api: run, samples

#3573 testing(bigquery): double test timeout for migration quickstart
  bigquery/bigquery_migration_quickstart/main_test.go
Labels: api: bigquery, samples

#3547 feat(spanner): add samples for BatchWrite
  spanner/go.mod
  spanner/go.sum
  spanner/spanner_snippets/spanner/integration_test.go
  spanner/spanner_snippets/spanner/spanner_batch_write.go
Labels: automerge, api: spanner, samples

#3572 chore(otel): update to a released version of autoexport
  opentelemetry/instrumentation/app/go.mod
  opentelemetry/instrumentation/app/go.sum
Labels: samples

#3450 feat: add sample and test for getting an access token from an imperso…
  auth/access_token_from_impersonated_credentials.go
  auth/auth_test.go
Labels: samples

#3576 fix: kokoro jobs for system tests should bypass the diff check
  testing/kokoro/system_tests.sh
Labels: samples

#3583 docs(bigquery): add more output to migration quickstart
  bigquery/bigquery_migration_quickstart/main.go
Labels: api: bigquery, samples

#3586 testing(bigquery): relax migration testing
  bigquery/bigquery_migration_quickstart/main.go
  bigquery/bigquery_migration_quickstart/main_test.go
Labels: api: bigquery, samples

#3577 feat(docs): major revision to the contributing docs.
  CONTRIBUTING.md
Labels: samples
