Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2023-02, with the labels that each got.

#2803 feat(compute): resize instance sample
  compute/change_machine_type.go
  compute/compute_test.go
Labels: api: compute, samples

#2850 fix(batch): Fix comments in batch/read_job_logs.go
  batch/read_job_logs.go
Labels: samples, api: batch

#2849 chore(functions/http): migrate HTTP Auth CORS and HTTP parse multipart samples to functions framework gen2
  functions/http/cors_auth.go
  functions/http/form.go
Labels: api: cloudfunctions, samples

#2853 chore(profile): Upgrade pprof library
  profiler/go.mod
  profiler/go.sum
Labels: samples

#2861 chore: remove explicit mod=vendor
  internal/cloudrunci/testingapp/Dockerfile
Labels: samples

#2854 docs: add comment about SystemCertPool() on windows
  run/grpc-ping/connection.go
Labels: samples

#2862 docs: add comments to explain environment variables
  cloudsql/mysql/database-sql/cloudsql.go
  cloudsql/mysql/database-sql/connect_connector.go
  cloudsql/mysql/database-sql/connect_connector_iam_authn.go
  cloudsql/mysql/database-sql/connect_tcp.go
  cloudsql/mysql/database-sql/connect_unix.go
  cloudsql/mysql/database-sql/deployment.yaml
  cloudsql/postgres/database-sql/cloudsql.go
  cloudsql/postgres/database-sql/connect_connector.go
  cloudsql/postgres/database-sql/connect_connector_iam_authn.go
  cloudsql/postgres/database-sql/connect_tcp.go
  cloudsql/postgres/database-sql/connect_unix.go
  cloudsql/postgres/database-sql/deployment.yaml
  cloudsql/sqlserver/database-sql/connect_connector.go
  cloudsql/sqlserver/database-sql/connect_tcp.go
Labels: samples

#2868 feat(appengine): Add preview helloworld sample
  appengine_flexible/preview/helloworld/app.yaml
  appengine_flexible/preview/helloworld/go.mod
  appengine_flexible/preview/helloworld/helloworld.go
Labels: samples

#2734 fix(storagetransfer): use UTC for Schedule
  storagetransfer/transfer_from_aws.go
  storagetransfer/transfer_to_nearline.go
Labels: api: storagetransfer, samples

#2874 fix(translate): improve test for get languages
  translate/v3/get_supported_languages_test.go
Labels: api: translate, samples

#2876 fix(documentai): changed DocAI package name
  documentai/documentai_quickstart/main.go
  documentai/documentai_quickstart/main_test.go
  documentai/go.mod
  documentai/go.sum
Labels: api: documentai, samples

#2880 docs(storagetransfer): move quickstart to its own directory
  storagetransfer/storagetransfer_quickstart/main.go
Labels: api: storagetransfer, samples

#2879 fix: prevent chmod errors that are filling up test logs
  testing/kokoro/trampoline.sh
Labels: samples
