Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2023-05, with the labels that each got.

#2998 feat(dlp): added a sample for deidentify table conditions
  dlp/snippets/deid/deid_table_condition_infotypes.go
  dlp/snippets/deid/deid_test.go
Labels: api: dlp, samples

#2997 feat(dlp): added a sample for de-identify replace
  dlp/snippets/deid/deid_replace.go
  dlp/snippets/deid/deid_test.go
Labels: api: dlp, samples

#3006 fix(testing): stop running all tests on insignificant changes
  testing/kokoro/system_tests.sh
Labels: samples

#2980 feat(kms): public key conversion to JWK format.
  go.mod
  go.sum
  kms/get_public_key_jwk.go
  kms/go.mod
  kms/go.sum
  kms/kms_test.go
  run/testing/go.mod
  run/testing/go.sum
Labels: api: cloudkms, samples

#3020 chore(cloudsql): update Cloud Function samples to gen2
  cloudsql/mysql/database-sql/README.md
  cloudsql/mysql/database-sql/cmd/functions/functions.go
  cloudsql/mysql/database-sql/go.mod
  cloudsql/mysql/database-sql/go.sum
  cloudsql/postgres/database-sql/README.md
  cloudsql/postgres/database-sql/cmd/app/functions/functions.go
  cloudsql/postgres/database-sql/go.mod
  cloudsql/postgres/database-sql/go.sum
  cloudsql/sqlserver/database-sql/README.md
  cloudsql/sqlserver/database-sql/cmd/functions/functions.go
  cloudsql/sqlserver/database-sql/go.mod
  cloudsql/sqlserver/database-sql/go.sum
Labels: api: cloudsql, samples

#3000 feat(dlp): added a sample for deidentify table condition masking
  dlp/snippets/deid/deid_table_condition_masking.go
  dlp/snippets/deid/deid_test.go
Labels: api: dlp, samples

#3019 chore(appengine): move region tags to include the full function
  docs/appengine/capabilities/capability.go
Labels: automerge, api: appengine, samples

#3022 fix(videointelligence): use retryable Error method
  videointelligence/video_analyze/video_analyze_test.go
Labels: api: videointelligence, samples

#3001 feat(dlp): added a sample for deidentify table infotypes
  dlp/snippets/deid/deid_table_infotypes.go
  dlp/snippets/deid/deid_test.go
  dlp/snippets/inspect/inspect_string_excluding_substring.go
Labels: api: dlp, samples

#3023 chore: update ownership for asset team
  .github/CODEOWNERS
  .github/blunderbuss.yml
Labels: samples

#3027 fix(appengine): fix missing context initiatilization in capability.go
  docs/appengine/capabilities/capability.go
Labels: samples

#3024 fix(kms): updates region tag
  kms/get_public_key_jwk.go
Labels: api: cloudkms, samples

#3010 feat(dlp): added a sample for deidentify table row supress
  dlp/snippets/deid/deid_table_row_supress.go
  dlp/snippets/deid/deid_test.go
Labels: api: dlp, samples

#3011 feat(dlp): added a sample for inspect string with multiple rules
  dlp/snippets/inspect/inspect_string_multiple_rules.go
  dlp/snippets/inspect/inspect_test.go
Labels: api: dlp, samples

#3037 chore(fixit): Go Error Visibility for dlp
  dlp/snippets/deid/date_shift.go
  dlp/snippets/deid/deid_fpe.go
  dlp/snippets/deid/deid_with_exception_list.go
  dlp/snippets/deid/deid_with_redact.go
  dlp/snippets/deid/mask.go
  dlp/snippets/deid/reid_fpe.go
  dlp/snippets/inspect/inspect_bigquery.go
  dlp/snippets/inspect/inspect_datastore.go
  dlp/snippets/inspect/inspect_gcs.go
  dlp/snippets/inspect/inspect_text_file.go
  dlp/snippets/jobs/delete.go
  dlp/snippets/jobs/jobs_test.go
  dlp/snippets/jobs/list.go
  dlp/snippets/metadata/info_types.go
  dlp/snippets/redact/redact.go
  dlp/snippets/risk/categorical.go
  dlp/snippets/risk/k_anonymity.go
  dlp/snippets/risk/k_map.go
  dlp/snippets/risk/l_diversity.go
  dlp/snippets/risk/numerical.go
  dlp/snippets/risk/risk.go
  dlp/snippets/template/create.go
  dlp/snippets/template/delete.go
  dlp/snippets/template/list.go
  dlp/snippets/trigger/create.go
  dlp/snippets/trigger/delete.go
  dlp/snippets/trigger/list.go
Labels: samples

#3012 feat(dlp): added a sample for inspect string custom excluding substring
  dlp/snippets/deid/deid_test.go
  dlp/snippets/inspect/inspect_test.go
Labels: api: dlp, samples

#3032 chore(fixit): Go Error Visibility for kms
  kms/check_state_import_job.go
  kms/check_state_imported_key.go
  kms/create_import_job.go
  kms/create_key_asymmetric_decrypt.go
  kms/create_key_asymmetric_sign.go
  kms/create_key_for_import.go
  kms/create_key_hsm.go
  kms/create_key_labels.go
  kms/create_key_mac.go
  kms/create_key_ring.go
  kms/create_key_rotation_schedule.go
  kms/create_key_symmetric_encrypt_decrypt.go
  kms/create_key_version.go
  kms/decrypt_asymmetric.go
  kms/decrypt_symmetric.go
  kms/destroy_key_version.go
  kms/disable_key_version.go
  kms/enable_key_version.go
  kms/encrypt_asymmetric.go
  kms/encrypt_symmetric.go
  kms/generate_random_bytes.go
  kms/get_key_labels.go
  kms/get_key_version_attestation.go
  kms/get_public_key.go
  kms/iam_add_member.go
  kms/iam_get_policy.go
  kms/iam_remove_member.go
  kms/import_manually_wrapped_key.go
  kms/kms_helpers_test.go
  kms/restore_key_version.go
  kms/sign_asymmetric.go
  kms/sign_mac.go
  kms/update_key_add_rotation.go
  kms/update_key_remove_labels.go
  kms/update_key_remove_rotation.go
  kms/update_key_set_primary.go
  kms/update_key_update_labels.go
  kms/verify_asymmetric_ec.go
  kms/verify_asymmetric_rsa.go
  kms/verify_mac.go
Labels: samples

#3033 chore(fixit): Go Error Visibility for iam
  iam/deny/create_deny_policy.go
  iam/deny/delete_deny_policy.go
  iam/deny/get_deny_policy.go
  iam/deny/list_deny_policies.go
  iam/deny/update_deny_policy.go
  iam/snippets/permissions_query_testable.go
  iam/snippets/roles_create.go
  iam/snippets/roles_delete.go
  iam/snippets/roles_edit.go
  iam/snippets/roles_get.go
  iam/snippets/roles_list.go
  iam/snippets/roles_undelete.go
  iam/snippets/roles_view_grantable.go
  iam/snippets/service_account_keys_create.go
  iam/snippets/service_account_keys_delete.go
  iam/snippets/service_account_keys_list.go
  iam/snippets/service_accounts_create.go
  iam/snippets/service_accounts_delete.go
  iam/snippets/service_accounts_disable.go
  iam/snippets/service_accounts_enable.go
  iam/snippets/service_accounts_list.go
  iam/snippets/service_accounts_rename.go
Labels: samples

#3034 chore(fixit): Go Error Visibility for functions
  functions/console_snippets/firebase_auth/firebase_auth.go
  functions/console_snippets/firebase_rtdb/firebase_rtdb.go
  functions/console_snippets/firestore/firestore.go
  functions/console_snippets/google_analytics/google_analytics.go
  functions/firebase/hello/firestore.go
  functions/firebase/upper/upper.go
  functions/functionsv2/hellopubsub/hello_pubsub.go
  functions/functionsv2/imagemagick/imagemagick.go
  functions/functionsv2/log/process_log_entry.go
  functions/functionsv2/ocr/app/detect.go
  functions/functionsv2/ocr/app/process.go
  functions/functionsv2/ocr/app/save.go
  functions/functionsv2/ocr/app/setup.go
  functions/functionsv2/ocr/app/translate.go
  functions/functionsv2/slack/format.go
  functions/functionsv2/slack/search.go
  functions/functionsv2/tips/infinite_retries/infinite_retries.go
  functions/functionsv2/tips/retry.go
  functions/helloworld/hello_cloud_storage.go
  functions/imagemagick/imagemagick.go
  functions/memorystore/redis/visitcount.go
  functions/ocr/app/detect.go
  functions/ocr/app/process.go
  functions/ocr/app/save.go
  functions/ocr/app/setup.go
  functions/ocr/app/translate.go
  functions/security/idtoken.go
  functions/slack/search.go
  functions/tips/infinite_retries/infinite_retries.go
Labels: samples

#3046 chore(fixit): Errors update for Cloud Run system-package
  run/system_package/graphviz.go
Labels: samples

#3042 chore(fixit): Go Error Visibility for getting-started/bookshelf
  getting-started/bookshelf/bookshelf.go
  getting-started/bookshelf/db_firestore.go
  getting-started/bookshelf/main.go
  getting-started/bookshelf/template.go
Labels: samples

#3050 fix(videointelligence): skip failing tests.
  videointelligence/video_analyze/video_analyze_test.go
Labels: api: videointelligence, samples

#3013 feat(dlp): added a sample for inspect string with exclusion regex
  dlp/snippets/inspect/inspect_string_with_exclusion_regex.go
  dlp/snippets/inspect/inspect_test.go
Labels: api: dlp, samples

#3014 feat(dlp): added a sample for inspect table
  dlp/snippets/inspect/inspect_table.go
  dlp/snippets/inspect/inspect_test.go
Labels: api: dlp, samples

#3035 chore(fixit): Go Error Visibility for batch
  batch/create_with_container_no_mounting.go
  batch/create_with_gcs_bucket.go
  batch/create_with_gcs_bucket_test.go
  batch/create_with_script_no_mounting.go
  batch/create_with_template.go
  batch/create_with_template_test.go
  batch/delete_job.go
  batch/get_job.go
  batch/get_task.go
  batch/list_jobs.go
  batch/list_tasks.go
  batch/read_job_logs.go
  batch/testutils.go
Labels: samples

#3040 chore(fixit): Go Error Visibility for tasks/token
  tasks/token/create_http_task_with_token.go
Labels: samples

#3041 chore(fixit): Go Error Visibility for Cloud Tasks
  tasks/create_http_task.go
Labels: samples

#3043 chore(fixit): Errors update for Cloud Run grpc-ping
  run/grpc-ping/request_auth.go
  run/testing/grpc_ping.e2e_test.go
Labels: samples

#3045 chore(fixit): Errors update for Cloud Run image-processing
  run/image-processing/imagemagick/imagemagick.go
Labels: samples

#3061 chore(fixit): Errors update for Cloud SQL Postgres
  cloudsql/postgres/database-sql/cloudsql.go
  cloudsql/postgres/database-sql/connect_connector.go
  cloudsql/postgres/database-sql/connect_connector_iam_authn.go
  cloudsql/postgres/database-sql/connect_tcp.go
  cloudsql/postgres/database-sql/connect_unix.go
Labels: samples

#3063 chore(fixit): Go Error Visibility for bigtables/writes
  bigtable/writes/write_batch.go
  bigtable/writes/write_conditionally.go
  bigtable/writes/write_increment.go
  bigtable/writes/write_simple.go
Labels: samples

#3058 chore(fixit): Go Error Visibility for asset
  asset/quickstart/create-saved-query/create_saved_query.go
  asset/quickstart/delete-saved-query/delete_saved_query.go
  asset/quickstart/get-saved-query/get_saved_query.go
  asset/quickstart/list-saved-queries/list_saved_queries.go
  asset/quickstart/update-saved-query/update_saved_query.go
Labels: samples

#3054 chore(fixit): Error visibility for getting-started/gopher-run/leaderboard
  getting-started/gopher-run/leaderboard/leaderboard.go
Labels: samples

#3069 chore(fixit): Go Error Visibility for translate/v3
  translate/v3/batch_translate_text.go
  translate/v3/batch_translate_text_with_glossary.go
  translate/v3/batch_translate_text_with_glossary_and_model.go
  translate/v3/batch_translate_text_with_model.go
  translate/v3/create_glossary.go
  translate/v3/delete_glossary.go
  translate/v3/detect_language.go
  translate/v3/get_glossary.go
  translate/v3/get_supported_languages.go
  translate/v3/get_supported_languages_for_target.go
  translate/v3/list_glossaries.go
  translate/v3/translate_text.go
  translate/v3/translate_text_with_glossary.go
  translate/v3/translate_text_with_glossary_and_model.go
  translate/v3/translate_text_with_model.go
Labels: samples

#3057 chore(fixit): Go Error Visibility for spanner
  spanner/spanner_snippets/snippet.go
  spanner/spanner_snippets/spanner/integration_test.go
  spanner/spanner_snippets/spanner/pg_spanner_create_storing_index.go
  spanner/spanner_snippets/spanner/pg_spanner_dml_getting_started_update.go
  spanner/spanner_snippets/spanner/spanner_cancel_backup_create.go
  spanner/spanner_snippets/spanner/spanner_commit_stats.go
  spanner/spanner_snippets/spanner/spanner_copy_backup.go
  spanner/spanner_snippets/spanner/spanner_create_backup.go
  spanner/spanner_snippets/spanner/spanner_create_backup_with_encryption_key.go
  spanner/spanner_snippets/spanner/spanner_create_database_with_default_leader.go
  spanner/spanner_snippets/spanner/spanner_create_database_with_encryption_key.go
  spanner/spanner_snippets/spanner/spanner_create_database_with_retention_period.go
  spanner/spanner_snippets/spanner/spanner_create_instance.go
  spanner/spanner_snippets/spanner/spanner_create_instance_config.go
  spanner/spanner_snippets/spanner/spanner_create_instance_with_processing_units.go
  spanner/spanner_snippets/spanner/spanner_create_table_with_datatypes.go
  spanner/spanner_snippets/spanner/spanner_get_instance_config.go
  spanner/spanner_snippets/spanner/spanner_restore_backup_with_encryption_key.go
  spanner/spanner_snippets/spanner/spanner_update_instance_config.go
Labels: samples

#3071 chore(fixit): Go Error Visibility for translate
  translate/detect.go
  translate/list.go
  translate/model.go
  translate/text.go
Labels: samples

#3059 chore(fixit): Go Error Visibility for automl
  automl/batch_predict.go
  automl/dataset_delete.go
  automl/dataset_export.go
  automl/dataset_get.go
  automl/dataset_import_data.go
  automl/dataset_list.go
  automl/language/entity_extraction/dataset_create.go
  automl/language/entity_extraction/model_create.go
  automl/language/entity_extraction/predict.go
  automl/language/sentiment_analysis/dataset_create.go
  automl/language/sentiment_analysis/model_create.go
  automl/language/sentiment_analysis/predict.go
  automl/language/text_classification/dataset_create.go
  automl/language/text_classification/model_create.go
  automl/language/text_classification/predict.go
  automl/model_delete.go
  automl/model_deploy.go
  automl/model_evaluation_get.go
  automl/model_evaluation_list.go
  automl/model_export.go
  automl/model_get.go
  automl/model_list.go
  automl/model_undeploy.go
  automl/operation_status_get.go
  automl/operation_status_list.go
  automl/translate/dataset_create.go
  automl/translate/model_create.go
  automl/translate/predict.go
  automl/vision/classification/dataset_create.go
  automl/vision/classification/model_create.go
  automl/vision/classification/model_deploy_with_node_count.go
  automl/vision/classification/predict.go
  automl/vision/object_detection/dataset_create.go
  automl/vision/object_detection/model_create.go
  automl/vision/object_detection/model_deploy_with_node_count.go
  automl/vision/object_detection/predict.go
Labels: samples

#3062 chore(fixit): Go Error Visibility for cloudsql/mysql/database-sql
  cloudsql/mysql/database-sql/cloudsql.go
  cloudsql/mysql/database-sql/connect_connector.go
  cloudsql/mysql/database-sql/connect_connector_iam_authn.go
  cloudsql/mysql/database-sql/connect_tcp.go
  cloudsql/mysql/database-sql/connect_unix.go
Labels: samples

#3073 chore(fixit): Go Error Visibility for vision/detect
  vision/detect/set_endpoint.go
Labels: samples

#3076 chore(fixit): Go Error Visibility for videointelligence/video_analyze
  videointelligence/video_analyze/video_analyze.go
  videointelligence/video_analyze/video_analyze_gcs.go
Labels: samples

#3066 chore(fixit): Go Error Visibility for bigtables/connectionpool
  bigtable/connectionpool/configure_connection_pool.go
Labels: samples

#3064 chore(fixit): Go Error Visibility for bigtables/reads
  bigtable/reads/reads.go
Labels: samples

#3068 feat(fixit): Adding privateca/ca_pool samples
  .github/CODEOWNERS
  .github/blunderbuss.yml
  .gitignore
  privateca/create_ca_pool.go
  privateca/delete_ca_pool.go
  privateca/go.mod
  privateca/go.sum
  privateca/privateca_test.go
Labels: samples

#3067 chore(fixit): error visibility for getting-started
  getting-started/sessions/main.go
Labels: samples

#3070 refactor(firestore): Split firestore/save.go samples to separate file, widen region tags
  firestore/save.go
  firestore/save_data_batch_writes.go
  firestore/save_data_delete_collection.go
  firestore/save_data_delete_doc.go
  firestore/save_data_delete_field.go
  firestore/save_data_set_doc_upsert.go
  firestore/save_data_set_field.go
  firestore/save_data_set_from_custom_type.go
  firestore/save_data_set_from_map.go
  firestore/save_data_set_from_map_nested.go
  firestore/save_data_set_id_random_collection.go
  firestore/save_data_set_id_random_document_ref.go
  firestore/save_data_set_id_specified.go
  firestore/save_data_set_nested_fields.go
  firestore/save_data_set_server_timestamp.go
  firestore/save_transaction_document_update.go
  firestore/save_transaction_document_update_conditional.go
  firestore/save_update_multiple_fields.go
Labels: api: firestore, samples

#3097 chore(fixit): error format update for bigtable/filters
  bigtable/filters/filters.go
Labels: samples

#3060 chore(fixit): Go Error Visibility for cloudsql/sqlserver/database-sql
  cloudsql/sqlserver/database-sql/cloudsql.go
  cloudsql/sqlserver/database-sql/connect_connector.go
  cloudsql/sqlserver/database-sql/connect_tcp.go
Labels: automerge, samples

#3104 chore(fixit): Go Error Visibility for pubsublite/admin
  pubsublite/admin/create_pubsub_export_subscription.go
  pubsublite/admin/create_reservation.go
  pubsublite/admin/create_subscription.go
  pubsublite/admin/create_topic.go
  pubsublite/admin/delete_reservation.go
  pubsublite/admin/delete_subscription.go
  pubsublite/admin/delete_topic.go
  pubsublite/admin/get_reservation.go
  pubsublite/admin/get_subscription.go
  pubsublite/admin/get_topic.go
  pubsublite/admin/list_reservations.go
  pubsublite/admin/list_subscriptions_in_project.go
  pubsublite/admin/list_subscriptions_in_topic.go
  pubsublite/admin/list_topics.go
  pubsublite/admin/seek_subscription.go
  pubsublite/admin/update_reservation.go
  pubsublite/admin/update_subscription.go
  pubsublite/admin/update_topic.go
Labels: samples

#3080 chore(fixit): Go Error Visibility for getting-started/gopher-run/cmd
  getting-started/gopher-run/cmd/main.go
Labels: automerge, samples

#3075 chore(fixit): Go Error Visibility for videointelligence/annotate
  videointelligence/annotate/logo_detection.go
  videointelligence/annotate/logo_detection_gcs.go
  videointelligence/annotate/object_tracking.go
  videointelligence/annotate/object_tracking_gcs.go
  videointelligence/annotate/text_detection.go
  videointelligence/annotate/text_detection_gcs.go
Labels: automerge, samples

#3081 chore(fixit): Go Error Visibility for logging/taillogs
  logging/taillogs/taillogs.go
Labels: automerge, samples

#3078 chore(fixit): Go Error Visibility for datacatalog/datacatalog_quickstart
  datacatalog/datacatalog_quickstart/main_test.go
Labels: automerge, samples

#3082 chore(fixit): Go Error Visibility for iot/mqttsnippets
  iot/mqttsnippets/gateway_send_data_test.go
Labels: automerge, samples

#3074 chore(fixit): Go Error Visibility for vision/product_search
  vision/product_search/add_product_to_product_set.go
  vision/product_search/create_product.go
  vision/product_search/create_product_set.go
  vision/product_search/create_reference_image.go
  vision/product_search/delete_product.go
  vision/product_search/delete_product_set.go
  vision/product_search/delete_reference_image.go
  vision/product_search/get_product.go
  vision/product_search/get_product_set.go
  vision/product_search/get_reference_image.go
  vision/product_search/get_similar_products.go
  vision/product_search/get_similar_products_uri.go
  vision/product_search/import_product_sets.go
  vision/product_search/list_product_sets.go
  vision/product_search/list_products.go
  vision/product_search/list_products_in_product_set.go
  vision/product_search/list_reference_images.go
  vision/product_search/purge_orphan_products.go
  vision/product_search/purge_products_in_product_set.go
  vision/product_search/remove_product_from_product_set.go
  vision/product_search/update_product_labels.go
Labels: automerge, samples

#3077 chore(fixit): Go error visibility for pubsub, speech, tts
  pubsub/topics/add_users.go
  pubsub/topics/create.go
  pubsub/topics/delete.go
  pubsub/topics/list_subs.go
  pubsub/topics/list_topics.go
  pubsub/topics/policy.go
  pubsub/topics/publish.go
  pubsub/topics/publish_custom.go
  pubsub/topics/publish_flow_control.go
  pubsub/topics/publish_scale.go
  pubsub/topics/publish_settings.go
  pubsub/topics/publish_single.go
  pubsub/topics/test_permissions.go
  speech/snippets/auto_punctuation.go
  speech/snippets/context_classes.go
  speech/snippets/enhanced_model.go
  speech/snippets/model_selection.go
  speech/snippets/multichannel.go
  texttospeech/synthesize_speech/audio_profile.go
Labels: automerge, samples

#3084 chore(fixit): Go Error Visibility for servicedirectory
  servicedirectory/create_endpoint.go
  servicedirectory/create_namespace.go
  servicedirectory/create_service.go
  servicedirectory/delete_endpoint.go
  servicedirectory/delete_namespace.go
  servicedirectory/delete_service.go
  servicedirectory/resolve_service.go
Labels: automerge, samples

#3106 chore(fixit): Go Error Visibility for monitoring/uptime
  monitoring/uptime/uptime.go
Labels: samples

#3098 chore(fixit): error format update for bigtable/garbage collection
  bigtable/garbagecollection/create_family_gc_intersect.go
  bigtable/garbagecollection/create_family_gc_max_age.go
  bigtable/garbagecollection/create_family_gc_max_versions.go
  bigtable/garbagecollection/create_family_gc_nested.go
  bigtable/garbagecollection/create_family_gc_union.go
  bigtable/garbagecollection/update_gc_rule.go
Labels: samples

#3087 chore(fixit): Go Error Visibility for testing/gimmeproj
  testing/gimmeproj/main.go
Labels: samples

#3108 chore(fixit): Go Error Visibility for endpoints/getting-started/client
  endpoints/getting-started/client/main.go
Labels: samples

#3088 chore(fixit): Go Error Visibility for iotkit/helloworld/display
  iotkit/helloworld/display/display.go
Labels: samples

#3089 chore(fixit): Go Error Visibility for media/livestream
  media/livestream/create_channel.go
  media/livestream/create_channel_event.go
  media/livestream/create_channel_with_backup_input.go
  media/livestream/create_input.go
  media/livestream/delete_channel.go
  media/livestream/delete_channel_event.go
  media/livestream/delete_input.go
  media/livestream/get_channel.go
  media/livestream/get_channel_event.go
  media/livestream/get_input.go
  media/livestream/list_channel_events.go
  media/livestream/list_channels.go
  media/livestream/list_inputs.go
  media/livestream/start_channel.go
  media/livestream/stop_channel.go
  media/livestream/update_channel.go
  media/livestream/update_input.go
Labels: samples

#3090 chore(fixit): Go Error Visibility for jobs/v4/howto
  jobs/v4/howto/auto_complete_sample.go
  jobs/v4/howto/basic_client_event.go
  jobs/v4/howto/batch_delete_jobs.go
  jobs/v4/howto/commute_search_sample.go
  jobs/v4/howto/create_company_sample.go
  jobs/v4/howto/create_job_sample.go
  jobs/v4/howto/custom_attribute_sample.go
  jobs/v4/howto/custom_ranking_search.go
  jobs/v4/howto/delete_company_sample.go
  jobs/v4/howto/delete_job_sample.go
  jobs/v4/howto/get_company_sample.go
  jobs/v4/howto/get_job_sample.go
  jobs/v4/howto/histogram_search_sample.go
  jobs/v4/howto/list_company_sample.go
  jobs/v4/howto/list_job_sample.go
Labels: samples

#3107 chore(fixit): Go Error Visibility for monitoring/snippets
  monitoring/snippets/channel_delete.go
  monitoring/snippets/channel_delete_test.go
  monitoring/snippets/channel_enable.go
  monitoring/snippets/metric_create.go
  monitoring/snippets/metric_delete.go
  monitoring/snippets/metric_get.go
  monitoring/snippets/metric_list.go
  monitoring/snippets/monitored_resource_get.go
  monitoring/snippets/monitored_resource_get_test.go
  monitoring/snippets/monitored_resource_list.go
  monitoring/snippets/time_series_align.go
  monitoring/snippets/time_series_fields.go
  monitoring/snippets/time_series_reduce.go
Labels: samples

#3091 chore(fixit): Go error visibility for pubsub
  pubsub/schemas/commit_avro_schema.go
  pubsub/schemas/commit_proto_schema.go
  pubsub/schemas/create_avro_schema.go
  pubsub/schemas/create_proto_schema.go
  pubsub/schemas/create_topic_with_schema.go
  pubsub/schemas/create_topic_with_schema_revisions.go
  pubsub/schemas/delete_schema.go
  pubsub/schemas/delete_schema_revision.go
  pubsub/schemas/get_schema.go
  pubsub/schemas/get_schema_revision.go
  pubsub/schemas/list_schema_revisions.go
  pubsub/schemas/list_schemas.go
  pubsub/schemas/publish_avro_records.go
  pubsub/schemas/publish_proto_messages.go
  pubsub/schemas/rollback_schema.go
  pubsub/schemas/subscribe_avro_records.go
  pubsub/schemas/subscribe_proto_messages.go
  pubsub/schemas/subscribe_with_avro_schema_revisions.go
  pubsub/schemas/update_topic_schema.go
  pubsub/subscriptions/add_users.go
  pubsub/subscriptions/async_pull.go
  pubsub/subscriptions/async_pull_custom_attributes.go
  pubsub/subscriptions/create.go
  pubsub/subscriptions/create_bigquery_subscription.go
  pubsub/subscriptions/create_endpoint.go
  pubsub/subscriptions/create_exactly_once_delivery.go
  pubsub/subscriptions/create_filter.go
  pubsub/subscriptions/create_ordering.go
  pubsub/subscriptions/dead_letter_create.go
  pubsub/subscriptions/dead_letter_delivery_attempt.go
  pubsub/subscriptions/dead_letter_remove.go
  pubsub/subscriptions/dead_letter_update.go
  pubsub/subscriptions/delete.go
  pubsub/subscriptions/detach_subscription.go
  pubsub/subscriptions/list.go
  pubsub/subscriptions/policy.go
  pubsub/subscriptions/pull_concurrency.go
  pubsub/subscriptions/pull_error.go
  pubsub/subscriptions/pull_exactly_once_delivery.go
  pubsub/subscriptions/pull_settings.go
  pubsub/subscriptions/subscription_test.go
  pubsub/subscriptions/sync_pull.go
  pubsub/subscriptions/test_permissions.go
  pubsub/subscriptions/update.go
Labels: samples

#3110 chore(fixit): Go Error Visibility for media/videostitcher
  media/videostitcher/create_cdn_key.go
  media/videostitcher/create_cdn_key_akamai.go
  media/videostitcher/create_live_session.go
  media/videostitcher/create_slate.go
  media/videostitcher/create_vod_session.go
  media/videostitcher/delete_cdn_key.go
  media/videostitcher/delete_slate.go
  media/videostitcher/get_cdn_key.go
  media/videostitcher/get_live_ad_tag_detail.go
  media/videostitcher/get_live_session.go
  media/videostitcher/get_slate.go
  media/videostitcher/get_vod_ad_tag_detail.go
  media/videostitcher/get_vod_session.go
  media/videostitcher/get_vod_stitch_detail.go
  media/videostitcher/list_cdn_keys.go
  media/videostitcher/list_live_ad_tag_details.go
  media/videostitcher/list_slates.go
  media/videostitcher/list_vod_ad_tag_details.go
  media/videostitcher/list_vod_stitch_details.go
  media/videostitcher/update_cdn_key.go
  media/videostitcher/update_cdn_key_akamai.go
  media/videostitcher/update_slate.go
Labels: samples

#2695 sample(compute): update create_snapshot.go error
  compute/snapshots/create_snapshot.go
Labels: api: compute, samples

#3118 chore(fixit): Go Error Visibility for monitoring/custommetric
  monitoring/custommetric/custommetric.go
Labels: samples

#3095 chore(fixit): Go Error Visibility for dataproc/quickstart
  dataproc/quickstart/quickstart_test.go
Labels: samples

#3099 chore(fixit): error format update for container/listclusters
  container/listclusters/listclusters.go
Labels: samples

#3105 chore(fixit): Go error visibility for getting-started
  getting-started/authenticating-users/main.go
  getting-started/background/index/main.go
  getting-started/background/translate.go
Labels: samples

#3109 chore(fixit): Go error visibility for firestore
  firestore/collection_group_query.go
  firestore/collection_group_setup.go
  firestore/increment.go
  firestore/listen_changes.go
  firestore/listen_document.go
  firestore/listen_errors.go
  firestore/listen_multiple.go
  firestore/solution_counters.go
Labels: samples

#3111 chore(fixit): Go error visibility for DocAI
  documentai/documentai_quickstart/main.go
Labels: automerge, samples

#3112 chore(fixit): Go error visibility for Datastore
  datastore/admin/datastore_admin_client_create.go
  datastore/admin/datastore_admin_entities_export.go
  datastore/admin/datastore_admin_entities_import.go
  datastore/admin/datastore_admin_index_get.go
  datastore/admin/datastore_admin_index_list.go
  datastore/snippets/snippet_test.go
Labels: samples

#3115 chore(fixit): Go Error Visibility for media/transcoder
  media/transcoder/create_job_from_ad_hoc.go
  media/transcoder/create_job_from_preset.go
  media/transcoder/create_job_from_template.go
  media/transcoder/create_job_template.go
  media/transcoder/create_job_with_animated_overlay.go
  media/transcoder/create_job_with_concatenated_inputs.go
  media/transcoder/create_job_with_embedded_captions.go
  media/transcoder/create_job_with_periodic_images_spritesheet.go
  media/transcoder/create_job_with_set_number_images_spritesheet.go
  media/transcoder/create_job_with_standalone_captions.go
  media/transcoder/create_job_with_static_overlay.go
  media/transcoder/delete_job.go
  media/transcoder/delete_job_template.go
  media/transcoder/get_job.go
  media/transcoder/get_job_state.go
  media/transcoder/get_job_template.go
  media/transcoder/list_job_templates.go
  media/transcoder/list_jobs.go
Labels: samples

#3116 chore(fixit): Go Error Visibility for profiler/shakesapp/shakesapp
  profiler/shakesapp/shakesapp/server.go
Labels: samples

#3117 chore(fixit): Go Error Visibility for monitoring/alert
  monitoring/alert/alert.go
Labels: samples

#3103 feat(dlp): added a sample for dlp inspect image file
  dlp/snippets/inspect/inspect_image_file.go
  dlp/snippets/inspect/inspect_test.go
Labels: api: dlp, samples

#3093 feat(logging): add a sample for list logs
  logging/list_logs.go
  logging/list_logs_test.go
Labels: api: logging, samples

#3100 feat(dlp): added a sample for dlp get job
  dlp/snippets/jobs/get.go
  dlp/snippets/jobs/jobs_test.go
Labels: api: dlp, samples

#3122 feat(fixit): Adding CA samples for private CA
  privateca/create_ca.go
  privateca/delete_ca.go
  privateca/disable_ca.go
  privateca/enable_ca.go
  privateca/go.mod
  privateca/privateca_test.go
  privateca/undelete_ca.go
Labels: samples

#3128 chore: refactor exportlogs samples to stand alone
  logging/exportlogs/create_sink.go
  logging/exportlogs/delete_sink.go
  logging/exportlogs/exportlogs.go
  logging/exportlogs/list_sink.go
  logging/exportlogs/update_sink.go
Labels: api: logging, samples

#3127 chore(securitycenter): adds SCC org and project
  testing/kokoro/system_tests.sh
Labels: api: securitycenter, samples

#3125 chore(simplelog): refactor samples to be standalone
  logging/simplelog/delete_log.go
  logging/simplelog/list_log_entries.go
  logging/simplelog/simplelog.go
  logging/simplelog/simplelog_test.go
  logging/simplelog/write_log.go
Labels: api: logging, samples

#3129 chore(spanner): update region tags
  spanner/spanner_snippets/spanner/pg_spanner_dml_delete_returning.go
  spanner/spanner_snippets/spanner/pg_spanner_dml_insert_returning.go
  spanner/spanner_snippets/spanner/pg_spanner_dml_update_returning.go
  spanner/spanner_snippets/spanner/spanner_dml_delete_returning.go
  spanner/spanner_snippets/spanner/spanner_dml_insert_returning.go
  spanner/spanner_snippets/spanner/spanner_dml_update_returning.go
Labels: api: spanner, samples

#3134 refactor(firestore): Refactor firestore/retrieve.go
  firestore/retrieve.go
  firestore/retrieve_data_get_all_documents.go
  firestore/retrieve_data_get_as_custom_type.go
  firestore/retrieve_data_get_as_map.go
  firestore/retrieve_data_get_dataset.go
  firestore/retrieve_data_get_sub_collections.go
  firestore/retrieve_data_query.go
  firestore/retrieve_data_reference_collection.go
  firestore/retrieve_data_reference_document.go
  firestore/retrieve_data_reference_document_path.go
  firestore/retrieve_data_reference_subcollection.go
Labels: api: firestore, samples

#3131 feat(iam): add samples for add_member and remove_member
  iam/go.mod
  iam/snippets/member_add.go
  iam/snippets/member_add_test.go
  iam/snippets/member_remove.go
  iam/snippets/member_remove_test.go
Labels: api: iam, samples

#3137 feat(fixit): create, list and revoke certificate samples
  privateca/create_certificate.go
  privateca/list_certificates.go
  privateca/privateca_test.go
  privateca/revoke_certificate.go
Labels: samples

#2989 feat(firestore): adds OR query sample
  firestore/go.mod
  firestore/go.sum
  firestore/query_filter_or.go
  firestore/query_filter_or_test.go
Labels: api: firestore, samples

#3021 feat(asset): Add sample code for Org Policy Analyzer
  asset/quickstart/analyze-org-policies/analyze_org_policies.go
  asset/quickstart/analyze-org-policies/main_test.go
  asset/quickstart/analyze-org-policy-governed-assets/analyze_org_policy_governed_assets.go
  asset/quickstart/analyze-org-policy-governed-assets/main_test.go
  asset/quickstart/analyze-org-policy-governed-containers/analyze_org_policy_governed_containers.go
  asset/quickstart/analyze-org-policy-governed-containers/main_test.go
Labels: api: cloudasset, samples

#3135 feat(logging): add a sample for logging_get_sink
  logging/get_sink.go
  logging/get_sink_test.go
Labels: api: logging, samples

#3141 chore(fixit): Go Error Visibility for iap
  iap/request.go
  iap/validate.go
Labels: samples

#3008 feat(run): Add Cloud Run custom metrics example
  run/custom-metrics/.dockerignore
  run/custom-metrics/Dockerfile
  run/custom-metrics/collector/Dockerfile
  run/custom-metrics/collector/collector-config.yaml
  run/custom-metrics/go.mod
  run/custom-metrics/go.sum
  run/custom-metrics/main.go
  run/custom-metrics/main_test.go
Labels: samples

#3138 chore(endpoints): Update region tag with product prefix
  endpoints/getting-started/app.yaml
Labels: samples, api: endpoints

#3136 chore(datastore/tasks): refactor samples to stand alone
  datastore/tasks/add_entity.go
  datastore/tasks/create_client.go
  datastore/tasks/delete_entity.go
  datastore/tasks/list_entities.go
  datastore/tasks/tasks.go
  datastore/tasks/tasks_test.go
  datastore/tasks/update_entity.go
Labels: api: datastore, samples

#3124 fix(dlp): fixing the branch syncing issues in DLP
  dlp/snippets/inspect/inspect_test.go
Labels: api: dlp, samples

#3142 chore(privateca): adding t.Helper calls per best practices
  privateca/privateca_test.go
Labels: samples

#3096 feat(dlp): added a sample for dlp create job
  dlp/snippets/jobs/create.go
  dlp/snippets/jobs/jobs_test.go
  dlp/snippets/jobs/testdata/test.txt
Labels: api: dlp, samples

#3120 feat(dlp): added a sample for dlp inspect image all infotypes
  dlp/snippets/inspect/inspect_image_all_infotypes.go
  dlp/snippets/inspect/inspect_test.go
  dlp/snippets/inspect/testdata/image.jpg
Labels: api: dlp, samples

#3143 feat(speech): add transcription snippets
  badfiles_test.go
  speech/resources/commercial_mono.wav
  speech/snippets/transcribe_diarization.go
  speech/snippets/transcribe_diarization_beta.go
  speech/snippets/transcribe_model_selection_gcs.go
  speech/snippets/transcribe_test.go
Labels: api: speech, samples

#3145 fix(run): Update cloud run custom metrics example to use PORT env var
  run/custom-metrics/main.go
  run/custom-metrics/main_test.go
Labels: api: run, samples
