Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2024-04, with the labels that each got.

#3972 test(storagetransfer): add retries to all storagetransfer tests
  storagetransfer/storagetransfer_test.go
Labels: automerge, api: storagetransfer, samples

#3988 sample(storage): add storage control quickstart
  storage/control_quickstart/main.go
  storage/control_quickstart/main_test.go
  storage/go.mod
  storage/go.sum
Labels: api: storage, samples

#3999 fix(otel-instrumentation): fix severity mapping to work with Cloud Logging agent
  opentelemetry/instrumentation/app/logger.go
  opentelemetry/instrumentation/app/logger_test.go
  opentelemetry/instrumentation/otel-collector-config.yaml
Labels: samples

#3772 feat(speech): adding speech quickstart and snippets for v2
  speech/go.mod
  speech/speech_quickstart_v2/README.md
  speech/speech_quickstart_v2/main.go
Labels: api: speech, samples

#3991 fix: fix/skip some broken tests
  Makefile
  badfiles_test.go
  internal/e2e/README.md
  internal/e2e/standard_test.go
  securitycenter/muteconfig/mute_config_test.go
Labels: samples

#4103 fix(speech): updated README.md to update apiv1 to apiv2
  speech/speech_quickstart_v2/README.md
Labels: samples

#3851 feat(vertexai): Align Function calling chat sample with the Python sample.
  vertexai/function-calling/functioncalling.go
  vertexai/function-calling/functioncalling_test.go
Labels: samples

#4109 fix(vertexai): variable name
  vertexai/multimodal-video/multimodalvideo.go
Labels: samples
