Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2024-09, with the labels that each got.

#4355 chore(automl): remove deprecated samples from automl/language directory
  automl/language/entity_extraction/dataset_create.go
  automl/language/entity_extraction/model_create.go
  automl/language/entity_extraction/predict.go
  automl/language/sentiment_analysis/dataset_create.go
  automl/language/sentiment_analysis/model_create.go
  automl/language/sentiment_analysis/predict.go
  automl/language/text_classification/dataset_create.go
  automl/language/text_classification/model_create.go
  automl/language/text_classification/predict.go
Labels: api: automl, samples

#4356 chore(automl): remove automl vision samples
  automl/vision/classification/dataset_create.go
  automl/vision/classification/model_create.go
  automl/vision/classification/model_deploy_with_node_count.go
  automl/vision/classification/predict.go
  automl/vision/object_detection/dataset_create.go
  automl/vision/object_detection/model_create.go
  automl/vision/object_detection/model_deploy_with_node_count.go
  automl/vision/object_detection/predict.go
Labels: api: automl, samples

#3961 feat(pubsub): add otel tracing samples
  pubsub/go.mod
  pubsub/go.sum
  pubsub/subscriptions/pull_otel_tracing.go
  pubsub/subscriptions/subscription_test.go
  pubsub/topics/publish_otel_tracing.go
  pubsub/topics/topics_test.go
Labels: api: pubsub, samples

#4343 feat(bigqueryv2): Add Big Query v2 client libraries/ samples
  securitycenter/bigqueryv2/bigquery_test.go
  securitycenter/bigqueryv2/create_big_query_export.go
  securitycenter/bigqueryv2/delete_big_query_export.go
  securitycenter/bigqueryv2/get_big_query_export.go
  securitycenter/bigqueryv2/list_big_query_export.go
  securitycenter/bigqueryv2/update_big_query_export.go
Labels: api: bigquery, samples

#4359 feat: batch_create_custom_serive_account sample
  batch/create_with_service_account.go
  batch/create_with_service_acount_test.go
Labels: samples

#4313 feat: Create a few code snippets as examples for using Spanner Graph in golang
  spanner/spanner_snippets/spanner/integration_test.go
  spanner/spanner_snippets/spanner/spanner_create_database_with_property_graph.go
  spanner/spanner_snippets/spanner/spanner_delete_graph_data.go
  spanner/spanner_snippets/spanner/spanner_dml_delete_graph_data.go
  spanner/spanner_snippets/spanner/spanner_dml_insert_graph_data.go
  spanner/spanner_snippets/spanner/spanner_dml_update_graph_data.go
  spanner/spanner_snippets/spanner/spanner_dml_update_graph_data_with_graph_query.go
  spanner/spanner_snippets/spanner/spanner_insert_graph_data.go
  spanner/spanner_snippets/spanner/spanner_query_graph_data.go
  spanner/spanner_snippets/spanner/spanner_query_graph_data_with_parameter.go
Labels: api: spanner, samples

#4357 docs(bigquery): minor doc fixes
  bigquery/snippets/managedwriter/exampleproto/sample_data.pb.go
  bigquery/snippets/managedwriter/exampleproto/sample_data.proto
Labels: api: bigquery, samples

#4361 chore: Extended existing sample with new attribute
  compute/disks/create_hyperdisk_pool.go
  compute/disks/disks_test.go
  compute/go.mod
  compute/go.sum
Labels: samples

#4369 feat: reservations create/get/list/delete samples
  compute/reservations/create_reservation.go
  compute/reservations/delete_reservation.go
  compute/reservations/get_reservation.go
  compute/reservations/list_reservations.go
  compute/reservations/reservations_test.go
Labels: kokoro:run, samples

#4375 chore: fix linter issue
  .github/workflows/go.yaml
Labels: samples

#4371 fix: moved context inside functions
  compute/reservations/reservations_test.go
Labels: samples

#4373 fix: remove discoveryengine samples
  discoveryengine/go.mod
  discoveryengine/go.sum
  discoveryengine/search.go
  discoveryengine/search_test.go
Labels: samples

#4352 feat(firestore): Query explain and explain analyze
  firestore/aggregate_query_explain.go
  firestore/aggregate_query_explain_analyze.go
  firestore/aggregate_query_explain_analyze_test.go
  firestore/aggregate_query_explain_test.go
  firestore/go.mod
  firestore/go.sum
  firestore/query_explain.go
  firestore/query_explain_analyze.go
  firestore/query_explain_analyze_test.go
  firestore/query_explain_test.go
  firestore/query_multiple_inequality_test.go
Labels: api: firestore, samples

#4376 feat(pubsub): add publish compression sample
  pubsub/topics/publish_with_compression.go
  pubsub/topics/topics_test.go
Labels: api: pubsub, samples

#4253 feat: added labels samples for secret manager
  secretmanager/create_secret_with_labels.go
  secretmanager/create_update_secret_label.go
  secretmanager/delete_secret_label.go
  secretmanager/go.mod
  secretmanager/go.sum
  secretmanager/secretmanager_test.go
  secretmanager/view_secret_labels.go
Labels: samples

#4345 fix: Fix environment variable substitution for GOOGLE_CLOUD_PROJECT.
  opentelemetry/instrumentation/otel-collector-config.yaml
Labels: samples

#4381 chore(samples): add sample for spanner editions
  spanner/go.mod
  spanner/go.sum
  spanner/spanner_snippets/spanner/integration_test.go
  spanner/spanner_snippets/spanner/spanner_create_instance.go
  spanner/spanner_snippets/spanner/spanner_update_instance.go
Labels: api: spanner, samples

#4379 feat: add v2 API config for bulk mute finding to the existing mute config Go client library or samples
  securitycenter/muteconfigv2/bulk_mute.go
  securitycenter/muteconfigv2/mute_config_test.go
Labels: api: securitycenter, samples

#4377 fix(healthcare): replace deprecated NotificationConfig with FhirNotificationConfig
  healthcare/fhir_store_patch.go
Labels: api: healthcare, samples

#4380 feat(auth): add sample apikeys_authenticate_api_key
  auth/auth_test.go
  auth/authenticate_with_api_key.go
  auth/go.mod
  auth/go.sum
Labels: samples

#4393 chore(samples): Add samples for Cloud Spanner Scheduled Backups
  spanner/spanner_snippets/spanner/integration_test.go
  spanner/spanner_snippets/spanner/spanner_create_full_backup_schedule.go
  spanner/spanner_snippets/spanner/spanner_create_incremental_backup_schedule.go
  spanner/spanner_snippets/spanner/spanner_delete_backup_schedule.go
  spanner/spanner_snippets/spanner/spanner_get_backup_schedule.go
  spanner/spanner_snippets/spanner/spanner_list_backup_schedules.go
  spanner/spanner_snippets/spanner/spanner_update_backup_schedule.go
Labels: api: spanner, samples

#4396 fix(docs): Fixing region tag name
  batch/create_with_service_account.go
Labels: samples

#4398 docs: update analyticshub sample to use v1 analyticshub client
  bigquery/bigquery_analyticshub_quickstart/main.go
  bigquery/go.mod
  bigquery/go.sum
Labels: samples

#4281 chore(bigquery): remove deprecated proto pkg
  bigquery/bigquery_storage_quickstart/main.go
  internal/mtls_smoketest/smoketest_test.go
Labels: api: bigquery, samples

#4400 chore(CODEOWNERS): Add cloud-samples-infra team to repo config ownership
  .github/CODEOWNERS
Labels: samples

#4401 chore(CODEOWNERS): Remove unused teams
  .github/CODEOWNERS
Labels: samples

#4404 chore(blunderbuss): Remove unused teams
  .github/blunderbuss.yml
Labels: samples

#4409 fix: changes batch samples to 1000 CPU millis
  batch/create_with_local_ssd.go
  batch/create_with_persistent_disk.go
Labels: automerge, samples, api: batch

#4408 fix(cloudrun): update practices from deprecated ioutil to io
  run/pubsub/main.go
  run/pubsub/main_test.go
Labels: samples
