Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2024-01, with the labels that each got.

#3707 test(profiler): add tests for ListProfiles sample
  profiler/export/main.go
  profiler/export/main_test.go
  profiler/go.mod
  profiler/go.sum
  testing/kokoro/system_tests.sh
Labels: api: cloudprofiler, samples

#3724 feat(spanner): add samples for directed reads
  spanner/go.mod
  spanner/go.sum
  spanner/spanner_snippets/spanner/integration_test.go
  spanner/spanner_snippets/spanner/spanner_directed_read_options.go
Labels: api: spanner, samples

#3618 feat: add live session methods and tests
  media/videostitcher/create_live_session.go
  media/videostitcher/create_live_session_test.go
  media/videostitcher/get_live_ad_tag_detail_test.go
  media/videostitcher/get_live_session_test.go
  media/videostitcher/list_live_ad_tag_details_test.go
  media/videostitcher/stitcher_test.go
Labels: samples

#3741 fix: use go1.21, without a toolchain directive- avoiding diffs in go.mod
  .github/workflows/go.yaml
Labels: samples

#3710 Fix: error of close intanceTemplatesClient
  compute/create_instance_from_template_with_overrides.go
Labels: samples

#3758 test(storage): add retry to flaky SignedURL test
  storage/objects/objects_test.go
Labels: api: storage, samples

#3759 test(storage): add retry to HMAC key deletion
  storage/service_account/hmac/hmac_test.go
Labels: api: storage, samples
