Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2024-11, with the labels that each got.

#4462 feat: migrate earliest-version off of Container Registry
  testing/kokoro/earliest-version.cfg
Labels: samples

#4472 chore: upgrade GHA workflows to use stable go
  .github/workflows/go.yaml
  getting-started/gopher-run/cmd/main.go
Labels: samples

#4461 feat: adopt go.work to ensure consistent inter-repo deps
  .gitignore
  badfiles_test.go
  functions/functionsv2/helloworld/go.mod
  functions/functionsv2/log/go.mod
  functions/functionsv2/ocr/app/go.mod
  go.work
Labels: samples

#4451 feat: migrate Cloud Run testing to Artifact Registry
  go.mod
  go.sum
  internal/cloudrunci/cloudrunci.go
  internal/cloudrunci/cloudrunjobs.go
  run/testing/go.mod
  run/testing/go.sum
Labels: samples

#4497 chore: update code ownership and blunderbuss auto-assignments
  .github/CODEOWNERS
  .github/blunderbuss.yml
Labels: samples

#4430 feat: create reservation from existing VM sample
  compute/reservations/create_reservation_from_vm.go
  compute/reservations/reservations_test.go
Labels: api: compute, samples

#4457 feat(gen ai): add samples for aiplatform batch predict api with gemini
  vertexai/batch-predict/batch_predict_test.go
  vertexai/batch-predict/gemini_batch_predict_bq.go
  vertexai/batch-predict/gemini_batch_predict_gcs.go
Labels: samples, api: vertex-ai

#4533 chore: clean builds
  testing/kokoro/system_tests.sh
Labels: samples

#4546 Fix: managedkafka subnet comment format
  managedkafka/clusters/create_cluster.go
Labels: samples

#4544 Fix: update_consumergroup partitionOffsets
  managedkafka/consumergroups/update_consumergroup.go
Labels: samples

#4543 Fix: managedkafka create_topic and update_topic samples
  managedkafka/topics/create_topic.go
  managedkafka/topics/update_topic.go
Labels: samples

#4547 feat(security-command-center): simplify "create client with endpoint" sample
  securitycenter/clientv2/create_client_with_endpoint.go
Labels: api: securitycenter, samples

#4514 feat(gen ai): add samples for aiplatform evaluation api
  go.work
  vertexai/evaluation/evaluate_output.go
  vertexai/evaluation/evaluation_test.go
  vertexai/evaluation/get_rouge_score.go
  vertexai/evaluation/go.mod
  vertexai/evaluation/go.sum
  vertexai/evaluation/pairwise_evaluation.go
Labels: samples, api: aiplatform, api: vertex-ai

#4528 feat(securitycenter): Add Resource SCC Management API Org ETD Custom Module samples (Create, Delete, Get, List, Update)
  securitycenter/management_api/event_threat_detection/create_event_threat_detection_custom_module.go
  securitycenter/management_api/event_threat_detection/delete_event_threat_detection_custom_module.go
  securitycenter/management_api/event_threat_detection/event_threat_detection_custom_module_test.go
  securitycenter/management_api/event_threat_detection/get_event_threat_detection_custom_module.go
  securitycenter/management_api/event_threat_detection/list_event_threat_detection_custom_module.go
  securitycenter/management_api/event_threat_detection/update_event_threat_detection_custom_module.go
Labels: api: securitycenter, samples

#4567 chore: remove extraneous string
  dlp/snippets/deid/deid_table_fpe.go
Labels: samples

#4529 feat(datastore): adds create new client with custom database
  datastore/tasks/client_with_database.go
  datastore/tasks/tasks_test.go
Labels: api: datastore, samples

#4569 feat: start/stop async replication samples
  compute/disks/create_secondary_disk.go
  compute/disks/create_secondary_disk_custom.go
  compute/disks/create_secondary_disk_regional.go
  compute/disks/disks_test.go
  compute/disks/start_replication.go
  compute/disks/stop_replication.go
Labels: api: compute, samples

#4527 feat(spanner): Add samples for Cloud Spanner Default Backup Schedules
  spanner/go.mod
  spanner/go.sum
  spanner/spanner_snippets/spanner/integration_test.go
  spanner/spanner_snippets/spanner/spanner_create_instance_without_default_backup_schedule.go
  spanner/spanner_snippets/spanner/spanner_update_instance_default_backup_schedule_type.go
Labels: api: spanner, samples

#4568 feat(gen ai): add parameter example to evaluation samples
  vertexai/evaluation/evaluate_output.go
  vertexai/evaluation/get_rouge_score.go
  vertexai/evaluation/pairwise_evaluation.go
Labels: samples, api: aiplatform

#4596 fix: update practices from deprecated ioutil to io
  cloudsql/mysql/database-sql/connect_tcp.go
Labels: samples

#4593 fix: update practices from deprecated ioutil to io
  auth/downscoping/token_consumer.go
Labels: samples

#4603 fix: update practices from deprecated ioutil to io
  run/markdown-preview/editor/render.go
Labels: samples

#4619 feat(eventarc): improved error handling
  functions/functionsv2/hellostorage/hello_storage.go
Labels: samples, api: eventarc

#4647 feat: add sample for controlled generation with enum schema
  vertexai/controlled-generation/controlledgen_schema_enum.go
  vertexai/controlled-generation/controlledgen_schema_test.go
  vertexai/controlled-generation/go.mod
  vertexai/controlled-generation/go.sum
Labels: samples, api: aiplatform

#4637 Refactor: Replace ioutil with os in redact_image_listed_infotypes.go for go 1.16 compatibility
  dlp/snippets/redact/redact_image_listed_infotypes.go
Labels: samples

#4586 feat: consistency group basic operations
  compute/disks/consistency_group_add_disk.go
  compute/disks/consistency_group_create.go
  compute/disks/consistency_group_delete.go
  compute/disks/consistency_group_remove_disk.go
  compute/disks/disks_test.go
Labels: api: compute, samples

#4601 fix: Delete functions_ci_cd_cloud_build for Cloud Functions from cloudbuild.yaml file
  functions/ci_cd/cloudbuild.yaml
Labels: samples

#4627 Refactor: Replace ioutil with io in hello_pubsub_test.go for go 1.16 compatibility
  functions/functionsv2/hellopubsub/hello_pubsub_test.go
Labels: samples

#4663 fix: update practices from deprecated ioutil to io
  healthcare/fhir_execute_bundle.go
Labels: samples

#4662 fix: update practices from deprecated ioutil to io
  functions/helloworld/hello_cloud_storage_test.go
Labels: samples

#4665 fix: update practices from deprecated ioutil to io/os
  healthcare/dicomweb_instance_store.go
Labels: samples

#4661 fix: update practices from deprecated ioutil to io
  functions/helloworld/hello_pubsub_test.go
Labels: samples

#4659 fix: update practices from deprecated ioutil to os
  dlp/snippets/redact/redact_image_all_text.go
Labels: samples

#4658 fix: update practices from deprecated ioutil to os
  dlp/snippets/redact/redact_image_colored_infotypes.go
  dlp/snippets/redact/redact_image_colored_infotypes_test.go
Labels: samples

#4654 feat(securitycenter): Add Resource SCC Management API Org Security Center Service Custom Module samples (Get, List, Update)
  securitycenter/management_api/security_center_service/get_security_center_service.go
  securitycenter/management_api/security_center_service/list_security_center_service.go
  securitycenter/management_api/security_center_service/security_center_service_test.go
  securitycenter/management_api/security_center_service/update_security_center_service.go
Labels: api: securitycenter, samples

#4653 feat(vertexai): add new sample for function-calling/text
  vertexai/function-calling/functioncalling_basic.go
  vertexai/function-calling/functioncalling_test.go
Labels: samples, api: aiplatform

#4651 fix: update practices from deprecated ioutil to io
  functions/slack/search.go
Labels: samples

#4625 chore(eventarc): Replace ioutil with io in GenericHandler for go 1.16 compatibility
  eventarc/generic/main.go
Labels: samples
