Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2024-08, with the labels that each got.

#4265 feat: added samples for regional SM
  secretmanager/regional_quickstart/regional_quickstart.go
  secretmanager/regional_samples/access_regional_secret_version.go
  secretmanager/regional_samples/add_regional_secret_version.go
  secretmanager/regional_samples/create_regional_secret.go
  secretmanager/regional_samples/delete_regional_secret.go
  secretmanager/regional_samples/delete_regional_secret_with_etag.go
  secretmanager/regional_samples/destroy_regional_secret_version.go
  secretmanager/regional_samples/destroy_regional_secret_version_with_etag.go
  secretmanager/regional_samples/disable_regional_secret_version.go
  secretmanager/regional_samples/disable_regional_secret_version_with_etag.go
  secretmanager/regional_samples/enable_regional_secret_version.go
  secretmanager/regional_samples/enable_regional_secret_version_with_etag.go
  secretmanager/regional_samples/get_regional_secret.go
  secretmanager/regional_samples/get_regional_secret_version.go
  secretmanager/regional_samples/iam_grant_access_with_regional_secret.go
  secretmanager/regional_samples/iam_revoke_access_with_regional_secret.go
  secretmanager/regional_samples/list_regional_secret_versions.go
  secretmanager/regional_samples/list_regional_secret_versions_with_filter.go
  secretmanager/regional_samples/list_regional_secrets.go
  secretmanager/regional_samples/list_regional_secrets_with_filter.go
  secretmanager/regional_samples/update_regional_secret.go
  secretmanager/regional_samples/update_regional_secret_with_alias.go
  secretmanager/regional_samples/update_regional_secret_with_etag.go
  secretmanager/secretmanager_test.go
Labels: samples

#4304 fix: wordcount.go - register DoFns with the the beam/register package
  dataflow/flex-templates/wordcount/wordcount.go
Labels: samples

#4298 fix: simpify sample structure
  vertexai/multimodal-pdf/pdf.go
  vertexai/multimodal-pdf/pdf_test.go
Labels: samples

#4307 chore: update kokoro go versions
  testing/kokoro/earliest-version.cfg
  testing/kokoro/latest-version.cfg
Labels: samples

#4299 feat(dlp): Add code sample for using REP endpoint
  dlp/snippets/inspect/inspect_string_rep.go
  dlp/snippets/inspect/inspect_string_rep_test.go
Labels: kokoro:force-run, samples

#4300 fix: Adding more complex context for weather and corresponding test
  vertexai/function-calling/functioncalling_basic.go
  vertexai/function-calling/functioncalling_test.go
Labels: samples

#4306 fix: moved prompt inside function
  vertexai/safety-settings-multimodal/safety-settings-multimodal.go
  vertexai/safety-settings-multimodal/safety-settings-multimodal_test.go
Labels: samples

#4311 feat(datastore): Multiple inequalities
  datastore/go.mod
  datastore/snippets/query_mieq.go
  datastore/snippets/query_test.go
Labels: api: datastore, samples

#4268 feat: add v2 API for muteconfig Go client libraries or samples
  securitycenter/muteconfigv2/create_mute_rule.go
  securitycenter/muteconfigv2/delete_mute_rule.go
  securitycenter/muteconfigv2/get_mute_rule.go
  securitycenter/muteconfigv2/list_mute_rules.go
  securitycenter/muteconfigv2/mute_config_test.go
  securitycenter/muteconfigv2/set_mute_finding.go
  securitycenter/muteconfigv2/set_unmute_finding.go
  securitycenter/muteconfigv2/update_mute_rule.go
Labels: samples

#4322 feat: Elastic Text-Embedding Model demo (preview0815).
  aiplatform/snippets/embeddings_preview.go
  aiplatform/snippets/embeddings_test.go
Labels: samples

#4226 feat: add v2 API findings samples for create, update
  securitycenter/findingsv2/create_finding.go
  securitycenter/findingsv2/findings_test.go
  securitycenter/findingsv2/set_finding_state.go
  securitycenter/findingsv2/update_finding_source_properties.go
  securitycenter/go.mod
  securitycenter/go.sum
Labels: samples

#4269 feat: add v2 API for resource notification config Go client libraries
  securitycenter/notificationsv2/create_notification_config.go
  securitycenter/notificationsv2/delete_notification_config.go
  securitycenter/notificationsv2/get_notification_config.go
  securitycenter/notificationsv2/list_notification_configs.go
  securitycenter/notificationsv2/notifications_test.go
  securitycenter/notificationsv2/receive_notifications.go
  securitycenter/notificationsv2/update_notification_config.go
Labels: api: securitycenter, samples

#4293 samples(storage): add Managed Folders Samples
  storage/control/create_managed_folder.go
  storage/control/delete_managed_folder.go
  storage/control/folders_test.go
  storage/control/get_managed_folder.go
  storage/control/list_managed_folder.go
Labels: api: storage, samples

#4335 fix: step 1 of adding region tag
  endpoints/getting-started/deployment.yaml
Labels: samples

#4334 fix(pubsub): add locational endpoint for exactly once sample
  pubsub/subscriptions/pull_exactly_once_delivery.go
  pubsub/topics/publish_ordering.go
  pubsub/topics/publish_resume_ordering.go
Labels: api: pubsub, samples

#4270 feat(findings): Add findings v2 resources
  securitycenter/findingsv2/add_security_marks.go
  securitycenter/findingsv2/create_source.go
  securitycenter/findingsv2/findings_test.go
  securitycenter/findingsv2/get_source.go
  securitycenter/findingsv2/group_filtered_findings.go
  securitycenter/findingsv2/group_findings.go
  securitycenter/findingsv2/group_findings_state.go
  securitycenter/findingsv2/list_all_findings.go
  securitycenter/findingsv2/list_filtered_findings.go
  securitycenter/findingsv2/list_findings_with_security_mark.go
  securitycenter/findingsv2/list_sources.go
  securitycenter/findingsv2/update_source.go
Labels: api: securitycenter, samples

#4315 fix: moved attributes inside sample
  vertexai/multimodal/multimodal.go
  vertexai/multimodal/multimodal_test.go
Labels: samples

#4318 fix: move attributes inside sample
  vertexai/system-instruction/systeminstruction.go
  vertexai/system-instruction/systeminstruction_test.go
Labels: kokoro:run, samples

#4319 fix: move prompt inside the sample
  vertexai/multimodal-video-with-audio/multimodalvideoaudio.go
  vertexai/multimodal-video-with-audio/multimodalvideoaudio_test.go
Labels: samples

#4326 fix: refactoring aiplatform samples
  aiplatform/snippets/embeddings.go
  aiplatform/snippets/embeddings_preview.go
  aiplatform/snippets/embeddings_test.go
  aiplatform/text-predict/text.go
  aiplatform/text-predict/text_test.go
Labels: samples, aiplatform, api: vertex-ai

#3560 testing(run): Update all HTTP1 testing to new retry facility
  run/testing/helloworld.e2e_test.go
  run/testing/pubsub.e2e_test.go
  run/testing/system_package.e2e_test.go
Labels: api: run, samples

#4347 fix: resolve breaking build
  run/go.mod
  run/go.sum
  run/testing/pubsub.e2e_test.go
Labels: samples

#4314 fix: refactoring the sample
  vertexai/multimodal-multiple/multiple-multimodal.go
  vertexai/multimodal-multiple/multiple-multimodal_test.go
Labels: samples

#4310 feat(firestore): Multiple inequalities
  firestore/custom_type_definition.go
  firestore/query_multiple_inequality.go
  firestore/query_multiple_inequality_test.go
Labels: api: firestore, samples

#4325 Fix: moving function attributes inside samples, to make them self-descriptive
  vertexai/function-calling/functioncalling_basic.go
  vertexai/function-calling/functioncalling_test.go
  vertexai/multimodal-video-with-audio/multimodalvideoaudio.go
  vertexai/multimodal-video-with-audio/multimodalvideoaudio_test.go
  vertexai/multimodal-video/multimodalvideo.go
  vertexai/multimodal-video/multimodalvideo_test.go
  vertexai/multimodal/multimodal.go
  vertexai/multimodal/multimodal_test.go
  vertexai/safety-settings-multimodal/safety-settings-multimodal.go
  vertexai/safety-settings-multimodal/safety-settings-multimodal_test.go
  vertexai/safety-settings/safety-settings.go
  vertexai/safety-settings/safety-settings_test.go
Labels: samples

#4339 feat: batch_create_local_ssd_job sample
  batch/create_with_local_ssd.go
  batch/create_with_local_ssd_test.go
Labels: samples

#4344 feat: batch_create_persistent_disk_job sample created
  batch/create_with_persistent_disk.go
  batch/create_with_persistent_disk_test.go
Labels: samples
