Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2024-07, with the labels that each got.

#4179 feat(compute): samples/compute_instances_bulk_insert
  compute/go.mod
  compute/instances/create-start-instance/bulk_insert.go
  compute/instances/create-start-instance/create_instance_test.go
Labels: api: compute, samples

#4194 feat(compute): compute_ip_address_assign_static_external_new_vm sample
  compute/address/address_test.go
  compute/address/assign_static_address_to_new_vm.go
Labels: api: compute, samples

#4222 samples(discoveryengine): Update Vertex AI Search sample to use regional endpoint if needed
  discoveryengine/search.go
Labels: samples, api: discoveryengine

#4243 chore: remove get_job region tag from basic_job_sample.go
  jobs/v3/howto/basic_job_sample.go
Labels: samples

#4236 feat: use a module to encapsulate gimmeproj tool
  go.mod
  go.sum
  testing/gimmeproj/go.mod
  testing/gimmeproj/go.sum
Labels: samples

#4248 fix(compute): debian-10 image family EoL.
  compute/address/assign_static_address_to_new_vm.go
  compute/compute_test.go
  compute/create_instance.go
  compute/create_instance_from_template_test.go
  compute/create_instance_from_template_with_overrides.go
  compute/custom-hostname-instance/create_instance_with_custom_hostname.go
  compute/custom-hostname-instance/instance_hostname_test.go
  compute/instance-templates/create-instance-templates/create_instance_templates_test.go
  compute/instances/create-start-instance/create_instance_from_public_image.go
  compute/instances/create-start-instance/create_instance_with_additional_disk.go
  compute/instances/create-start-instance/create_instance_with_local_ssd.go
  compute/instances/create-start-instance/create_instance_with_snapshotted_data_disk.go
  compute/instances/create-start-instance/create_instance_with_subnet.go
  compute/instances/custom-machine-type/create_custom_machine_type.go
  compute/instances/custom-machine-type/create_shared_with_helper.go
  compute/instances/custom-machine-type/create_with_helper.go
  compute/instances/custom-machine-type/create_without_helper.go
  compute/instances/custom-machine-type/extra_mem_without_helper.go
  compute/instances/preventing-accidental-vm-deletion/create_instance.go
  compute/start_stop_instances_test.go
Labels: kokoro:force-run, api: compute, samples

#4244 fixit: migrate to new region tag in jobs
  jobs/v3/howto/basic_company_sample.go
  jobs/v3/howto/custom_attribute_sample.go
  jobs/v3/howto/histogram_search_sample.go
Labels: samples

#4227 fixit: migrate to new region tag with prefix 'job_'
  jobs/v3/howto/basic_company_sample.go
  jobs/v3/howto/basic_job_sample.go
  jobs/v3/howto/custom_attribute_sample.go
  jobs/v3/howto/location_based_search_sample.go
Labels: Fixit, samples

#4186 feat: Added create image from snapshot sample
  compute/disk-images/create_disk_image_from_snapshot.go
  compute/disk-images/disk_image_test.go
Labels: samples

#4225 chore(CODEOWNERS): Remove invalid iot entries
  .github/CODEOWNERS
Labels: samples

#4223 feat(gimmeproj): blocking retry on lease operations
  testing/gimmeproj/main.go
Labels: samples

#4195 feat(compute): compute_ip_address_promote_ephemeral sample
  compute/address/address_test.go
  compute/address/promote_ephemeral_address.go
Labels: api: compute, samples

#4193 feat(compute): compute_ip_address_get_vm_address sample
  compute/address/address_test.go
  compute/address/get_vm_address.go
Labels: api: compute, samples

#4191 feat(compute): hyperdisk_create/hyperdisk_pool_create/hyperdisk_create_from_pool samples
  compute/compute_test.go
  compute/disks/create_hyperdisk.go
  compute/disks/create_hyperdisk_from_pool.go
  compute/disks/create_hyperdisk_pool.go
  compute/disks/disks_test.go
  compute/go.mod
  compute/go.sum
Labels: api: compute, samples

#4259 docs(compute): Renaming region tag
  compute/disks/list.go
Labels: api: compute, samples

#4249 fix(jobs): delete old region tag
  jobs/v3/howto/featured_job_search_sample.go
Labels: Fixit, api: jobs, samples

#4257 feat(vertexai): Add controlled generation (constrained decoding)
  vertexai/controlled-generation/controlledgen_mime_type.go
  vertexai/controlled-generation/controlledgen_mime_type_test.go
  vertexai/controlled-generation/controlledgen_schema.go
  vertexai/controlled-generation/controlledgen_schema2.go
  vertexai/controlled-generation/controlledgen_schema3.go
  vertexai/controlled-generation/controlledgen_schema4.go
  vertexai/controlled-generation/controlledgen_schema6.go
  vertexai/controlled-generation/controlledgen_schema_test.go
  vertexai/controlled-generation/go.mod
  vertexai/controlled-generation/go.sum
Labels: samples

#4258 docs(spanner): add opentelemetry tracing spanner samples
  spanner/opentelemetry/tracing/Readme.md
  spanner/opentelemetry/tracing/go.mod
  spanner/opentelemetry/tracing/go.sum
  spanner/opentelemetry/tracing/spanner_opentelemetry_tracing.go
Labels: api: spanner, samples

#4210 feat(bigquery): add short mode query snippet
  bigquery/snippets/querying/bigquery_query_shortquery.go
  bigquery/snippets/querying/integration_test.go
Labels: api: bigquery, samples

#4220 feat(storage): add object retention samples
  internal/testutil/storage_cleaner.go
  storage/buckets/buckets_test.go
  storage/buckets/create_bucket_object_retention.go
  storage/buckets/get_bucket_metadata.go
  storage/go.mod
  storage/go.sum
  storage/objects/get_metadata.go
  storage/objects/objects_test.go
  storage/objects/set_object_retention.go
Labels: api: storage, samples

#4278 chore: update CODEOWNERS to add SCC team
  .github/CODEOWNERS
Labels: samples

#4251 fix(translate): Serbian expected translation
  translate/v3/translate_text_test.go
Labels: api: translate, samples

#4252 fix(batch): valid date format layout
  batch/create_with_gcs_bucket_test.go
  batch/create_with_template_test.go
  batch/job_basics_test.go
Labels: samples, api: batch

#4254 fix(bigquery): remove bucket name trailing dash
  bigquery/snippets/bqtestutil/bqtestutil.go
Labels: api: bigquery, samples

#4256 fix(internal): Printf with non-constant format arg
  internal/cloudrunci/cloudrunci.go
Labels: samples

#4214 feat(testing): run tests in modified packages only
  testing/kokoro/system_tests.sh
Labels: samples

#4266 feat: create job with notification sample
  batch/create_with_notification.go
  batch/job_basics_test.go
Labels: samples

#4245 fix(datastore): Iterator reused result object
  datastore/snippets/snippet_test.go
Labels: api: datastore, samples

#4279 chore(vertexai): use cloud.google.com/go/vertexai v0.12.0
  vertexai/chat/go.mod
  vertexai/chat/go.sum
  vertexai/function-calling/go.mod
  vertexai/function-calling/go.sum
  vertexai/multimodal-all/go.mod
  vertexai/multimodal-all/go.sum
  vertexai/multimodal-audio/go.mod
  vertexai/multimodal-audio/go.sum
  vertexai/multimodal-multiple/go.mod
  vertexai/multimodal-multiple/go.sum
  vertexai/multimodal-pdf/go.mod
  vertexai/multimodal-pdf/go.sum
  vertexai/multimodal-video-with-audio/go.mod
  vertexai/multimodal-video-with-audio/go.sum
  vertexai/multimodal-video/go.mod
  vertexai/multimodal-video/go.sum
  vertexai/multimodal/go.mod
  vertexai/multimodal/go.sum
  vertexai/safety-settings-multimodal/go.mod
  vertexai/safety-settings-multimodal/go.sum
  vertexai/safety-settings/go.mod
  vertexai/safety-settings/go.sum
  vertexai/snippets/go.mod
  vertexai/snippets/go.sum
  vertexai/stream-multimodality-basic/go.mod
  vertexai/stream-multimodality-basic/go.sum
  vertexai/stream-text-basic/go.mod
  vertexai/stream-text-basic/go.sum
  vertexai/system-instruction/go.mod
  vertexai/system-instruction/go.sum
  vertexai/token-count/go.mod
  vertexai/token-count/go.sum
Labels: samples

#4231 fix(firestore): Call document iterator stop function
  firestore/retrieve_data_get_all_documents.go
Labels: api: firestore, samples

#4283 fix(testing): downgrade gimmeproj deps to allow use of go119
  testing/gimmeproj/go.mod
  testing/gimmeproj/go.sum
Labels: samples

#4267 feat(vertexai): Context caching
  vertexai/context-caching/contextcaching_create.go
  vertexai/context-caching/contextcaching_delete.go
  vertexai/context-caching/contextcaching_get.go
  vertexai/context-caching/contextcaching_test.go
  vertexai/context-caching/contextcaching_update.go
  vertexai/context-caching/contextcaching_use.go
  vertexai/context-caching/go.mod
  vertexai/context-caching/go.sum
Labels: samples

#4288 docs(generativeai): add region tags for code samples
  aiplatform/snippets/embeddings.go
  aiplatform/text-predict/text.go
Labels: samples

#3785 docs(samples): passing data out of firestore transaction in go
  firestore/save_test.go
  firestore/save_transaction_document_update_conditional.go
Labels: samples

#4285 fix(dlp): use log for output during tests.
  dlp/snippets/inspect/inspect_send_data_to_hybrid_job_trigger_test.go
  dlp/snippets/redact/testdata/test_output.png
  dlp/snippets/template/template_test.go
  dlp/snippets/trigger/trigger_test.go
Labels: api: dlp, samples

#4224 fix(iotkit): Remove deprecated sample
  iotkit/README.md
  iotkit/go.mod
  iotkit/go.sum
  iotkit/helloworld/README.md
  iotkit/helloworld/display/display.go
  iotkit/helloworld/main.go
Labels: samples

#3966 fix: address the use of InsecureSkipVerify in sample
  cloudsql/mysql/database-sql/connect_tcp.go
  cloudsql/mysql/database-sql/go.mod
Labels: samples

#4287 fix: refactor variables to make samples more self-descriptive
  speech/snippets/auto_punctuation.go
  speech/snippets/auto_punctuation_test.go
  speech/snippets/context_classes.go
  speech/snippets/context_classes_test.go
  speech/snippets/enhanced_model.go
  speech/snippets/enhanced_model_test.go
  speech/snippets/model_selection.go
  speech/snippets/model_selection_test.go
  speech/snippets/multichannel.go
  speech/snippets/multichannel_test.go
  speech/snippets/transcribe_diarization.go
  speech/snippets/transcribe_diarization_beta.go
  speech/snippets/transcribe_model_selection_gcs.go
  speech/snippets/transcribe_streaming_v2.go
  speech/snippets/transcribe_streaming_v2_explicit_decoding.go
  speech/snippets/transcribe_streaming_v2_explicit_decoding_test.go
  speech/snippets/transcribe_streaming_v2_test.go
  speech/snippets/transcribe_test.go
Labels: samples

#4295 fix: simplifying gemini all modalities sample
  vertexai/multimodal-all/multimodalall.go
  vertexai/multimodal-all/multimodalall_test.go
Labels: samples

#4290 fix: update incorrect region tags
  speech/snippets/auto_punctuation.go
  speech/snippets/auto_punctuation_test.go
Labels: samples

#4291 feat: create batch with GPU accelerator sample
  batch/create_with_gpu.go
  batch/create_with_gpu_test.go
Labels: samples

#4286 feat(testing): improve process for building test images
  testing/docker/README.md
  testing/docker/bootstrap.sh
  testing/docker/cloudbuild.yaml
Labels: samples

#4289 feat: create batch custom events sample
  batch/create_with_custom_events.go
  batch/job_basics_test.go
Labels: kokoro:force-run, samples

#4276 feat(spanner): add samples for instance partitions
  spanner/spanner_snippets/spanner/integration_test.go
  spanner/spanner_snippets/spanner/spanner_create_instance_partition.go
Labels: api: spanner, samples

#4273 feat(securitymarksv2): Add Security Marks v2 Go Client Libraries/ Samples
  securitycenter/go.mod
  securitycenter/go.sum
  securitycenter/securitymarksv2/add_delete_security_marks.go
  securitycenter/securitymarksv2/add_security_marks.go
  securitycenter/securitymarksv2/assets_test.go
  securitycenter/securitymarksv2/delete_security_marks.go
Labels: samples

#4271 feat(iam): Add iam v2 Go client libraries/ samples
  securitycenter/go.mod
  securitycenter/iamv2/get_iam_policies.go
  securitycenter/iamv2/iam_policies_test.go
  securitycenter/iamv2/set_iam_policies.go
  securitycenter/iamv2/test_iam_permissions.go
Labels: api: iam, samples

#4297 feat: added secret manager team in codeowners
  .github/CODEOWNERS
Labels: samples
