Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2024-02, with the labels that each got.

#3760 fix(otel): simplify quota project config with GOOGLE_CLOUD_QUOTA_PROJECT
  opentelemetry/instrumentation/docker-compose.adc.yaml
  opentelemetry/instrumentation/docker-compose.creds.yaml
  opentelemetry/instrumentation/docker-compose.yaml
  opentelemetry/instrumentation/otel-collector-config.yaml
Labels: samples

#3769 fix(functions): fix contexttip test to use sync.Once instead of init()
  functions/tips/contexttip/context_tip.go
  functions/tips/contexttip/context_tip_test.go
  functions/tips/contexttip/go.mod
  functions/tips/contexttip/go.sum
Labels: api: cloudfunctions, samples

#3743 fix: use fully qualified module names.
  appengine/go11x/cloudsql/go.mod
  appengine/go11x/helloworld/go.mod
  appengine/go11x/tasks/handle_task/go.mod
  appengine/go11x/warmup/go.mod
  appengine_flexible/analytics/go.mod
  appengine_flexible/datastore/go.mod
  appengine_flexible/helloworld/go.mod
  appengine_flexible/pubsub/go.mod
  appengine_flexible/redis/go.mod
  appengine_flexible/static_files/go.mod
  appengine_flexible/storage/go.mod
  compute/quickstart/go.mod
  internal/gomodversiontest/go.mod
Labels: samples

#3776 fix(vertexai): bump SDK versions in go.mod to latest release
  vertexai/chat/go.mod
  vertexai/chat/go.sum
  vertexai/multimodal-multiple/go.mod
  vertexai/multimodal-multiple/go.sum
  vertexai/multimodal/go.mod
  vertexai/multimodal/go.sum
  vertexai/safety-settings-multimodal/go.mod
  vertexai/safety-settings-multimodal/go.sum
  vertexai/safety-settings/go.mod
  vertexai/safety-settings/go.sum
  vertexai/snippets/go.mod
  vertexai/snippets/go.sum
Labels: samples

#3761 feat(spanner): add samples for spanner opentelemetry instrumentation
  spanner/opentelemetry/go.mod
  spanner/opentelemetry/go.sum
  spanner/opentelemetry/spanner_opentelemetry_usage.go
Labels: api: spanner, samples

#3779 feat(vertexai): function calling
  vertexai/function-calling/functioncalling.go
  vertexai/function-calling/functioncalling_test.go
  vertexai/function-calling/go.mod
  vertexai/function-calling/go.sum
Labels: samples

#3784 fix: typo in token broker example
  auth/downscoping/token_broker.go
Labels: samples

#3789 feat(vertexai): model names gemini 1.0
  vertexai/chat/chat.go
  vertexai/chat/chat_test.go
  vertexai/function-calling/functioncalling_test.go
  vertexai/multimodal-multiple/multiple-multimodal.go
  vertexai/multimodal-multiple/multiple-multimodal_test.go
  vertexai/multimodal/multimodal.go
  vertexai/multimodal/multimodal_test.go
  vertexai/safety-settings-multimodal/safety-settings-multimodal.go
  vertexai/safety-settings-multimodal/safety-settings-multimodal_test.go
  vertexai/safety-settings/safety-settings.go
  vertexai/safety-settings/safety-settings_test.go
  vertexai/snippets/try_gemini.go
  vertexai/snippets/try_gemini_test.go
Labels: samples

#3778 feat(vertexai): token count
  vertexai/token-count/go.mod
  vertexai/token-count/go.sum
  vertexai/token-count/tokencount.go
  vertexai/token-count/tokencount_test.go
Labels: samples

#3797 chore(vertexai): consistent usage of context.Background
  vertexai/chat/chat.go
  vertexai/snippets/try_gemini.go
Labels: samples

#3771 chore(opentelemetry): update opentelemetry dependency, and handle non-fatal resource errors
  opentelemetry/instrumentation/app/go.mod
  opentelemetry/instrumentation/app/go.sum
  opentelemetry/instrumentation/app/main_test.go
  opentelemetry/instrumentation/docker-compose.yaml
  opentelemetry/trace/go.mod
  opentelemetry/trace/go.sum
  opentelemetry/trace/main.go
Labels: samples

#3801 chore(opentelemetry): simplify OpenTelemetry instrumentation logging sample
  opentelemetry/instrumentation/app/logger.go
  opentelemetry/instrumentation/docker-compose.yaml
  opentelemetry/instrumentation/otel-collector-config.yaml
Labels: samples

#3811 test(storage): use different bucket for KMS test
  storage/objects/objects_test.go
Labels: api: storage, samples

#3810 test(storage): fix error case for HMAC test
  storage/service_account/hmac/hmac_test.go
Labels: automerge, api: storage, samples
