Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2024-05, with the labels that each got.

#4112 feat(vertexai): pdf input
  vertexai/multimodal-pdf/go.mod
  vertexai/multimodal-pdf/go.sum
  vertexai/multimodal-pdf/pdf.go
  vertexai/multimodal-pdf/pdf_test.go
Labels: samples

#4111 feat(vertexai): multimodal audio
  vertexai/multimodal-audio/go.mod
  vertexai/multimodal-audio/go.sum
  vertexai/multimodal-audio/multimodalaudio.go
  vertexai/multimodal-audio/multimodalaudio_test.go
Labels: samples

#4119 fix(vertexai): Refactor the snippets sample
  vertexai/snippets/try_gemini.go
  vertexai/snippets/try_gemini_test.go
Labels: samples

#4118 fix(vertexai): Refactor the chat sample
  vertexai/chat/chat.go
  vertexai/chat/chat_test.go
Labels: samples

#4116 chore(vertexai): update Gemini samples to stable versions
  vertexai/function-calling/functioncalling.go
  vertexai/function-calling/functioncalling_test.go
  vertexai/multimodal-video/multimodalvideo.go
  vertexai/multimodal-video/multimodalvideo_test.go
  vertexai/multimodal/multimodal.go
  vertexai/multimodal/multimodal_test.go
  vertexai/safety-settings-multimodal/safety-settings-multimodal.go
  vertexai/safety-settings-multimodal/safety-settings-multimodal_test.go
  vertexai/safety-settings/safety-settings.go
  vertexai/safety-settings/safety-settings_test.go
  vertexai/token-count/tokencount.go
  vertexai/token-count/tokencount_test.go
Labels: samples

#4113 feat(vertextai): video with audio
  vertexai/multimodal-video-with-audio/go.mod
  vertexai/multimodal-video-with-audio/go.sum
  vertexai/multimodal-video-with-audio/multimodalvideoaudio.go
  vertexai/multimodal-video-with-audio/multimodalvideoaudio_test.go
Labels: samples

#4124 chore(fixit): remove redundant region tags
  functions/tips/lazy.go
  functions/tips/scope.go
  run/authentication/auth.go
  run/markdown-preview/editor/render.go
  run/system_package/graphviz.go
Labels: samples

#4125 chore(fixit): remove redundant region tags
  run/grpc-ping/connection.go
  run/grpc-ping/main.go
  run/grpc-ping/request.go
  run/grpc-ping/request_auth.go
  run/hello-broken/main.go
  run/helloworld/main.go
  run/image-processing/imagemagick/imagemagick.go
  run/image-processing/main.go
  run/logging-manual/main.go
  run/pubsub/main.go
Labels: samples

#4129 chore(fixit): remove duplicated samples
  storage/buckets/main.go
  storage/objects/main.go
Labels: samples

#4128 chore(fixit): remove unused iot samples
  iot/README.md
  iot/go.mod
  iot/go.sum
  iot/manager/README.md
  iot/manager/manager.go
  iot/manager/manager_test.go.deprecated
  iot/mqttsnippets/attach_detach_device.go
  iot/mqttsnippets/create_jwt.go
  iot/mqttsnippets/gateway_send_data.go
  iot/mqttsnippets/gateway_send_data_test.go.deprecated
  iot/mqttsnippets/main_test.go.deprecated
  iot/mqttsnippets/subscribe_gateway_device_topic.go
  iot/mqttsnippets/subscribe_gateway_device_topic_test.go.deprecated
Labels: samples

#4130 feat: add gemini code sample and test for text-only input
  vertexai/snippets/text_input.go
  vertexai/snippets/text_input_test.go
Labels: automerge, samples

#4001 test(testutil): add new function for creating a test bucket
  internal/testutil/storage_cleaner.go
  storage/buckets/buckets_test.go
Labels: samples

#4134 fix(cloudrun): remove unused region tags
  eventarc/generic/Dockerfile
  eventarc/pubsub/Dockerfile
  run/grpc-ping/Dockerfile
  run/grpc-server-streaming/Dockerfile
Labels: samples

#4121 feat(vertexai): system instruction
  vertexai/system-instruction/go.mod
  vertexai/system-instruction/go.sum
  vertexai/system-instruction/systeminstruction.go
  vertexai/system-instruction/systeminstruction_test.go
Labels: samples, api: vertex-ai

#4110 feat(vertexai): multimodal with all modalities
  vertexai/multimodal-all/go.mod
  vertexai/multimodal-all/go.sum
  vertexai/multimodal-all/multimodalall.go
  vertexai/multimodal-all/multimodalall_test.go
Labels: samples

#4136 feat(spanner): add samples for proto columns
  badfiles_test.go
  spanner/go.mod
  spanner/go.sum
  spanner/spanner_snippets/spanner/integration_test.go
  spanner/spanner_snippets/spanner/spanner_add_proto_column.go
  spanner/spanner_snippets/spanner/spanner_query_with_proto_parameter.go
  spanner/spanner_snippets/spanner/spanner_update_data_with_proto_column.go
  spanner/spanner_snippets/spanner/spanner_update_data_with_proto_column_using_dml.go
  spanner/spanner_snippets/spanner/testdata/protos/README.md
  spanner/spanner_snippets/spanner/testdata/protos/descriptors.pb
  spanner/spanner_snippets/spanner/testdata/protos/singer.pb.go
  spanner/spanner_snippets/spanner/testdata/protos/singer.proto
Labels: api: spanner, samples

#3742 feat(datastore): Datastore query profiling samples
  datastore/go.mod
  datastore/go.sum
  datastore/snippets/snippet_test.go
Labels: samples

#4000 test(all): remove all references to CleanBucket
  aiplatform/go.mod
  aiplatform/go.sum
  aiplatform/snippets/import_data_image_classification_test.go
  asset/go.mod
  asset/go.sum
  asset/quickstart/analyze-iam-policy-longrunning-gcs/main_test.go
  asset/quickstart/export-assets/main_test.go
  dataproc/go.mod
  dataproc/go.sum
  dataproc/quickstart/quickstart_test.go
  datastore/admin/datastore_admin_test.go
  datastore/go.mod
  datastore/go.sum
  dlp/go.mod
  dlp/go.sum
  dlp/snippets/inspect/inspect_gcs_send_to_scc_test.go
  dlp/snippets/inspect/inspect_gcs_with_sampling_test.go
  dlp/snippets/inspect/inspect_with_stored_infotype_test.go
  dlp/snippets/metadata/create_stored_infotype_test.go
  dlp/snippets/metadata/update_stored_infotype_test.go
  functions/functionsv2/imagemagick/go.mod
  functions/functionsv2/imagemagick/go.sum
  functions/functionsv2/imagemagick/imagemagick_test.go
  healthcare/fhir_test.go
  healthcare/go.mod
  healthcare/go.sum
  internal/testutil/storage_cleaner.go
  media/go.mod
  media/go.sum
  media/transcoder/transcoder_test.go
  storage/acl/acl_test.go
  storage/buckets/buckets_test.go
  storage/control_quickstart/main_test.go
  storage/go.mod
  storage/go.sum
  storage/notifications/notifications_test.go
  storage/objects/objects_test.go
  storage/retry/retry_test.go
  vision/detect/detect_test.go
  vision/go.mod
  vision/go.sum
Labels: samples

#4139 chore(vertexai): add region tag for tokencount
  vertexai/token-count/tokencount.go
Labels: samples

#4140 chore(vertexai): Add new region tag to Function Calling Sample
  vertexai/function-calling/functioncalling.go
Labels: samples

#4144 fix(vertexai): test name typos in error messages.
  vertexai/multimodal-audio/multimodalaudio_test.go
  vertexai/multimodal-pdf/pdf_test.go
Labels: samples

#4141 feat(compute): compute_ip_address_reserve_new_external sample
  compute/address/address_test.go
  compute/address/reserve_new_external.go
Labels: api: compute, samples

#4127 feat(vertexai): Elastic Text-Embedding Model demo.
  aiplatform/snippets/embeddings.go
  aiplatform/snippets/embeddings_test.go
  aiplatform/text-embeddings/embeddings.go
  aiplatform/text-embeddings/embeddings_test.go
Labels: samples

#4147 feat(vertexai): Add stream text sample
  vertexai/stream-text-basic/go.mod
  vertexai/stream-text-basic/go.sum
  vertexai/stream-text-basic/streamtextbasic.go
  vertexai/stream-text-basic/streamtextbasic_test.go
Labels: samples
