Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2025-07, with the labels that each got.

#5347 docs(bigquery): initial preview samples
  bigquery/go.mod
  bigquery/go.sum
  bigquery/snippets_preview/client/bigquery_client_usage.go
  bigquery/snippets_preview/client/integration_test.go
  bigquery/snippets_preview/dataset/bigquery_create_dataset.go
  bigquery/snippets_preview/dataset/bigquery_delete_dataset.go
  bigquery/snippets_preview/dataset/bigquery_list_datasets.go
  bigquery/snippets_preview/dataset/bigquery_update_dataset.go
  bigquery/snippets_preview/dataset/integration_test.go
  datacatalog/go.mod
  datacatalog/go.sum
Labels: automerge, api: bigquery, samples

#5353 genai: updated go sdk from 1.6.0 to 1.17.0 and fix broken test
  genai/content_cache/contentcache_create_with_txt_gcs_pdf.go
  genai/content_cache/contentcache_use_with_txt.go
  genai/controlled_generation/ctrlgen_with_enum_schema.go
  genai/controlled_generation/ctrlgen_with_nullable_schema.go
  genai/controlled_generation/ctrlgen_with_resp_schema.go
  genai/count_tokens/counttoken_compute_with_txt.go
  genai/count_tokens/counttoken_resp_with_txt.go
  genai/count_tokens/counttoken_with_txt.go
  genai/count_tokens/counttoken_with_txt_vid.go
  genai/go.mod
  genai/go.sum
  genai/text_generation/text_generation_examples_test.go
  genai/text_generation/textgen_code_with_pdf.go
  genai/text_generation/textgen_config_with_txt.go
  genai/text_generation/textgen_sys_instr_with_txt.go
  genai/text_generation/textgen_transcript_with_gcs_audio.go
  genai/text_generation/textgen_with_gcs_audio.go
  genai/text_generation/textgen_with_multi_img.go
  genai/text_generation/textgen_with_mute_video.go
  genai/text_generation/textgen_with_txt.go
  genai/text_generation/textgen_with_txt_stream.go
  genai/text_generation/textgen_with_video.go
  genai/text_generation/textgen_with_youtube_video.go
  genai/tools/tools_func_desc_with_txt.go
  genai/tools/tools_google_search_with_txt.go
Labels: automerge, samples

#5355 chore: remove flakybot configuration (long retired)
  .github/flakybot.yaml
Labels: samples
