Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2025-04, with the labels that each got.

#5239 chore: remove old region tag
  docs/appengine/datastore/entities/overview.go
Labels: samples

#5231 feat(storage): add samples and tests for bucket soft delete (get, set, disable)
  storage/buckets/buckets_test.go
  storage/buckets/disable_soft_delete_policy.go
  storage/buckets/get_soft_delete_policy.go
  storage/buckets/set_soft_delete_policy.go
Labels: api: storage, samples

#5227 feat(parametermanager): Added quickstart samples for both global and regional
  go.work
  parametermanager/README.md
  parametermanager/go.mod
  parametermanager/go.sum
  parametermanager/quickstart/quickstart.go
  parametermanager/regional_quickstart/regional_quickstart.go
Labels: samples

#5238 feat(spanner): add samples for setting spanner isolation levels
  spanner/go.mod
  spanner/go.sum
  spanner/spanner_snippets/spanner/integration_test.go
  spanner/spanner_snippets/spanner/spanner_isolation_level.go
Labels: api: spanner, samples

#5244 chore: remove 1.X samples
  go.work
  vertexai/batch-predict/go.sum
  vertexai/chat/chat.go
  vertexai/chat/chat_test.go
  vertexai/chat/go.mod
  vertexai/chat/go.sum
  vertexai/context-caching/contextcaching_delete.go
  vertexai/context-caching/contextcaching_list.go
  vertexai/context-caching/contextcaching_test.go
  vertexai/context-caching/contextcaching_update.go
  vertexai/context-caching/contextcaching_use.go
  vertexai/context-caching/go.mod
  vertexai/context-caching/go.sum
  vertexai/controlled-generation/controlledgen_mime_type.go
  vertexai/controlled-generation/controlledgen_mime_type_test.go
  vertexai/controlled-generation/controlledgen_schema.go
  vertexai/controlled-generation/controlledgen_schema2.go
  vertexai/controlled-generation/controlledgen_schema3.go
  vertexai/controlled-generation/controlledgen_schema4.go
  vertexai/controlled-generation/controlledgen_schema_test.go
  vertexai/controlled-generation/go.sum
  vertexai/multimodal-all/go.mod
  vertexai/multimodal-all/go.sum
  vertexai/multimodal-all/multimodalall.go
  vertexai/multimodal-all/multimodalall_test.go
  vertexai/multimodal-audio/go.mod
  vertexai/multimodal-audio/go.sum
  vertexai/multimodal-audio/multimodalaudio.go
  vertexai/multimodal-audio/multimodalaudio_test.go
  vertexai/multimodal-multiple/go.mod
  vertexai/multimodal-multiple/go.sum
  vertexai/multimodal-multiple/multiple-multimodal.go
  vertexai/multimodal-multiple/multiple-multimodal_test.go
  vertexai/multimodal-pdf/go.mod
  vertexai/multimodal-pdf/go.sum
  vertexai/multimodal-pdf/pdf.go
  vertexai/multimodal-pdf/pdf_test.go
  vertexai/multimodal-video/go.mod
  vertexai/multimodal-video/go.sum
  vertexai/multimodal-video/multimodalvideo.go
  vertexai/multimodal-video/multimodalvideo_test.go
  vertexai/multimodal/go.mod
  vertexai/multimodal/go.sum
  vertexai/multimodal/multimodal.go
  vertexai/multimodal/multimodal_test.go
  vertexai/safety-settings-multimodal/go.mod
  vertexai/safety-settings-multimodal/go.sum
  vertexai/safety-settings-multimodal/safety-settings-multimodal.go
  vertexai/safety-settings-multimodal/safety-settings-multimodal_test.go
  vertexai/system-instruction/go.mod
  vertexai/system-instruction/go.sum
  vertexai/system-instruction/systeminstruction.go
  vertexai/system-instruction/systeminstruction_test.go
Labels: samples

#5243 feat(storage): add samples and tests for object soft delete (list, list versions, restore)
  storage/go.mod
  storage/go.sum
  storage/objects/list_soft_deleted_objects.go
  storage/objects/list_soft_deleted_versions_of_object.go
  storage/objects/objects_test.go
  storage/objects/restore_soft_deleted_object.go
Labels: api: storage, samples

#5256 feat(parametermanager): Added samples for create global parameter version
  parametermanager/create_param_version.go
  parametermanager/create_param_version_with_secret.go
  parametermanager/create_structured_param_version.go
  parametermanager/go.mod
  parametermanager/go.sum
  parametermanager/parametermanager_test.go
Labels: samples

#5258 feat(parametermanager): Added samples for get and list global parameters
  parametermanager/get_param.go
  parametermanager/list_param.go
  parametermanager/parametermanager_test.go
Labels: samples

#5268 feat(genai sdk): code samples
  genai/content_cache/content_cache_test.go
  genai/content_cache/contentcache_create_with_txt_gcs_pdf.go
  genai/content_cache/contentcache_delete.go
  genai/content_cache/contentcache_update.go
  genai/content_cache/contentcache_use_with_txt.go
  genai/controlled_generation/controlled_generation_examples_test.go
  genai/controlled_generation/ctrlgen_with_enum_schema.go
  genai/controlled_generation/ctrlgen_with_nullable_schema.go
  genai/controlled_generation/ctrlgen_with_resp_schema.go
  genai/count_tokens/count_tokens_examples_test.go
  genai/count_tokens/counttoken_compute_with_txt.go
  genai/count_tokens/counttoken_resp_with_txt.go
  genai/count_tokens/counttoken_with_txt.go
  genai/count_tokens/counttoken_with_txt_vid.go
  genai/go.mod
  genai/go.sum
  genai/text_generation/text_generation_examples_test.go
  genai/text_generation/textgen_code_with_pdf.go
  genai/text_generation/textgen_config_with_txt.go
  genai/text_generation/textgen_sys_instr_with_txt.go
  genai/text_generation/textgen_transcript_with_gcs_audio.go
  genai/text_generation/textgen_with_gcs_audio.go
  genai/text_generation/textgen_with_multi_img.go
  genai/text_generation/textgen_with_mute_video.go
  genai/text_generation/textgen_with_txt_img.go
  genai/text_generation/textgen_with_txt_stream.go
  genai/text_generation/textgen_with_video.go
  genai/text_generation/textgen_with_youtube_video.go
  genai/tools/tools_code_exec_with_txt.go
  genai/tools/tools_examples_test.go
  genai/tools/tools_func_desc_with_txt.go
  genai/tools/tools_google_search_with_txt.go
  go.work
Labels: samples

#5246 feat(spanner): adding sample for the pre splitting feature
  spanner/spanner_snippets/spanner/integration_test.go
  spanner/spanner_snippets/spanner/spanner_database_add_split_points.go
Labels: samples

#5269 feat(storage): update TestListSoftDeletedVersionsOfObject to store 2 objects
  storage/objects/objects_test.go
Labels: api: storage, samples

#5287 Revert "feat(firestore): add new sample for sessions"
  getting-started/sessions/go.mod
  getting-started/sessions/go.sum
  getting-started/sessions/main.go
  getting-started/sessions/main_test.go
Labels: api: firestore, samples

#5257 fix(parametermanager): Added samples for create regional parameter and parameter version
  parametermanager/go.mod
  parametermanager/go.sum
  parametermanager/list_param.go
  parametermanager/parametermanager_test.go
  parametermanager/regional_samples/create_regional_param.go
  parametermanager/regional_samples/create_regional_param_version.go
  parametermanager/regional_samples/create_regional_param_version_with_secret.go
  parametermanager/regional_samples/create_structured_regional_param.go
  parametermanager/regional_samples/create_structured_regional_param_version.go
  parametermanager/regional_samples/regional_parametermanager_test.go
Labels: samples

#5255 feat(parametermanager): Added samples for create global parameter
  parametermanager/create_param.go
  parametermanager/create_structured_param.go
  parametermanager/parametermanager_test.go
Labels: samples

#5253 feat(parametermanager): Added samples for delete, enable and disable parameter and parameter version
  parametermanager/delete_param.go
  parametermanager/delete_param_version.go
  parametermanager/disable_param_vesion.go
  parametermanager/enable_param_version.go
  parametermanager/go.mod
  parametermanager/go.sum
  parametermanager/parametermanager_test.go
Labels: samples

#5254 feat(parametermanager): Added regional samples for delete, enable & disable parameter and parameter version
  parametermanager/go.mod
  parametermanager/go.sum
  parametermanager/regional_samples/delete_regional_param.go
  parametermanager/regional_samples/delete_regional_param_version.go
  parametermanager/regional_samples/disable_regional_param_vesion.go
  parametermanager/regional_samples/enable_regional_param_version.go
  parametermanager/regional_samples/regional_parametermanager_test.go
Labels: samples

#5290 feat(pubsub): add message transform samples
  pubsub/go.mod
  pubsub/go.sum
  pubsub/v1samples/subscriptions/create_message_transforms.go
  pubsub/v1samples/subscriptions/subscription_test.go
  pubsub/v1samples/topics/create_topic_message_transforms.go
  pubsub/v1samples/topics/topics_test.go
Labels: api: pubsub, samples

#5260 feat(parametermanager): Added samples for get, list and render parameter & parameter version
  parametermanager/go.mod
  parametermanager/go.sum
  parametermanager/regional_samples/get_regional_param.go
  parametermanager/regional_samples/get_regional_param_version.go
  parametermanager/regional_samples/list_regional_param.go
  parametermanager/regional_samples/list_regional_param_version.go
  parametermanager/regional_samples/regional_parametermanager_test.go
  parametermanager/regional_samples/render_regional_param_version.go
Labels: samples

#5262 feat(parametermanager): Added samples for kms_key in regional parameter
  parametermanager/go.mod
  parametermanager/go.sum
  parametermanager/regional_samples/create_regional_param_with_kms_key.go
  parametermanager/regional_samples/regional_parametermanager_test.go
  parametermanager/regional_samples/remove_regional_param_kms_key.go
  parametermanager/regional_samples/update_regional_param_kms_key.go
Labels: samples

#5271 feat(modelarmor): Added snippets for create and delete template
  .github/CODEOWNERS
  .github/blunderbuss.yml
  go.work
  modelarmor/create_template.go
  modelarmor/delete_template.go
  modelarmor/go.mod
  modelarmor/go.sum
  modelarmor/modelarmor_test.go
Labels: samples

#5261 feat(parametermanager): Added samples for kms_key in global parameter
  parametermanager/create_param_with_kms_key.go
  parametermanager/parametermanager_test.go
  parametermanager/remove_param_kms_key.go
  parametermanager/update_param_kms_key.go
Labels: samples

#5245 feat(workflows): add samples for workflow execution
  go.work
  workflows/execute_workflow.go
  workflows/execute_workflow_test.go
  workflows/execute_workflow_with_arguments.go
  workflows/execute_workflow_with_arguments_test.go
  workflows/go.mod
  workflows/go.sum
  workflows/myFirstWorkflow.yaml
  workflows/test_functions.go
Labels: samples, api: workflows

#5297 feat(workflows): add samples for workflow execution
  workflows/execute_workflow.go
  workflows/execute_workflow_test.go
  workflows/execute_workflow_with_arguments.go
  workflows/execute_workflow_with_arguments_test.go
Labels: samples

#5295 fix(helloworld): use consistent casing in FROM and AS
  run/helloworld/Dockerfile
Labels: samples

#5298 feat: update gemini mode name
  genai/content_cache/contentcache_create_with_txt_gcs_pdf.go
  vertexai/batch-predict/gemini_batch_predict_bq.go
  vertexai/batch-predict/gemini_batch_predict_gcs.go
  vertexai/context-caching/contextcaching_create.go
  vertexai/context-caching/contextcaching_test.go
  vertexai/controlled-generation/controlledgen_schema6.go
  vertexai/controlled-generation/controlledgen_schema_enum.go
  vertexai/controlled-generation/controlledgen_schema_test.go
  vertexai/function-calling/functioncalling.go
  vertexai/function-calling/functioncalling_basic.go
  vertexai/function-calling/functioncalling_parallel.go
  vertexai/function-calling/functioncalling_test.go
  vertexai/multimodal-video-with-audio/multimodalvideoaudio.go
  vertexai/multimodal-video-with-audio/multimodalvideoaudio_test.go
  vertexai/safety-settings/safety-settings.go
  vertexai/safety-settings/safety-settings_test.go
  vertexai/snippets/gemini_translate.go
  vertexai/snippets/text_input.go
  vertexai/snippets/try_gemini.go
  vertexai/snippets/try_gemini_test.go
  vertexai/stream-multimodality-basic/streammultimodalitybasic_test.go
  vertexai/stream-text-basic/streamtextbasic_test.go
  vertexai/token-count/tokencount.go
  vertexai/token-count/tokencount_multimodal.go
  vertexai/token-count/tokencount_test.go
Labels: samples

#5274 feat(modelarmor): Added snippets for create template with basic sdp
  modelarmor/create_template_with_basic_sdp.go
  modelarmor/modelarmor_test.go
Labels: samples

#5275 feat(modelarmor): Added snippets for create template with advance sdp filter
  modelarmor/create_template_with_advanced_sdp.go
  modelarmor/go.mod
  modelarmor/go.sum
  modelarmor/modelarmor_test.go
Labels: samples

#5301 fix(workflows): add main func and re-organize files
  go.work
  workflows/executions/execute_workflow.go
  workflows/executions/execute_workflow_test.go
  workflows/executions/execute_workflow_with_arguments.go
  workflows/executions/execute_workflow_with_arguments_test.go
  workflows/executions/go.mod
  workflows/executions/go.sum
  workflows/executions/main.go
  workflows/executions/myFirstWorkflow.yaml
  workflows/executions/test_functions.go
Labels: samples, api: workflows

#5303 docs(genai): update region tag
  genai/content_cache/contentcache_delete.go
Labels: samples

#5304 fix(cloudrun): remove unnecessary comment
  run/pubsub/main.go
Labels: samples

#5305 chore(cloudrun): rename new region tag cloudrun_imageproc_imagemagick_dockerfile_go
  run/image-processing/Dockerfile
Labels: samples
