Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2025-03, with the labels that each got.

#5201 chore(gae): rename region "securing_urls"
  docs/appengine/taskqueue/app.yaml
Labels: samples

#5203 fix(gae): delete old region tags from helloworld
  appengine/go11x/helloworld/helloworld.go
Labels: samples

#5208 fix(gae): update deprecated package ioutil
  docs/appengine/storage/app.go
Labels: samples

#5207 feat(vision): add region tag "vision_imports"
  vision/detect/detect.go
Labels: api: vision, samples

#5204 chore(gae): delete old region tag "intro"
  docs/appengine/datastore/index.go
Labels: samples

#5197 fix(gae): delete old region tags from transactions.go
  docs/appengine/datastore/transactions/transactions.go
Labels: samples

#5168 chore(gae): migrate region tags at docs/appengine/mail/mail.go
  docs/appengine/mail/app.yaml
  docs/appengine/mail/mail.go
Labels: samples

#5192 chore(gae): rename regions from unittest/aest*.go
  docs/appengine/tools/unittest/aetest.go
  docs/appengine/tools/unittest/aetest2.go
Labels: samples

#5185 chore(tts): migrate region tag and update deprecated ioutil package
  docs/appengine/mail/sendgrid/sendgrid.go
  docs/go.mod
  docs/go.sum
  texttospeech/synthesize_speech/audio_profile.go
Labels: samples

#5209 fix(storage): update storage codeowners team
  .github/CODEOWNERS
Labels: api: storage, samples

#5193 feat(bigquery): add samples for control access 1/3
  bigquery/bigquery_access_quickstart/grant_access_table_or_view.go
  bigquery/bigquery_access_quickstart/grant_access_table_or_view_test.go
  bigquery/bigquery_access_quickstart/grant_access_to_dataset.go
  bigquery/bigquery_access_quickstart/grant_access_to_dataset_test.go
  bigquery/bigquery_access_quickstart/test_functions.go
Labels: api: bigquery, samples

#5194 feat(bigquery): add samples for control access 2/3
  bigquery/bigquery_access_quickstart/revoke_access_table_or_view.go
  bigquery/bigquery_access_quickstart/revoke_access_table_or_view_test.go
  bigquery/bigquery_access_quickstart/revoke_access_to_dataset.go
  bigquery/bigquery_access_quickstart/revoke_access_to_dataset_test.go
Labels: api: bigquery, samples

#5200 chore(gae): delete unused sample helloworld from getting-started/helloworld
  getting-started/helloworld/app.yaml
  getting-started/helloworld/helloworld.go
Labels: samples

#5210 chore(tts): delete old region texttospeech_audio_profile
  texttospeech/synthesize_speech/audio_profile.go
Labels: samples

#5213 chore(endpoints): start migrating region endpoints_esp
  endpoints/getting-started/deployment.yaml
Labels: samples, api: endpoints

#5214 chore(cloudrun): migrate region cloudrun_system_package_ubuntu
  run/system_package/Dockerfile
Labels: api: run, samples

#5215 chore(cloudrun): migrate region cloudrun_broken_dockerfile
  run/hello-broken/Dockerfile
Labels: samples

#5219 chore(endpoints): delete old region tag "endpoints_esp"
  endpoints/getting-started/deployment.yaml
Labels: samples, api: endpoints

#5177 feat(parametermanager): created folder to add samples
  .github/CODEOWNERS
  .github/blunderbuss.yml
  parametermanager/README.md
Labels: samples

#5195 feat(bigquery): add samples for control access 3/3
  bigquery/bigquery_access_quickstart/view_dataset_access_policy.go
  bigquery/bigquery_access_quickstart/view_dataset_access_policy_test.go
  bigquery/bigquery_access_quickstart/view_table_or_view_access_policy.go
  bigquery/bigquery_access_quickstart/view_table_or_view_access_policy_test.go
Labels: api: bigquery, samples

#5220 chore(cloudrun): delete old region cloudrun_broken_dockerfile
  run/hello-broken/Dockerfile
Labels: samples

#5221 chore(cloudrun): migrate region "cloudrun_helloworld_dockerfile"
  run/helloworld/Dockerfile
Labels: samples

#5222 chore(cloudrun): migrate region tag "cloudrun_imageproc_dockerfile_imagemagick"
  run/image-processing/Dockerfile
Labels: samples

#5223 chore(cloudrun): delete old region tag "cloudrun_system_package_ubuntu"
  run/system_package/Dockerfile
Labels: samples

#5226 chore(cloudrun): delete old region tag "cloudrun_helloworld_dockerfile"
  run/helloworld/Dockerfile
Labels: samples

#5212 chore(gae): delete unused samples from docs/appengine/storage/*
  docs/appengine/storage/README.md
  docs/appengine/storage/app.go
  docs/appengine/storage/app.yaml
  docs/go.mod
Labels: samples
