Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2025-05, with the labels that each got.

#5180 fix: code in tests should use log.Print*
  internal/cloudrunci/cloudrunci.go
  run/testing/sigterm_handler.e2e_test.go
Labels: samples

#5307 fix(cloudrun): remove old region cloudrun_imageproc_dockerfile_imagemagick
  run/image-processing/Dockerfile
Labels: samples

#5308 chore(translate): rename and remove unused region tags.
  translate/v3/translate_text.go
Labels: api: translate, samples

#5285 feat(modelarmor): Added snippets for sanitize model response with user prompt
  modelarmor/modelarmor_test.go
  modelarmor/sanitize_model_response_with_user_prompt.go
Labels: samples

#5311 fix(cloudrun): rename PubSubMessage struct and add a more descriptive link
  run/pubsub/main.go
Labels: samples

#5312 fix(firestore): remove deprecated library firestore-gorilla-sessions
  getting-started/sessions/go.mod
  getting-started/sessions/go.sum
  getting-started/sessions/main.go
  getting-started/sessions/main_test.go
Labels: api: firestore, samples

#5313 chore: Removing dee-infra from CODEOWNERS and Blunderbuss config files
  .github/CODEOWNERS
  .github/blunderbuss.yml
Labels: samples

#5314 Revert "chore(all): update module github.com/aws/aws-sdk-go to v1.55.7"
  storage/go.mod
  storagetransfer/go.mod
Labels: samples

#5309 fix(pubsub): update message transform samples
  pubsub/v1samples/subscriptions/create_message_transforms.go
  pubsub/v1samples/topics/create_topic_message_transforms.go
Labels: api: pubsub, samples

#5259 feat(parametermanager): Added samples for get, list and render global parameter version
  parametermanager/get_param_version.go
  parametermanager/list_param_versions.go
  parametermanager/parametermanager_test.go
  parametermanager/regional_samples/regional_parametermanager_test.go
  parametermanager/render_param_version.go
Labels: samples

#5315 chore: removes old and unused sample app
  getting-started/gopher-run/Dockerfile
  getting-started/gopher-run/app.yaml
  getting-started/gopher-run/cmd/main.go
  getting-started/gopher-run/cmd/training.sh
  getting-started/gopher-run/generator/generator.go
  getting-started/gopher-run/generator/generator_test.go
  getting-started/gopher-run/go.mod
  getting-started/gopher-run/go.sum
  getting-started/gopher-run/leaderboard/leaderboard.go
  go.work
Labels: samples

#5317 feat(genaisdk): update contentcache to v1 from v1beta
  genai/content_cache/contentcache_create_with_txt_gcs_pdf.go
  genai/content_cache/contentcache_delete.go
  genai/content_cache/contentcache_update.go
  genai/content_cache/contentcache_use_with_txt.go
Labels: samples

#5286 feat(modelarmor): #8 Added snippets for screen pdf file
  badfiles_test.go
  modelarmor/modelarmor_test.go
  modelarmor/screen_pdf_file.go
  modelarmor/test_sample.pdf
Labels: samples, api: modelarmor

#5319 fix(spanner): update sample to include adding split point with ExpireTime set
  spanner/spanner_snippets/spanner/spanner_database_add_split_points.go
Labels: api: spanner, samples

#5283 feat(modelarmor): #7 Added snippets for sanitization user prompt
  modelarmor/modelarmor_test.go
  modelarmor/sanitize_user_prompt.go
Labels: samples, api: modelarmor

#5273 feat(modelarmor): #9 Added snippets for create template with labels and metadata
  modelarmor/create_template_with_labels.go
  modelarmor/create_template_with_metadata.go
  modelarmor/modelarmor_test.go
Labels: samples, api: modelarmor

#5324 fix(firestore): avoid URI validation for preventing duplicate requests
  getting-started/sessions/main.go
Labels: api: firestore, samples

#5291 feat(cloudrun): add sample for service-to-service auth
  go.work
  run/service-auth/go.mod
  run/service-auth/go.sum
  run/service-auth/main.go
  run/service-auth/receive.go
  run/service-auth/receive_test.go
Labels: samples

#5299 feat: add code samples for Connect Gateway API
  .github/CODEOWNERS
  .github/blunderbuss.yml
  connectgateway/get_namespace.go
  connectgateway/get_namespace_test.go
  connectgateway/go.mod
  connectgateway/go.sum
  go.work
Labels: samples, api: connectgateway

#5276 feat(modelarmor): #10 Added snippets for get template and list templates
  modelarmor/get_template.go
  modelarmor/list_templates.go
  modelarmor/list_templates_with_filter.go
  modelarmor/modelarmor_test.go
Labels: samples, api: modelarmor

#5332 fix(translate): update translate text sample for consistency duty
  translate/snippet_test.go
  translate/text.go
Labels: api: translate, samples
