Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2025-01, with the labels that each got.

#4933 fix(cloudrun): delete old region tag run_system_package_ubuntu
  run/system_package/Dockerfile
Labels: samples

#4932 fix(speech): delete old region tag "imports"
  speech/snippets/model_selection.go
Labels: api: speech, samples

#4934 fix(job): delete old region tag histogram_search
  jobs/v3/howto/histogram_search_sample.go
Labels: samples

#5005 fix(run): delete old region tag broken_dockerfile
  run/hello-broken/Dockerfile
Labels: api: run, samples

#5019 fix(language): migrate imports region tag step 1
  language/analyze/analyze.go
Labels: api: language, samples

#5035 fix(language): delete old region tag "imports"
  language/analyze/analyze.go
Labels: api: language, samples

#5000 fix(endpoints): add _go suffix to regions
  endpoints/getting-started/k8s/esp_echo_http.yaml
Labels: samples, api: endpoints

#5018 fix: disable flakybot reporting
  testing/kokoro/system_tests.sh
Labels: samples

#5036 chore(many): rename Golang to Go
  CONTRIBUTING.md
  appengine/go11x/tasks/handle_task/Dockerfile
  appengine_flexible/go115_and_earlier/websockets/static/index.html
  appengine_flexible/websockets/static/index.html
  bigtable/helloworld/main.go
  cloudsql/mysql/database-sql/Dockerfile
  cloudsql/postgres/database-sql/Dockerfile
  cloudsql/sqlserver/database-sql/Dockerfile
  eventarc/audit_storage/Dockerfile
  eventarc/generic/Dockerfile
  eventarc/pubsub/Dockerfile
  getting-started/gopher-run/Dockerfile
  memorystore/redis/cloud_run_deployment/Dockerfile
  opentelemetry/instrumentation/app/logger.go
  run/grpc-ping/Dockerfile
  run/grpc-ping/connection.go
  run/grpc-server-streaming/Dockerfile
  run/hello-broken/Dockerfile
  run/helloworld/Dockerfile
  run/image-processing/Dockerfile
  run/logging-manual/Dockerfile
  run/markdown-preview/editor/Dockerfile
  run/markdown-preview/renderer/Dockerfile
  run/pubsub/Dockerfile
  run/sigterm-handler/Dockerfile
  run/system_package/Dockerfile
  testing/docker/README.md
  testing/kokoro/configure_cloudsql.bash
Labels: samples

#5069 fix(job): delete old region "create_job"
  jobs/v3/howto/basic_job_sample.go
Labels: samples

#5057 fix(gae): migrate region example to new one
  appengine_flexible/static_files/static/main.css
Labels: samples

#5046 fix(appengine): delete old region tags
  endpoints/getting-started/k8s/esp_echo_http.yaml
Labels: api: appengine, samples

#5037 fix(gae): add new region tags with "gae_storage_" prefix
  docs/appengine/storage/app.go
Labels: samples

#5004 fix(run): remove old region tag pubsub_dockerfile
  run/pubsub/Dockerfile
Labels: api: run, samples

#4982 fix(job): remove old region tags
  jobs/v3/howto/location_based_search_sample.go
Labels: samples

#4894 chore(secretmanager): add optional argument ttl to createSecret
  secretmanager/create_secret_ttl.go
  secretmanager/go.mod
  secretmanager/secretmanager_test.go
Labels: api: secretmanager, samples

#5079 fix(run): go mod tidy
  run/custom-metrics/go.sum
Labels: api: run, samples

#5083 fix(run): align schemas url versions
  run/custom-metrics/main.go
Labels: api: run, samples

#5085 fix(run): align schemas url versions
  run/custom-metrics/main.go
  run/custom-metrics/main_test.go
Labels: api: run, samples

#5077 fix(compute): Renaming region tag to proper name
  compute/disks/consistency_group_clone.go
Labels: api: compute, samples

#5093 chore(all): minimum supported version is now go 1.22
  appengine/go11x/cloudsql/app.yaml
  appengine/go11x/helloworld/app.yaml
  appengine/go11x/pubsub/authenicated_push/app.yaml
  appengine/go11x/tasks/handle_task/app.yaml
  appengine/go11x/warmup/app.yaml
  functions/security/security_system_test.go
  testing/kokoro/earliest-version.cfg
Labels: samples

#5076 chore(compute): Minor updates to regional consistency group listing
  compute/disks/consistency_group_list.go
  compute/disks/disks_test.go
Labels: api: compute, samples

#5095 fix: update go.work to match minimum 1.22
  go.work
Labels: samples

#5099 fix(gae): add "gae_datastore" prefix
  docs/appengine/datastore/entities/entities.go
Labels: samples

#5097 fix(gae): delete old region tags
  docs/appengine/storage/app.go
Labels: samples

#5094 fix(gae): migrate region "deferred_tasks"
  docs/appengine/taskqueue/push/defer.go
Labels: samples

#5088 fix(gae): add gae_search prefix to all regions tags
  docs/appengine/search/search.go
Labels: samples

#5090 fix(securitycenter): issues related to flaky tests in SHA & ETD
  securitycenter/go.mod
  securitycenter/go.sum
  securitycenter/management_api/create_security_health_analytics_custom_module.go
  securitycenter/management_api/event_threat_detection/create_event_threat_detection_custom_module.go
  securitycenter/management_api/event_threat_detection/event_threat_detection_custom_module_test.go
  securitycenter/management_api/security_health_analytics_custom_module_test.go
Labels: api: securitycenter, samples

#5098 fix(gae): add "gae_" prefix
  docs/appengine/taskqueue/pull/taskqueue_pull.go
Labels: samples

#5086 chore: bump Go Connector to v1.14.0
  cloudsql/mysql/database-sql/Dockerfile
  cloudsql/mysql/database-sql/cmd/functions/functions.go
  cloudsql/mysql/database-sql/go.mod
  cloudsql/mysql/database-sql/go.sum
  cloudsql/postgres/database-sql/Dockerfile
  cloudsql/postgres/database-sql/go.mod
  cloudsql/postgres/database-sql/go.sum
  cloudsql/sqlserver/database-sql/Dockerfile
  cloudsql/sqlserver/database-sql/cmd/functions/functions.go
  cloudsql/sqlserver/database-sql/go.mod
  cloudsql/sqlserver/database-sql/go.sum
Labels: samples

#5071 feat(spanner): add change streams transaction exclusion sample
  spanner/spanner_snippets/spanner/integration_test.go
  spanner/spanner_snippets/spanner/spanner_change_streams_txn_exclusion.go
Labels: api: spanner, samples

#5103 chore(deps): bump Cloud SQL Go Connector to v1.14.1
  cloudsql/mysql/database-sql/go.mod
  cloudsql/mysql/database-sql/go.sum
  cloudsql/postgres/database-sql/go.mod
  cloudsql/postgres/database-sql/go.sum
  cloudsql/sqlserver/database-sql/go.mod
  cloudsql/sqlserver/database-sql/go.sum
Labels: samples

#5106 chore(gae): migrate regions indexes.go
  docs/appengine/datastore/indexes/indexes.go
Labels: samples

#5105 chore(gae): migrate region taskqueue_host
  docs/appengine/taskqueue/taskqueue.go
Labels: samples

#5102 fix(gae): delete old region tags
  docs/appengine/datastore/entities/entities.go
Labels: samples

#5104 chore(gae): rename regions taskqueue.go
  docs/appengine/taskqueue/taskqueue.go
Labels: samples

#5109 fix(gae): delete old region taskqueue_host
  docs/appengine/taskqueue/taskqueue.go
Labels: samples

#4845 feat(spanner): add spanner sample snippet for creating asymmetric autoscaling instance
  spanner/spanner_snippets/spanner/integration_test.go
  spanner/spanner_snippets/spanner/spanner_create_instance_with_asymmetric_autoscaling.go
Labels: api: spanner, samples

#5116 chore(endpoints): migrate region "swagger" from openapi-appengine.yaml
  endpoints/getting-started/openapi-appengine.yaml
Labels: samples, api: endpoints

#5115 chore(endpoints): migrate region "swagger" from openapi.yaml
  endpoints/getting-started/openapi.yaml
Labels: samples, api: endpoints

#5108 chore(gae): migrate region tags from projectionqueries.go
  docs/appengine/datastore/projectionqueries/projectionqueries.go
Labels: samples

#5119 fix(gae): amend region tag renaming "gae_grouping_grouping"
  docs/appengine/datastore/projectionqueries/projectionqueries.go
Labels: samples

#5120 chore(storage): correct typo in comment
  storage/objects/generate_v4_put_object_signed_url.go
Labels: api: storage, samples
