Repository GoogleCloudPlatform/golang-samples, pull requests merged in 2025-02, with the labels that each got.

#5122 chore(endpoints): remove old region "esp" at endpoints/getting-started/deployment.yaml
  endpoints/getting-started/deployment.yaml
Labels: samples, api: endpoints

#5113 fix(cloudrun): delete old region tag run_helloworld_dockerfile
  run/helloworld/Dockerfile
Labels: samples

#5111 chore(gae): delete old region tags from indexes.go
  docs/appengine/datastore/indexes/indexes.go
Labels: samples

#5112 chore(gae): delete unused region tags from static_files .css
  appengine_flexible/go115_and_earlier/static_files/static/main.css
  appengine_flexible/static_files/static/main.css
Labels: samples

#5117 fix(bigquery): rename file that accidentally has two periods
  bigquery/snippets/routine/bigquery_get_routine.go
Labels: api: bigquery, samples

#5123 feat(pubsub): add kafka ingestion, azure ingestion samples
  go.work
  pubsub/go.mod
  pubsub/go.sum
  pubsub/v1samples/topics/create_topic_aws_msk_ingestion.go
  pubsub/v1samples/topics/create_topic_azure_event_hubs_ingestion.go
  pubsub/v1samples/topics/create_topic_confluent_cloud_ingestion.go
  pubsub/v1samples/topics/topics_test.go
Labels: api: pubsub, samples

#5118 chore(cloudrun): migrate region "cloudrun_pubsub_dockerfile" from run/pubsub/Dockerfile
  run/pubsub/Dockerfile
Labels: samples

#5126 chore(cloudrun): delete old region tag "cloudrun_pubusub_dockerfile"
  run/pubsub/Dockerfile
Labels: samples

#5129 chore(gae): migrate region tags from docs/appengine/modules/module.go
  docs/appengine/modules/module.go
Labels: samples

#5130 chore(gae): migrate region tags from docs/appengine/datastore/indexes/index.yaml
  docs/appengine/datastore/indexes/index.yaml
Labels: samples

#5132 chore(gae): delete old regions from "../indexes/index.yaml"
  docs/appengine/datastore/indexes/index.yaml
Labels: samples

#5134 chore(profiler): delete unused region tag "hotmid"
  profiler/hotmid/main.go
Labels: api: cloudprofiler, samples

#5135 chore(gae): migrate region "import" from ../helloworld/helloworld.go
  appengine/go11x/helloworld/helloworld.go
Labels: samples

#5136 chore(endpoints): delete old region tag "swagger"
  endpoints/getting-started/openapi-appengine.yaml
Labels: samples, api: endpoints

#5137 chore(endpoints): delete old region tag "swagger"
  endpoints/getting-started/openapi.yaml
Labels: samples, api: endpoints

#5142 chore(gae): delete old region "import" from ../helloworld/helloworld.go
  appengine/go11x/helloworld/helloworld.go
Labels: samples

#5138 feat(cloud-sql): add lazy refresh for csql: mysql, sql server and postgres
  cloudsql/mysql/database-sql/connect_connector.go
  cloudsql/mysql/database-sql/connect_connector_iam_authn.go
  cloudsql/postgres/database-sql/connect_connector.go
  cloudsql/postgres/database-sql/connect_connector_iam_authn.go
  cloudsql/sqlserver/database-sql/connect_connector.go
Labels: api: cloudsql, samples

#4652 fix(storage): update practices from deprecated ioutil to io
  storage/objects/download_public_file.go
Labels: api: storage, samples

#5147 chore(dialogflow): delete unuseful region tag "import libraries"
  dialogflow/go.mod
  dialogflow/go.sum
  dialogflow/intent_management/intent_management.go
Labels: api: dialogflow, samples

#5148 chore(dialogflow): delete unused region tag "import_libraries"
  dialogflow/detect_intent/detect_intent.go
Labels: api: dialogflow, samples

#5149 chore(vision): delete unused region tag "imports"
  vision/label/label.go
Labels: api: vision, samples

#5154 fix(vision): delete unused region tag "imports"
  vision/detect/detect.go
Labels: api: vision, samples

#5153 fix(language): delete unused region tag "language_imports"
  language/analyze/analyze.go
  language/go.mod
Labels: api: language, samples

#5159 chore(speech): delete unused region "imports"
  speech/snippets/enhanced_model.go
Labels: api: speech, samples

#5163 chore(vision): delete unused region tag "init"
  vision/label/label.go
Labels: api: vision, samples

#5171 chore(gae): migrate region intro_1 from docs/appengine/users/users.go
  docs/appengine/users/users.go
Labels: samples

#5179 chore(vision): delete duplicated sample/test from vision/label/*
  vision/label/README.md
  vision/label/label.go
  vision/label/label_test.go
Labels: api: vision, samples

#5176 chore(gae): delete unused sample from docs/appengine/taskqueue/push/modules.go
  docs/appengine/taskqueue/push/modules.go
Labels: samples

#5162 chore(language): delete unused region tag "init"
  language/analyze/analyze.go
Labels: api: language, samples

#5188 chore(gae): delete sample using_namespaces_with_the_Task_Queue
  docs/appengine/multitenancy/taskqueue/namespace_taskqueue.go
Labels: samples

#5174 chore: update dockerfiles to use go 1.23 as base
  appengine/go11x/tasks/handle_task/Dockerfile
  cloudsql/mysql/database-sql/Dockerfile
  cloudsql/postgres/database-sql/Dockerfile
  cloudsql/sqlserver/database-sql/Dockerfile
  eventarc/audit_storage/Dockerfile
  eventarc/generic/Dockerfile
  eventarc/pubsub/Dockerfile
  getting-started/devflowapp/Dockerfile
  getting-started/gopher-run/Dockerfile
  internal/cloudrunci/testingapp/Dockerfile
  memorystore/redis/cloud_run_deployment/Dockerfile
  memorystore/redis/gke_deployment/Dockerfile
  opentelemetry/instrumentation/app/Dockerfile
  profiler/hotapp/Dockerfile
  profiler/hotmid/Dockerfile
  run/custom-metrics/Dockerfile
  run/grpc-ping/Dockerfile
  run/grpc-server-streaming/Dockerfile
  run/hello-broken/Dockerfile
  run/helloworld/Dockerfile
  run/image-processing/Dockerfile
  run/logging-manual/Dockerfile
  run/markdown-preview/editor/Dockerfile
  run/markdown-preview/renderer/Dockerfile
  run/pubsub/Dockerfile
  run/sigterm-handler/Dockerfile
  run/system_package/Dockerfile
Labels: samples

#5189 chore(gae): delete sample using_namespaces_with_the_Datastore
  docs/appengine/multitenancy/datastore/namespace_datastore.go
Labels: samples

#5187 chore(gae): migrate regions from ../datastore/transactions/transactions.go
  docs/appengine/datastore/transactions/transactions.go
Labels: samples

#5175 chore(gae): rename region package_example_1
  docs/appengine/tools/unittest/package.go
Labels: samples

#5172 chore(gae): migrate region OAuth_and_App_Engine from docs/appengine/users/oauth.go
  docs/appengine/users/oauth.go
Labels: samples

#5169 chore(gae): rename region "intro_2" from ../gae/memcache/memcache.go
  docs/appengine/memcache/memcache.go
Labels: samples

#5167 chore(gae): rename region "intro" from docs/appengine/urlfetch/urlfetch.go
  docs/appengine/urlfetch/urlfetch.go
Labels: samples

#5165 chore(gae): rename region "intro" from ../taskqueue/push/taskqueue_push.go
  docs/appengine/taskqueue/push/taskqueue_push.go
Labels: samples

#5161 fix(gae): fix regions from gae/go11x/helloworld/helloworld.go
  appengine/go11x/helloworld/helloworld.go
Labels: samples

#5158 chore(speech): delete unused region tag "speech_transcribe_model_selection_imports"
  speech/snippets/model_selection.go
Labels: api: speech, samples

#5190 chore: Update the Spanner dependency to latest release v1.76.1
  spanner/go.mod
  spanner/go.sum
Labels: samples

#5196 feat(go): update go version in app.yaml for helloworld apps
  appengine/go11x/helloworld/app.yaml
  appengine_flexible/helloworld/app.yaml
Labels: samples

#5198 fix(gae): add deleted region tags
  appengine/go11x/helloworld/helloworld.go
Labels: samples
